### ISSUE TITLE
All - Improve log experience 

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#1009]
# Overview 

- [ ] Improve placing of log to help users to find it
- [ ] Make easier to use it, maybe print: `tail -f /path/log.file`
- [ ] Extra: Try to have a command for it
- [ ] Extra: Maybe to explore side window for tail the logs

```bash 
{"level":"info","time":"2022-12-22T12:20:13Z","message":"kubefirst started"}
Logging at: /app/logs/log_1671711613.log

... 
```

**Comment by echoboomer** [comment]
Logging hint has already been implemented.

https://github.com/kubefirst/kubefirst/blob/ff76d11d5605c35b3a77b73bb123c57811da229a/internal/helpers/setup.go#L11
