### ISSUE TITLE
Github-aws - On github installs commits are done by gitlab-bot

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#1014]
Some commits are done by `kubefirst-bot` and some are done by `gitlab-bot`:

![image](https://user-images.githubusercontent.com/53096417/209675992-8267a970-6651-4f00-8396-0b5213828d07.png)
![image](https://user-images.githubusercontent.com/53096417/209676030-e0face15-0327-46bc-bf19-4aafe4605a5e.png)

Possible Solution:
- [ ] Validate if we prefer to have all commits by kubefirst-bot.

**Comment by 6za** [comment]
Metaphor repos also have the same behavior: 
![image](https://user-images.githubusercontent.com/53096417/209676250-d556e080-38ed-40d2-bb67-6676251bcc30.png)

**Comment by echoboomer** [comment]
This is no longer an issue due to consolidation of which user processes commits.
