### ISSUE TITLE
The console pod creation failed on `local` if Docker cannot call api.segment.io

### ISSUE THREAD

**Issue by fharper** [kubefirst/kubefirst#1020]
The console pod creation failed on `local` if Docker cannot call api.segment.io which make the console unavailable when the user try to access it from `https://kubefirst.localdev.me/`. It should fail silently, and not be a breaking point.

Some people (like me) block telemetry connections by default for any applications, and even if the metrics helps us as a business, ethically, we cannot force people to activate them to use Kubefirst.

**Comment by 6za** [comment]
Based on the screen-sharing, it seems the console-app on local will not start, if it fails to send the telemetry to segment. 

Points for discussion: 
- [ ] How telemetry can be skipped on console app

Fix needed:
- [ ] Make console to fail silently, not degrading the deployment on argo, in case of lack of telemetry. (Is telemetry mandadory for console?)

**Comment by 6za** [comment]
Should console honor the value of this flag(`--use-telemetry` on local): 
https://github.com/kubefirst/kubefirst/blob/main/cmd/local/local.go#L56

- [ ] If skipped telemetry on the installation, should this be passed to the cluster installed to skip sending telemetry too.

**Comment by fharper** [comment]
> Should console honor the value of this flag(--use-telemetry on local):

I was going to create an issue about that as I think it should, but let's discuss about it here since they are related.

**Comment by 6za** [comment]
No worries, I just dumping my notes here connected to this issue, to avoid it to be forgotten next week.

**Comment by 6za** [comment]
So, after tests in local console honors telemetry selection:

**Comment by fharper** [comment]
This was fixed
