### ISSUE TITLE
Creating logs in `~/.k1` instead of current one

### ISSUE THREAD

**Issue by fharper** [kubefirst/kubefirst#1030]
Creating logs in `~/.k1` instead of creating them in the folder where the command is run.

It will prevent to have `logs` folders everywhere, and will make it easier to find all the logs.

**Comment by 6za** [comment]
Opening discussion on the topic: https://github.com/kubefirst/kubefirst/discussions/1031

**Comment by echoboomer** [comment]
All logs are currently generated at `~/.k1/logs`.
