### ISSUE TITLE
[WSL][Localhost] Error when pressing ENTER in localhost installation

### ISSUE THREAD

**Issue by marinhojess** [kubefirst/kubefirst#1038]
### **Description**

Error when trying to open github page at the beginning of localhost installation.

### **Environment**

**kubefirst-cli golang utility version**: development
**operating system**: Linux - Ubuntu (WSL)

### **Screenshots**

![image](https://user-images.githubusercontent.com/19623668/210248424-20560869-cb24-4911-8494-0a39a38be8bd.png)

### Steps to reproduce

Run `go run . local`

### Expected behaviour

Press Enter and open github page on browser.

**Comment by 6za** [comment]
this functionality, may help on that: 
https://github.com/kubefirst/kubefirst/blob/main/cmd/postInstall.go#L51
