### ISSUE TITLE
Ask for user confirmation when running kubefirst clean

### ISSUE THREAD

**Issue by marinhojess** [kubefirst/kubefirst#1040]
**What would you like to be added**:

Ask user for confirmation to destroy buckets when running `kubefirst clean --destroy-buckets`

**Why is this needed**:

Saves the user time by preventing the code from breaking and having to run the code again with the `--destroy-confirm` flag.

**Comment by echoboomer** [comment]
`clean` has been deprecated and similar functionality is not needed in `reset`.
