### ISSUE TITLE
[Docs]: reset user password detail incorrect - need to update to vault password reset details

### ISSUE THREAD

**Issue by johndietz** [kubefirst/kubefirst#1044]
### What type of suggestions?

Wrong Information

### What page is concerned?

https://docs.kubefirst.io/kubefirst/local/after-install.html#step-2-make-your-first-automated-terraform-change

### What is the issue?

"Once you've provided them this initial password, they can update their password throughout the platform by updating their GitLab user password in their Gitlab profile."

no gitlab in local, should describe the new vault password reset. verify details on all 3 "after install" docs with dev team.
- local
- gitlab
- github

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 6za** [comment]
Related to:
- #1084

**Comment by converge** [comment]
I was about to start this one, but Im not sure if there is still something to be done here.

**Comment by 6za** [comment]
Issue found, we mention gitlab on github installation:

**Comment by 6za** [comment]
I think this is covered on new vault page already on main, and PR https://github.com/kubefirst/kubefirst/pull/1145. 


If I missed anything, feel free to re-open.
