### ISSUE TITLE
[Docs]: local story requires a github-runner per repo for personal github accounts, no docs on this requirement

### ISSUE THREAD

**Issue by johndietz** [kubefirst/kubefirst#1064]
### What type of suggestions?

Missing Information

### What page is concerned?

https://docs.kubefirst.io/kubefirst/local/github-repositories.html

### What is the issue?

created a new kubefirst local repo that was just like metaphor-go, but the CI didn't work (see #1045). it turned out to be due to a requirement that any new repository needs a new action runner for personal repos. that needs to be be documented in local.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pagottoo** [comment]
Done, documented in the section Tips in metaphor common docs.
