### ISSUE TITLE
[Docs]:  Review tooling list of application

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#1091]
### What type of suggestions?

Missing Information

### What is the issue?

Z - TODO: Review this list of pages:
> I have feeling versions may be outdated.

Review this list of pages:
![image](https://user-images.githubusercontent.com/53096417/211609694-40c5e28e-df92-4b55-b1cb-b350eb1ae07c.png)

Action: 
- [ ] Check if there is any page that shouldn't be there.
- [ ] Check if the version is correct.
- [ ] Check if any application is missing on this list.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by converge** [comment]
done here https://github.com/kubefirst/kubefirst/pull/1127/files
