### ISSUE TITLE
update log level to debug

### ISSUE THREAD

**Issue by converge** [kubefirst/kubefirst#1096]
As a Kubefirst users I want to have full log details by default that includes relevant content that can be reported to the Kubefirst engineering team. So that when I run Kubefirst, I don't need to provide the `log-level debug` flag to generate full log for future report.

AC1: default log level is updated to debug 
AC2: debug level should not show credentials values

**Comment by 6za** [comment]
There was discussion in December to tone down and clean the logs. We need to chat with the team on that.

**Comment by 6za** [comment]
There was also deep effort to remove any creds logged in the logs by mistake, due some full objects logs. Info was already checked for that, Debug not yet.

**Comment by converge** [comment]
> There was also deep effort to remove any creds logged in the logs by mistake, due some full objects logs. Info was already checked for that, Debug not yet.

added a AC2 to the task.

**Comment by converge** [comment]
why set default log level back to default?

1. having Info as default log level make the impression installation failed for the end user, this is a 10min stop at the last log message:
![Screenshot 2023-01-11 at 10 22 15](https://user-images.githubusercontent.com/188671/211827572-23785689-7a13-479f-af5f-3d53d4fbfdec.png)

2. log-level flag was implemented for `local` only, end users wont have the possibility to set the log-level.
