### ISSUE TITLE
take advances of t.TempDir for unit tests

### ISSUE THREAD

**Issue by converge** [kubefirst/kubefirst#1097]
Go provides two nice functions to generate temporary folder and files, it would be nice to use them to avoid having this folder in the repository https://github.com/kubefirst/kubefirst/tree/main/test/artifacts/init

**Comment by converge** [comment]
I went a little further in the topic, there is actually a even better approach for tests, that is testing.TempDir, that self clean up after the test case finishes, I'll follow that for the tests in the /pkg folder that is not integration test for the commands.

**Comment by echoboomer** [comment]
Something like https://github.com/spf13/afero is probably a better idea.
