### ISSUE TITLE
ngrok memory leak

### ISSUE THREAD

**Issue by converge** [kubefirst/kubefirst#1099]
As a Kubefirst developer I want to handle a channel that is open for ngrok. So that, after the channel is not in use anymore, we close the running go routine and avoid memory leak.

AC1: ngrok functionality behaves the same
AC2: the opened channel is closed when the installation finish

**Comment by 6za** [comment]
Once the channel is closed, `atlantis` will not be usable on local. Is this the intended behavior?

**Comment by converge** [comment]
> Once the channel is closed, `atlantis` will not be usable on local. Is this the intended behavior?

yes, a non closed channel is a memory leak, we can close the channel before exiting the main process/kubefirst install.
