### ISSUE TITLE
kubefirst.init.completed is not being sent at init conclusion

### ISSUE THREAD

**Issue by converge** [kubefirst/kubefirst#1102]
issue: kubefirst.init.completed is not being sent at init conclusion

AC1: it should send a `kubefirst.init.completed` at the conclusion of the `init` command

**Comment by 6za** [comment]
Is this breaking `init` somehow, related to the installation side?

**Comment by converge** [comment]
> Is this breaking `init` somehow, related to the installation side?

it doesn't break the installation, but the metric is not sent.
