### ISSUE TITLE
terraform output from execution should be classified as info level log output

### ISSUE THREAD

**Issue by johndietz** [kubefirst/kubefirst#1109]
a recent logs refactor classifies terraform output as debug instead of info. 
a different recent change to make `info` the default log level is causing that tf output content to be omitted.
cli users will want that output by default
we will want it available for diagnosis / affirmation during triage.

AC:
- keep the default log level of info
- ensure all terraform execution detail is not omitted

**Comment by converge** [comment]
@johndietz I was thinking to update the log level because of this issue[1] wdty?

[1] https://github.com/kubefirst/kubefirst/issues/1096
