### ISSUE TITLE
footers are missing on our main branch docs

### ISSUE THREAD

**Issue by johndietz** [kubefirst/kubefirst#1110]
our current production docs have nice footers that guide users to the next topic
<img width="196" alt="image" src="https://user-images.githubusercontent.com/3649336/211975363-a2235aa0-bbcb-45f6-aa9a-ef50dbd5ff6c.png">

something has changed causing the footers to disappear on preprod / main
see bottom in production:
https://docs.kubefirst.io/kubefirst/local/install.html
[internal link only] see bottom in preprod:
https://docs.kubefirst.io/preprod/kubefirst/local/install.html

**Comment by converge** [comment]
closed by https://github.com/kubefirst/kubefirst/pull/1132
