### ISSUE TITLE
metaphor-frontend readme.md has broken detokenization links on local

### ISSUE THREAD

**Issue by johndietz** [kubefirst/kubefirst#1114]
see title

**Comment by 6za** [comment]
I was not able to find any token on local `metaphor-frontend`:
![image](https://user-images.githubusercontent.com/53096417/212398807-c507ae30-12c5-46fc-8012-6d652d5c91f5.png)

**Comment by 6za** [comment]
nothing found: 
![image](https://user-images.githubusercontent.com/53096417/212399011-8b0a936f-0274-4d77-9074-37b3911fe6a2.png)

**Comment by 6za** [comment]
Tested with a fresh local install.

**Comment by converge** [comment]
there is if github / gitlab to apply the flag value for the CHECKOUT_CWFT_TEMPLATE

**Comment by 6za** [comment]
yes, there a selector how to select the CWFt based on the provider, it was working on my detoken process.

**Comment by 6za** [comment]
![image](https://user-images.githubusercontent.com/53096417/212400368-a93d335b-c1b8-4902-be35-8b501e65d583.png)

**Comment by converge** [comment]
the template CI never worked, note added to "quality of life" doc
