### ISSUE TITLE
enable ngrok + atlantis in the `local connect` command

### ISSUE THREAD

**Issue by converge** [kubefirst/kubefirst#1115]
As a Kubefirst user I want to have Atlantis working after the installation is closed. For that, I'm able to use Atlantis after the installation is closed.

pre-requisite: have this[1] done before starting this issue is fixed before this task

AC1: ngrok opens a new tunnel
AC2: gitops user(installed) repository is update via GH API to update the webhook URL to use the ngrok URL

[1] https://github.com/kubefirst/kubefirst/issues/1099

**Comment by echoboomer** [comment]
This is no longer an issue with the latest ngrok in-cluster method.
