### ISSUE TITLE
Metaphor URLs should have (/app) at the end

### ISSUE THREAD

**Issue by marinhojess** [kubefirst/kubefirst#1153]
"/app" is missing at the end of metaphor and mtaphor-go url in handoff screen

![image](https://user-images.githubusercontent.com/19623668/212429511-1d1e0e9d-b533-436a-bd52-0fcf9681624b.png)

**Comment by 6za** [comment]
![image](https://user-images.githubusercontent.com/53096417/212698724-3b5ca5d8-619b-4f1a-9b9a-beedb21b6d40.png)

**Comment by 6za** [comment]
Waiting for approval.
