### ISSUE TITLE
GitHub stars bot, the return

### ISSUE THREAD

**Issue by converge** [kubefirst/kubefirst#1211]
Our beloved GitHub stars internal bot sends a message every time there is a new github star in the Kubefirst repository. Because we still dont automate it's deploy, we need to manually enable it again.

**Comment by 6za** [comment]
What are the AC for this ticket? 

Can we have a gitops version of it deployed to the management stack, so we don't loose it again on a newer release?

**Comment by converge** [comment]
I think it's a simple upload to AWS Lambda, if that's the case I'll postpone the deploy automation to follow the other priorities.

**Comment by converge** [comment]
wip:

**AC1:** update README with the build/push details
