### ISSUE TITLE
minio issue

### ISSUE THREAD

**Issue by converge** [kubefirst/kubefirst#1218]
this is a placeholder ticket, it needs to be updated with better description and ACs.

minio on local isn’t backed by disk. when memory is exhausted due to too many workflows, minio will restart and things get really messy. let’s fix that somehow.

**Comment by 6za** [comment]
Details: 
- [ ] Update persistence rules on `minio` to use something like a in cluster PVC or a localhost backed PVC, to allow read disk persistence instead of memory.  
- [ ] Update docs about new persistence requirements, where the user can find the data or remove the data.
