### ISSUE TITLE
[local] Gitops Repo  seems to be missing a runner for local

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#1257]
On the cloud template: 
- All repositories in the org are covered by this rule, allowing them to have self-hosted runneres available on github: 

https://github.com/kubefirst/gitops-template/blob/main/components/github-runner/github-runner.yaml#L24
> That include the gitops repo

On local, it seems only the metaphor repo supports github runner. I am not sure if this is by design or a missing deployment instruction. 

https://github.com/kubefirst/gitops-template/blob/main/localhost/components/github-runner/runnerdeployment.yaml

Due to the particularity of local, not be based on orgs, every repo requires an explicit deployment instruction.

therefore `gitops` seems to be missing a self-hosted runner instruction. 

Opening this ticket, just in case this is not by design.

**Comment by 6za** [comment]
PR submitted, in case this is a bug. 
Feel free to ignore and close in case it isn't.

**Comment by jarededwards** [comment]
hey @6za ! sorry for the slow response, we currently don't have a use case for runners on the gitops repository. we only use github runners on the application repositories associated with the platform so far, and atlantis is the only automation for IAC on the gitops repo. I'm going to close this for now but thank you for the quick pr and checking!
