### ISSUE TITLE
Detect if Docker is running before running `local` commands

### ISSUE THREAD

**Issue by fharper** [kubefirst/kubefirst#1312]
**What would you like to be added**:

Detect if Docker is running before running `local` commands

**Why is this needed**:

It would prevent the process to start, and as an example, when you create a new local cluster, the following error when the process need to create it.

<img width="789" alt="CleanShot 2023-02-27 at 09 25 24@2x" src="https://user-images.githubusercontent.com/1170989/221589749-f1826dc9-e672-49a5-b341-30d562b94a80.png">

**Comment by echoboomer** [comment]
https://github.com/kubefirst/kubefirst/blob/main/cmd/k3d/create.go#L721-L728
