### ISSUE TITLE
`destroy --help` shouldn't generate a log

### ISSUE THREAD

**Issue by fharper** [kubefirst/kubefirst#1380]
**What would you like to be added**:

`destroy --help` shouldn't generate a log

<img width="557" alt="CleanShot 2023-03-20 at 11 17 20@2x" src="https://user-images.githubusercontent.com/1170989/226456996-ba38bc44-5240-4114-baae-0aed5653c8f3.png">

**Why is this needed**:

Creating non-useful files + polluting the output.

**Comment by echoboomer** [comment]
Fixed by https://github.com/kubefirst/kubefirst/pull/1416.
