### ISSUE TITLE
Argo CD login via Vault doesn't work

### ISSUE THREAD

**Issue by fharper** [kubefirst/kubefirst#1461]
### Which version of kubefirst are you using?

2.0.0

### Which installation type?

None specific

### Which distributed Git provider?

None specific

### What is the issue?

When logged with Vault, we can connect to any other service, thanks to OIDC, but it's not working with Argo CD. We need to use the username/password provided in the handoff screen (purple rectangle showing all informations about the new cluster when the installation is completed).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by echoboomer** [comment]
This was fixed by a postsync hook.
