### ISSUE TITLE
allow us to destroy clusters from the cli

### ISSUE THREAD

**Issue by johndietz** [kubefirst/kubefirst#1522]

**Comment by donnalux** [comment]
@johndietz I think this issue can be closed.

**Comment by echoboomer** [comment]
It is now possible to run `kubefirst terraform set-env` with flags to generate a file that properly replaces the `VAULT_ADDR` variable. This file can then be sourced in a shell and you can run `terraform`. I was able to destroy a Digital Ocean cluster and GitLab repositories using this process.
