### ISSUE TITLE
confirm cli operational for all non-beta clouds

### ISSUE THREAD

**Issue by johndietz** [kubefirst/kubefirst#1525]

**Comment by echoboomer** [comment]
| Provider | Git    | Status |
| -------- | ------ | ------ |
| AWS      | GitHub |        |
| AWS      | GitLab |        |
| Civo     | GitHub | Ready       |
| Civo     | GitLab |  Ready      |
| K3d     | GitHub |       |
| K3d     | GitLab |       |
