### ISSUE TITLE
https instead of ssh for git providers

### ISSUE THREAD

**Issue by mickfeech** [kubefirst/kubefirst#1566]
**What would you like to be added**:
Give the ability for those that wish to use kubefirst to connect to git providers via https instead of ssh. 

**Why is this needed**:
Many organizations and companies turn off the ability to use ssh and require them to go through a http proxy to hit endpoints.

**Comment by PatrickLaabs** [comment]
Hey @mickfeech,

I am just wondering:
Do you mean using https instead of ssh at the creation time for the cluster?
Like `kubefirst k3d create --gitops-template-url "https://github.com/kubefirst/gitops-template.git"` ?

Best
Patrick

**Comment by Claywd** [comment]
Testing a implementation for this. Hoping to get it out soon @mickfeech !

**Comment by mickfeech** [comment]
kubefirst k3d create uses ssh to pull in repositories for standing up the cluster. The ask is to use https instead of ssh.

**Comment by Claywd** [comment]
Closed a little prematurely. 

@mickfeech the PRs referenced in this issue enable the k3d command to operate on both the https and ssh protocols. To use https ahead of our release next week

1. clone the kubefirst and runtime repositories
2. change directory into kubefirst 
3. run `go mod edit --replace github.com/kubefirst/runtime=/<REPLACE_WITH_PATH_TO_REPO>/runtime` 
4. then you can run `go run main.go k3d --git-protocol https` and any other flags you'd like to start using early.  

 
We will also release this next week for all the providers as well.

**Comment by Claywd** [comment]
Release 2.2 is out with k3d support for an https only flow. Enjoy and let us know if there are other issues.
