### ISSUE TITLE
Logs file info appear twice

### ISSUE THREAD

**Issue by fharper** [kubefirst/kubefirst#1571]
### Which version of kubefirst are you using?

208c9f20bf27c5fc2a0f83648f4c5f240f689e2c

### Which installation type?

Vultr

### Which distributed Git provider?

None specific

### What is the issue?

Logs file info appear twice

![CleanShot 2023-06-02 at 14 27 48@2x](https://github.com/kubefirst/kubefirst/assets/1170989/b86604f7-58aa-48f3-81aa-b10912ed9048)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by echoboomer** [comment]
Resolved by https://github.com/kubefirst/kubefirst/pull/1572
