### ISSUE TITLE
create new cli command for `kubefirst create github-cluster`

### ISSUE THREAD

**Issue by johndietz** [kubefirst/kubefirst#158]

**Comment by 6za** [comment]
Define the CLI `require` flags for the command, to ensure we know from get-go what is needed from github and how to differentiate from a `gitlab` installation.

**Comment by 6za** [comment]
We start as 2 different create journeys, on a later ticket we have a "wrapper" create that use flags to select the proper installation strategy.

**Comment by 6za** [comment]
Reviewing a bit the logic we use:

**Comment by 6za** [comment]
Based on this exploration: 
https://github.com/kubefirst/kubefirst/blob/eedfe3ed34c13a64d06193a55d9d3dd51e9fb93d/cmd/createGithub.go

Questions:
- [ ] Does anything changes on setup of [ArgoCD](https://github.com/kubefirst/kubefirst/issues/158)? 
- [ ] How to improve Hand-off screen to support github/gitlab?
> Different object, Object architecture, "Strategy pattern" or different pattern of reuse. 

Assumptions:
- OIDC/SSO will be handled by #157

**Comment by 6za** [comment]
Exploring a bit how to integrate to github to try to automate github access.

**Comment by 6za** [comment]
Github Actions needed: 
- [create repo](https://github.com/google/go-github/blob/master/github/repos.go#L393)
- [Add ssh key?](https://github.com/google/go-github/blob/master/github/users_keys.go#L82)
> do we create the keys, or the user does that

**Comment by 6za** [comment]
How to get the github token?

**Comment by 6za** [comment]
Added on #223
