### ISSUE TITLE
github-org flag not required before starting cluster creation on Vultr

### ISSUE THREAD

**Issue by fharper** [kubefirst/kubefirst#1584]
### Which version of kubefirst are you using?

208c9f20bf27c5fc2a0f83648f4c5f240f689e2c

### Which installation type?

Vultr

### Which distributed Git provider?

None specific

### What is the issue?

I ran the `beta vultr create` command, and I got this error `Error: something went wrong calling GitHub API during org lookup, http status code is: 404, and response is: "{\"message\":\"Not Found\",\"documentation_url\":\"https://docs.github.com/rest\"}"` which I assume is caused because I did use the `--github-org` flag. It should be require by the CLI before starting to do anything, like it does when I tried without any flags `Error: required flag(s) "alerts-email", "domain-name" not set`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fharper** [comment]
I had this unsubmitted draft issue in my browser, and should test it again with latest commits from main as it may have been fixed, but didn't want to lose it as I need to close my browser, and while writing it, just realized I could have saved the text elsewhere in the meantime 🤦‍♂️

**Comment by echoboomer** [comment]
Those flags are always required regardless of git provider. The flags that are git provider specific are not set to required because it's possible to not use one or the other. We can add a check but cannot rely on required command line flags.
