### ISSUE TITLE
version bump cwft in argo workflows needs to work with github as well

### ISSUE THREAD

**Issue by johndietz** [kubefirst/kubefirst#159]
version bump is currently doing patch bumps and should be doing minor bumps

**Comment by 6za** [comment]
I think this refer to metaphors updates around this code: https://github.com/kubefirst/metaphor-template/blob/main/.argo/publish.yaml#L70

And using this CWFT: 
https://github.com/kubefirst/gitops-template/blob/main/components/argo-cwfts/cwft-helm.yaml#L81

**Comment by 6za** [comment]
Is this a 1.9.0 thing or a post 1.9.0 thing?
