### ISSUE TITLE
github-actions runner running in kubernetes with access to argo submit workflow

### ISSUE THREAD

**Issue by johndietz** [kubefirst/kubefirst#160]
see
https://github.com/kubefirst/builder-tmps/blob/main/.github/actions/argo-submit/action.yaml

**Comment by 6za** [comment]
Solved, github  runner available on github installs. 
<img width="874" alt="image" src="https://user-images.githubusercontent.com/53096417/189715285-07d0dd04-814e-4e56-94dc-b21f71e4da39.png">
