### ISSUE TITLE
launch down shouldn't complete successfully if Docker isn't running

### ISSUE THREAD

**Issue by fharper** [kubefirst/kubefirst#1605]
### Which version of kubefirst are you using?

v2.1

### Which cloud provider?

None specific

### Which installation type?

UI (Console app)

### Which distributed Git provider?

None specific

### What is the issue?

If you run `kubefirst launch down` when Docker is not running, the command complete successfully in the terminal with this output

```
------------------------------------------------
Follow your logs in a new terminal with:
   tail -f -n +1 /Users/fharper/.k1/logs/log_1686598585.log
------------------------------------------------
INFO[0000] Deleting k3d cluster for Kubefirst console and API
INFO[0000] k3d cluster for Kubefirst console and API deleted successfully
INFO[0000] Deleting cluster directory at /Users/fharper/.k1/kubefirst-console
```

Firstly, the CLI should output an error if it's the case. See the error from the logs

`2023-06-12T15:36 ERR pkg/shell.go:33 > error executing command: ERRO[0000] Failed to get nodes for cluster 'kubefirst-console': docker failed to get containers with labels 'map[k3d.cluster:kubefirst-console]': failed to list containers: Cannot connect to the Docker daemon at unix:///Users/fharper/.docker/run/docker.sock. Is the docker daemon running?`

Secondly, the `launch down` command should check if Docker is running before running.

Thirdly, if the cluster is not deleted because of any errors, the following commands should not continue to run, as once I started Docker, and tried to ran the command again, I got the following error which I assume is because my configurations were wiped in my previous attempt.

```
INFO[0000] Deleting k3d cluster for Kubefirst console and API
FATA[0000] error deleting k3d cluster
```

Here's what was in the logs

```
2023-06-12T15:37 INF pkg/helpers.go:78 > Using config file: /Users/fharper/.kubefirst
2023-06-12T15:37 ERR pkg/shell.go:29 > error executing command error="fork/exec /Users/fharper/.k1/kubefirst-console/tools/k3d: no such file or directory"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by echoboomer** [comment]
The last release for cli implemented a check for Docker for all `launch` steps.
