### ISSUE TITLE
Cannot destroy a cluster if the handoffscreen is still up

### ISSUE THREAD

**Issue by fharper** [kubefirst/kubefirst#1619]
### Which version of kubefirst are you using?

v2.1.1

### Which cloud provider?

k3d (local)

### Which installation type?

CLI

### Which distributed Git provider?

None specific

### What is the issue?

Seems like the handoff screen is using port 9000 (I was using k3d, I assume it's the same for all CLI installations), as I cannot destroy my cluster when it's up. If I tried, I'll see the following error in the `destroy` logs

```
023-06-14T15:33 INF pkg/helpers.go:78 > Using config file: /Users/fharper/.kubefirst
2023-06-14T15:33 FTL cmd/k3d/destroy.go:41 > port 9000 is in use - this port is required to tear down your kubefirst environment - please close any existing port forwards before continuing
```

When I check which app is using the port with `lsof -i tcp:9000` I see it's kubefirst

```
COMMAND     PID    USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
kubefirst 75133 fharper   15u  IPv4 0xc12152017e089da9      0t0  TCP localhost:cslistener (LISTEN)
kubefirst 75133 fharper   16u  IPv6 0xc12151f31b9d7f81      0t0  TCP localhost:cslistener (LISTEN)
```

When I get out of the handoff screen, the ports are freed, and I can proceed with destroying my cluster. I know it make sense to get out of that screen if you want to destroy it, but it could be in another tab, like it was for me, and since there's nothing telling the user it's the problem, that they need to close it, it can lead to some bad user experience.

I'm not sure if it make sense to use another port to do that, or why the handoff screen needs port 9000 once it's displayed, but at least we could check if it's the issue when destroying, and advice the user consequently.

May want to do something in conjunction with the issue #1618.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by echoboomer** [comment]
Port 9000 is used for minio which is required as the terraform state backend. The way the CLI works, all of the ports it opens for port forwarding remain open until the cli process exits. I will add a statement to the handoff screen informing the user what's going on with the ports being open and how to exit the process before running any future commands.

**Comment by echoboomer** [comment]
Resolved by latest runtime release. https://github.com/kubefirst/kubefirst/pull/1624
