### ISSUE TITLE
add metaphor-go to the stack - feature paired with metaphor

### ISSUE THREAD

**Issue by johndietz** [kubefirst/kubefirst#162]

**Comment by johndietz** [comment]
polyrepo (isolated for the one app) for this - don't add to metaphor, we'll need a metaphor-go-template repo to house the code

**Comment by 6za** [comment]
@converge on my count, What is missing to complete this is to have github runner to trigger deploying changes, similar to gitlab, right?

**Comment by converge** [comment]
@6za I would say the ticket is done. We have metaphor-go up and running and feature paired with metaphor JS.

Im closing the ticket, feel free to re-open it if there is something we missed.

**Comment by converge** [comment]
Metaphor is our demo application. 
At previous release, after Kubefirst is installed, Metaphor is available at a specific address inside the cluster.

Now, at `1.9`, we broke Metaphor in 3 pieces:
- Metaphor Frontend
- Metaphor JavaScript/Node (API)
- Metaphor Go (API)

Metaphor frontend is what the user will have first contact with the demo application, this demo application(Metaphor) is consuming the data that is coming from Metaphor JavaScript/Node and Metaphor Go.

Metaphor JS and Metaphor Go uses the same API specification, but are written using different languages, to demo how different languages can be integrated into our cluster/platform.

This is the [OpenAPI definition for the Metaphor JavaScript/Node and Go](https://github.com/kubefirst/metaphor-go-template/blob/main/third_party/swagger-ui/openapi.yaml).
![Screenshot 2022-09-06 at 17 01 04](https://user-images.githubusercontent.com/188671/188727697-62082b28-eb2d-45de-b110-0479f2c5eb4d.png)
