### ISSUE TITLE
Bug: Created GitOps Repo also containing other Cloud Provider files as well, which are not needed

### ISSUE THREAD

**Issue by PatrickLaabs** [kubefirst/kubefirst#1633]
### Which version of kubefirst are you using?

v2.1.4

### Which cloud provider?

Civo

### Which installation type?

UI (Console app)

### Which distributed Git provider?

GitHub

### What is the issue?

Running Kubefirst UI on a local kubernetes cluster (created with 'kubefirst launch up') and setting everything up for using civo as the provider and github as the scm.

As the Kubefirst UI creates everything needed to provision the kubernetes cluster on civo, it will - of course - create the gitops repo, which will also contain the files for the gcp provider.

Since this not needed, I assume it might be a bug 😄 
![Bildschirmfoto 2023-06-17 um 00 26 16](https://github.com/kubefirst/kubefirst/assets/12104649/b28b9fe3-3182-4c3e-9f5d-f90eb4a6e62f)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by echoboomer** [comment]
@PatrickLaabs thanks for reporting this - we actually already caught it and it will be patched in the next release.
