### ISSUE TITLE
Console display no error when kbot SSH key exist

### ISSUE THREAD

**Issue by fharper** [kubefirst/kubefirst#1649]
### Which version of kubefirst are you using?

v2.1.7

### Which cloud provider?

Civo

### Which installation type?

CLI

### Which distributed Git provider?

GitLab

### What is the issue?

When I ran a new create command for Civo with GitLab from the CLI, the process ended without any errors.

<img width="1174" alt="CleanShot 2023-06-26 at 16 16 50@2x" src="https://github.com/kubefirst/kubefirst/assets/1170989/fe85e5cf-254c-44b2-a92a-3dd7ff08715f">

But when I looked in the logs, I saw `2023-06-26T16:12 FTL cmd/civo/create.go:788 > ssh key kbot-ssh-key already exists and key data has drifted - please remove before continuing`. The console should display a proper error message, so the user don't have to check the logs. Even better, it should be check during the preflight.

I assume the cloud is not important, and probably the same on GitHub.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by echoboomer** [comment]
This is patched in the next release.

**Comment by fharper** [comment]
That was fast 😅

**Comment by echoboomer** [comment]
This has since been patched.
