### ISSUE TITLE
Suppress "helpful box" on CLI creates for easier scripting

### ISSUE THREAD

**Issue by abangser** [kubefirst/kubefirst#1713]
### What is your feature idea?

Can you provide a `quiet` type flag for running a CLI create so that the helpful box at the end does not appear?

### Why is it needed?

This box really is helpful...to humans. But in the world of experienced kubefirst users and/or scripting it requires exiting before continuing on with the workflow.  Ideally I could provide a flag to the create to say "please just create and then give me back to the terminal!".

### Is this missing feature preventing you from using kubefirst?

- [ ] Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abangser** [comment]
My bad, it is possible with the `-ci` parameter 🎉

**Comment by abangser** [comment]
So turns out I just had to read a bit more about the CLI! The use of `--ci` is _nearly_ the behaviour I expect. Just that it still auto opens a browser (probably OK?) but when it does it navigates to `localhost` instead of `kubefirst.kubefirst.dev`.

While this is non blocking for me as the DNS for `kubefirst.kubefirst.dev` is working, it makes me wonder if there is some other impact to using `--ci` that I am not aware of.

Leaving this here for visibility incase someone else looks into this, but happy for you to close if you confirm that `ci` doesn't have any other adverse affects!

**Comment by fharper** [comment]
The issue with opening `localhost` instead of `kubefirst.kubefirst.dev` is not related to the `ci` flag usage. See https://github.com/kubefirst/kubefirst/issues/1808

Good idea to remove opening the browser automatically part of the `ci` flag though.

**Comment by fharper** [comment]
Should be in the next release 🎉

**Comment by fharper** [comment]
FYI, I'll close my PR, as the next release will have a refactor CLI, which won't open by default the console in the browser, and won't make the process wait for the user to terminate the handoff screen.

I'll keep this issue open until the release.

**Comment by fharper** [comment]
So except with k3d, which still use the previous CLI logics, all clouds are now using the new CLI. The handoff screen doesn't show like it used to, and the new one doesn't hand the process anymore. It still opening the browser thought.

@abangser: should we consider this issue close since it's not hanging the process anymore after a cluster creation?

**Comment by abangser** [comment]
Makes sense to me! And with the `--ci` flag we can also workaround. 

Happy to close ☺️
