### ISSUE TITLE
Cloudflare Origin Certs

### ISSUE THREAD

**Issue by claywd** [kubefirst/kubefirst#1718]
### What is your feature idea?

Support cloudflare origin certs in addition to letsencrypt so we can speed up cluster create times and harden our production stance. 

### Why is it needed?

letsencrypt runs out of certs consistently effectively making tlds useless for a week at a time. 

### Is this missing feature preventing you from using kubefirst?

- [X] Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fharper** [comment]
@johndietz took over this task due until @jarededwards is back
