### ISSUE TITLE
Consule UI logs goes out of the box when smaller viewport

### ISSUE THREAD

**Issue by fharper** [kubefirst/kubefirst#1735]
### Which version of kubefirst are you using?

v2.2.5

### Which cloud provider?

None specific

### Which installation type?

UI (Console app)

### Which distributed Git provider?

None specific

### What is the issue?

When the browser viewport become smaller than a specific width, the logs from the Console UI displayed outside of the "logs box".

https://github.com/kubefirst/kubefirst/assets/1170989/ef6e6745-6895-4013-90cb-782c6e0829de

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by D-B-Hawk** [comment]
[PR for fix](https://github.com/kubefirst/console/pull/446)
