### ISSUE TITLE
K3s provisioning

### ISSUE THREAD

**Issue by DrummyFloyd** [kubefirst/kubefirst#1748]
### What is your feature idea?

would be great to have a feature to populate a K3S cluster on-premise such as 

`kubefirst k3s create --ip-masters x.yy.z.xx, x.y.z.xz   --ip-worker x.x.x.x, y.y.y.y .. ip-lb x.x.x.x/16` 
edit: or directly pass the yaml config of k3s installation

k3s provide some already CLI cmd to manage this installation and joining nodes together.
we only need as a prerequisite a get an ssh access to those IP server adresses.

then , we just need managed the easy LoadBalancer [metallb](https://metallb.universe.tf/) then do the classical stuff made available by kubefirst and his gitops-template.

### Why is it needed?

because sometimes Cloud provider is much more expensive than actual machine/VM

if it's accepted i'll be glad to contribute to this , if i managed to find some time with my actual work.

thank you guys 

### Is this missing feature preventing you from using kubefirst?

- [x] Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

what going on !
- 

due to the hard rework of the CLI and API , need to make some rework 

- [x] Kubefirst: include k3s cli to create and destroy [here](https://github.com/kubefirst/kubefirst/pull/1875) 
- [ ] kubefirst-api: integrate all the need to call the gitops template and deal with it (WIP)
- [x] (GITLAB) gitops-template: [here](https://github.com/kubefirst/gitops-template/pull/659)
- [ ] (GITHUB) gitops-template: [here](https://github.com/kubefirst/gitops-template/pull/659)

**Comment by fharper** [comment]
Thanks for the suggestion, and the proposition to contribute to kubefirst @DrummyFloyd 🫶

For others, the discussion about this feature idea is happening in the #contributors channel of our [Slack community](https://kubefirst.io/slack).

**Comment by DrummyFloyd** [comment]
Thank you for you help guys!!!

**Comment by fharper** [comment]
@DrummyFloyd : thanks to you!

I'll start working on the docs next week.

**Comment by maxiar** [comment]
Hi! I'm interesting in this feature, how to work that? Any beta doc?

**Comment by DrummyFloyd** [comment]
hi @maxiar , dunno when the official Beta will be released, but don't worry it should be matter of days =)

**Comment by jarededwards** [comment]
hi @maxiar we released k3s in beta last week. we dont have documentation together yet but will be working on it as soon as we can. in the meantime what we were doing internally if it helps you put together something is run [this teraform](https://github.com/kubefirst/code-samples/tree/main/civo/examples/terraform/kubernetes-vms) that provisions vms in the Civo cloud and then once those are provisioned, taking the and running the following command
```
kubefirst beta k3s create \
    --servers-args "--disable traefik,--write-kubeconfig-mode 0644" \
    --alerts-email <your@email.com> \
    --domain-name <your-domain> \
    --gitlab-group <gitlab-group> \
    --git-provider gitlab \
    --servers-private-ips <private-ip-1>,<private-ip-2>,<private-ip-3> \
    --servers-public-ips <public-ip-1>,<public-ip-2>,<public-ip-3> \
    --ssh-privatekey <ssh-key-path> \
    --ssh-user root \
    --cluster-name <cluster-name>
    ```
    if you need any further help feel free to join our slack community and we can help as we can. thanks for your interest in kubefirst!

**Comment by maxiar** [comment]
Ok, I will test it next week.. only work with gitlab? No github yet?

**Comment by fharper** [comment]
@maxiar for now, it's only available on GitLab, but we will add GitHub before moving k3s out of beta.

**Comment by maxiar** [comment]
Hi! Any News for github versión? 
Where is the progress task for that, because this thread is closed...

Thanks in advanced..

**Comment by DrummyFloyd** [comment]
> Hi! Any News for github versión? Where is the progress task for that, because this thread is closed...
> 
> Thanks in advanced..

hi @maxiar , fromwhat i know, it should be still plan , but dunno how K1 teams are organized, 

from my side, i'm working on others stuff atm, but i can look to make a PR this asap , but i'lll will need help for review =) , as soon as i get a draft PR, do want me to ping you for test purpose ?

**Comment by maxiar** [comment]
Yes, of course, tell me to test it... 

Thanks!

**Comment by DrummyFloyd** [comment]
> Yes, of course, tell me to test it...
> 
> Thanks!

=> https://github.com/kubefirst/gitops-template/pull/758 there it is (sorry don't have much time to test it :/ )
