### ISSUE TITLE
aws: metaphor ghcr package access set to internal but required public to pull from cluster

### ISSUE THREAD

**Issue by cameronraysmith** [kubefirst/kubefirst#1764]
### Which version of kubefirst are you using?

2.2.9

### Which cloud provider?

AWS

### Which installation type?

CLI

### Which distributed Git provider?

GitHub

### What is the issue?

After installing kubefirst to aws, I had to make the metaphor ghcr package, which was appropriately set to internal, public in order for the cluster to be able to pull the image to complete the dev/stage/prod metaphor deployments. Indeed, setting the ghcr metaphor package to public immediately resolved the image pull failure/backoff.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fharper** [comment]
Thanks for the report @cameronraysmith, we will look into that.

**Comment by cameronraysmith** [comment]
This seemed to be confounded with presence/absence of repo/package:tag vs repo:tag alone so I'll close this for now and reopen if that's proved wrong.
