### ISSUE TITLE
GitOps catalog failed to load if there are single quotes inside an app secret label

### ISSUE THREAD

**Issue by fharper** [kubefirst/kubefirst#1781]
### Which version of kubefirst are you using?

ALL

### Which cloud provider?

None specific

### Which installation type?

UI (Console app)

### Which distributed Git provider?

None specific

### What is the issue?

GitOps catalog failed to load if there are single quotes inside an app secret label. The error `json: cannot unmarshal object into Go struct field GitopsCatalogAppSecretKey.secret_keys.value of type string`, so I assume we do not sanitize the content. Probably worth checking all string values as it may be an issue with other properties.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tomekz** [comment]
Hey I would like to work on this issue

**Comment by fharper** [comment]
@tomekz sorry about that, it was also fixed. We need to be better at closing our resolved issues!
