### ISSUE TITLE
GitOps Catalog application's secrets labels long description are truncated

### ISSUE THREAD

**Issue by fharper** [kubefirst/kubefirst#1782]
### Which version of kubefirst are you using?

ALL

### Which cloud provider?

None specific

### Which installation type?

UI (Console app)

### Which distributed Git provider?

None specific

### What is the issue?

GitOps secrets labels long description are truncated: they should displayed on multilines

<img width="1257" alt="CleanShot 2023-08-29 at 09 27 34@2x" src="https://github.com/kubefirst/kubefirst/assets/1170989/0bdd99a7-e4ff-4850-992a-97a2c0c8c5fd">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tomekz** [comment]
Seems like this issue is fixed already 

![Screenshot 2023-10-18 at 21 03 05](https://github.com/kubefirst/kubefirst/assets/2116354/7dbc08e9-7bcd-4b1f-9fcf-885eafaf7a31)

**Comment by fharper** [comment]
Oops, we forgot to close this issue, thanks @tomekz
