### ISSUE TITLE
Uppercase --github-org should be lowercased to prevent publish failures

### ISSUE THREAD

**Issue by alechp** [kubefirst/kubefirst#1790]
### Problem

- Our github org name is `Capswan`
- In the CLI, provided `--github-org Capswan`
- This causes metaphor to fail

![image](https://github.com/kubefirst/kubefirst/assets/3058939/38793814-a6c6-46f9-b026-e2a6a214bfb6)

This isn't quite a "bug" but it would be a quality-of-life improvement to automatically lowercase

### Quick Fix
If this change isn't implemented, the kubefirst user can simply 
a. Not make my mistake when using the CLI command (ie. use lowercase in `--github-org <org>`)
b. After the cluster is deployed, manually update all uppercase org-names to lowercase names 
> Important context here: I changed every `Capswan` to `capswan` in the `gitops` repo and that didn't resolve it. It wasn't resolved until updating `.github/workflows/main.yaml` in the `metaphor` repo. Specifically, the container registry URL
> <img width="884" alt="Screenshot 2023-08-31 at 8 37 40 PM" src="https://github.com/kubefirst/kubefirst/assets/3058939/7ccbdd3e-b560-4cfb-b9f0-b902c12ebdd6">

- After updating, the github action finally works:
<img width="2098" alt="Screenshot 2023-08-31 at 8 42 34 PM" src="https://github.com/kubefirst/kubefirst/assets/3058939/37ee8c44-e3b7-4020-bfee-86ca2a0bb7a0">

- However, after the deploy, the image fails to pull (I assume because the image artifact in the container registry would be stored under the same wrongly capitalized name; ie. `Capswan` instead of `capswan`)
> <img width="1659" alt="Screenshot 2023-08-31 at 8 47 59 PM" src="https://github.com/kubefirst/kubefirst/assets/3058939/b03efeef-e027-4e00-a6e9-87ca24683cc6">
> <img width="2672" alt="Screenshot 2023-08-31 at 8 46 42 PM" src="https://github.com/kubefirst/kubefirst/assets/3058939/0c75ecd8-5df5-42b6-9ee8-f5560e478474">
> <img width="2165" alt="Screenshot 2023-08-31 at 8 48 12 PM" src="https://github.com/kubefirst/kubefirst/assets/3058939/daf27d99-444e-43b1-8d3d-160592e843da">

### Context 

Conversation with @Claywd and @cameronraysmith:
> <img width="683" alt="Screenshot 2023-08-31 at 8 38 59 PM" src="https://github.com/kubefirst/kubefirst/assets/3058939/28e02e64-0f2a-4fa4-90b0-03afff2e85f1">
> <img width="599" alt="Screenshot 2023-08-31 at 8 39 08 PM" src="https://github.com/kubefirst/kubefirst/assets/3058939/b4b8ec07-e35a-49d7-b67d-778be04da905">

### Is this missing feature preventing you from using kubefirst?

- [ ] Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fharper** [comment]
Thanks for reporting this issue @alechp. We'll fix this.

**Comment by alechp** [comment]
Addressed by @Claywd in this PR:
https://github.com/kubefirst/kubefirst/pull/1793

This issue is probably good to close; currently testing on a fresh deploy to confirm:
<img width="1284" alt="Screenshot 2023-09-01 at 8 02 43 PM" src="https://github.com/kubefirst/kubefirst/assets/3058939/a041b2c9-fe01-4780-9f61-4a60d8a0b860">
