### ISSUE TITLE
`AWS` - `Metaphor` app fails to pull due to image name mismatch

### ISSUE THREAD

**Issue by alechp** [kubefirst/kubefirst#1801]
### Which version of kubefirst are you using?

2.2.17

### Which cloud provider?

AWS

### Which installation type?

CLI

### Which distributed Git provider?

GitHub

### What is the issue?

# Problem

![screenshot_2023-09-01_at_4 28 07_pm](https://github.com/kubefirst/kubefirst/assets/3058939/855660fe-31a6-4e16-bd8a-9306913aaa71)

- Metaphor image is successfully published 
- Image fails to pull due to name mismatch
   - Metaphor is checking `ghcr.io/<GITHUB_ORG>/metaphor:hash` 
   - Gitops is publishing to `ghcr.io/<GITHUB_ORG>/metaphor/metaphor:hash` (note the duplicative metaphor)
   
![image](https://github.com/kubefirst/kubefirst/assets/3058939/19a33321-5077-4554-abc1-cdc152114798)

Similar to the GCP issue here: https://github.com/kubefirst/kubefirst/pull/1774, @cameronraysmith submitted a fix for AWS here: https://github.com/kubefirst/kubefirst/pull/1797

I believe @Claywd is currently looking into this (screenshots below for context)

### Additional context
<img width="757" alt="Screenshot 2023-09-04 at 5 33 03 PM" src="https://github.com/kubefirst/kubefirst/assets/3058939/30d2dd97-6af9-48dc-9e7a-84feb8e95af9">

<img width="754" alt="Screenshot 2023-09-04 at 5 33 17 PM" src="https://github.com/kubefirst/kubefirst/assets/3058939/376dd9c6-f75e-4a6b-aaba-72df81a345f5">

<img width="757" alt="Screenshot 2023-09-04 at 5 32 30 PM" src="https://github.com/kubefirst/kubefirst/assets/3058939/b9b6eea4-057c-4013-8ed7-6f04ef7e9349">

### Related issues
- https://github.com/kubefirst/kubefirst/issues/1788
- https://github.com/kubefirst/kubefirst/issues/1764
- https://github.com/kubefirst/kubefirst/issues/1790

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alechp** [comment]
- Fixes that I originally tried (URL change based on @cameronraysmith's suggestion, the `application.yaml` change based on changes that are being made to Civo)
> <img width="1856" alt="Screenshot 2023-09-04 at 6 51 22 PM" src="https://github.com/kubefirst/kubefirst/assets/3058939/5ad102bb-aa78-45dd-a07e-26232ff089b0">

- Tried digging into registry and noticed that it's unavailable
> <img width="1392" alt="Screenshot 2023-09-04 at 6 50 51 PM" src="https://github.com/kubefirst/kubefirst/assets/3058939/92179b32-6abe-4aa0-86a7-1bf7009831c7">
> <img width="1392" alt="Screenshot 2023-09-04 at 6 50 56 PM" src="https://github.com/kubefirst/kubefirst/assets/3058939/8624642f-f9e1-43fc-9350-8036aa74eca3">

**Comment by fharper** [comment]
Thanks for reporting this issue @alechp: someone will review @cameronraysmith's PR soon.

**Comment by alechp** [comment]
Tried the build again. Getting `no such file or directory` for `registry/development/components/development/metaphor/Chart.yaml`:

<img width="2483" alt="Screenshot 2023-09-11 at 8 15 04 PM" src="https://github.com/kubefirst/kubefirst/assets/3058939/665973d9-e9fe-4759-a004-781514a064ff">

When I dig into the `gitops` repo, I notice that the specified `--cluster-name` passed to `kubefirst aws create` is missing from the path that's being checked:
<img width="1249" alt="Screenshot 2023-09-11 at 8 16 07 PM" src="https://github.com/kubefirst/kubefirst/assets/3058939/d04e4df6-a5d0-48a2-bdc1-839cb5fd5b1f">

### Full log
```
metaphor-development-58bfec9-gttdz-set-environment-version-3227680445: setting wrapper Chart.yaml to version: 0.0.1-rc.58bfec9
metaphor-development-58bfec9-gttdz-set-environment-version-3227680445: sed: can't read registry/development/components/development/metaphor/Chart.yaml: No such file or directory
metaphor-development-58bfec9-gttdz-set-environment-version-3227680445: time="2023-09-12T03:12:17.257Z" level=info msg="sub-process exited" argo=true error="<nil>"
metaphor-development-58bfec9-gttdz-set-environment-version-3227680445: time="2023-09-12T03:12:17.258Z" level=info msg="/src -> /var/run/argo/outputs/artifacts/src.tgz" argo=true
metaphor-development-58bfec9-gttdz-set-environment-version-3227680445: time="2023-09-12T03:12:17.258Z" level=info msg="Taring /src"
metaphor-development-58bfec9-gttdz-set-environment-version-3227680445: time="2023-09-12T03:12:17.381Z" level=info msg="archived 293 files/dirs in /src"
metaphor-development-58bfec9-gttdz-set-environment-version-3227680445: Error: exit status 2
metaphor-development-58bfec9-gttdz Failed at 2023-09-12 03:12:24 +0000 UTC
```

### Context
- running from source, not 2.2.17
- This is the last commit on kubefirst as of testing this script:
> https://github.com/kubefirst/kubefirst/commit/38c4d4fa7d691657956c785220bfa8b880b9357d

**Comment by alechp** [comment]
Source of the issue from https://github.com/kubefirst/kubefirst/issues/1801#issuecomment-1714902355 is due to the `metaphor/github/main.yaml` workflow setting the cluster name to the environment

<img width="1456" alt="Screenshot 2023-09-11 at 8 32 16 PM" src="https://github.com/kubefirst/kubefirst/assets/3058939/7d6584bd-c096-4e52-a282-32438bf45c42">

I fixed this by updating the fullChartPath parameter in `metaphor/.argo/deploy.yaml` from `registry/{{workflow.parameters.clusterName}}/components/{{workflow.parameters.environment}}/{{workflow.parameters.appName}}/Chart.yaml` to `       registry/capswancloud/components/{{workflow.parameters.environment}}/{{workflow.parameters.appName}}/Chart.yaml`

You can see this matches the generated value:
<img width="544" alt="Screenshot 2023-09-11 at 8 34 50 PM" src="https://github.com/kubefirst/kubefirst/assets/3058939/57010e81-b895-4600-8519-c4202230669f">

The actual fix would be to update the `-p clusterName` in each stage. This would also address the subsequent failure in `metaphor/.argo/release.yaml` where it also references `workflows.parameters.clusterName`

**Comment by alechp** [comment]
The following manual changes gets Github Actions workflow to pass all the way through release:

1. fullChartPath value in `metaphor/.argo/deploy.yaml` and `metaphor/.argo/release.yaml` (2 files, same update in both):
From:
```
              parameters:
                - name: fullChartPath
                  value: 'registry/{{workflow.parameters.clusterName}}/components/{{workflow.parameters.environment}}/{{workflow.parameters.appName}}/Chart.yaml'
```
To:
```
              parameters:
                - name: fullChartPath
                  value: 'registry/WHATEVER_VALUE_YOU_PASSED_TO_--cluster-name_IN_CLI/components/{{workflow.parameters.environment}}/{{workflow.parameters.appName}}/Chart.yaml'
```

2. For sake of consistency (although this doesn't fix it by itself which is why I include it as second priority) update the clusterName in `staging`, `development` and `production`. Need to update once for each stage:
From:
```
      - name: development
        run: |
          echo "commit sha $GITHUB_SHA"
          argo version --short
          argo submit .argo/deploy.yaml \
            --generate-name="${GITHUB_REPOSITORY_NAME_PART}-development-${GITHUB_SHA_SHORT}-" \
            -p appName="${GITHUB_REPOSITORY_NAME_PART}" \
            -p branch="${GITHUB_REF_NAME}" \
            -p clusterName="development" \
            -p environment="development" \
            -p gitUrlNoProtocol="git@github.com:${GITHUB_REPOSITORY_OWNER_PART_SLUG}" \
            -p shortSha="${GITHUB_SHA_SHORT}" \
            --wait --log
```
To:
```
      - name: development
        run: |
          echo "commit sha $GITHUB_SHA"
          argo version --short
          argo submit .argo/deploy.yaml \
            --generate-name="${GITHUB_REPOSITORY_NAME_PART}-development-${GITHUB_SHA_SHORT}-" \
            -p appName="${GITHUB_REPOSITORY_NAME_PART}" \
            -p branch="${GITHUB_REF_NAME}" \
            -p clusterName="WHATEVER_VALUE_YOU_PASSED_TO_--cluster-name_IN_CLI" \
            -p environment="development" \
            -p gitUrlNoProtocol="git@github.com:${GITHUB_REPOSITORY_OWNER_PART_SLUG}" \
            -p shortSha="${GITHUB_SHA_SHORT}" \
            --wait --log
```

3. Add whitespace to metaphor Chart

Context:
<img width="848" alt="Screenshot 2023-09-12 at 2 59 28 PM" src="https://github.com/kubefirst/kubefirst/assets/3058939/e625c334-b400-45e0-b76d-ce90a8c59d1f">
<img width="825" alt="Screenshot 2023-09-12 at 2 59 46 PM" src="https://github.com/kubefirst/kubefirst/assets/3058939/f773826a-1da1-4854-a4d0-f36a83411339">

**Comment by alechp** [comment]
Despite GH Action succeeding, still failing to deploy. PUblish failed multiple times, and the dev/stage/prod stuck as pending indefinitely (left it running since yesterday)

### Screenshots

> <img width="2672" alt="Screenshot 2023-09-13 at 1 01 31 PM" src="https://github.com/kubefirst/kubefirst/assets/3058939/6a5efb91-7d19-4950-9d03-f7b1a18f17e8">

> <img width="2077" alt="Screenshot 2023-09-13 at 1 04 27 PM" src="https://github.com/kubefirst/kubefirst/assets/3058939/d5594a33-4f4a-4abd-afd9-e05edc263c13">
- Only metaphor (dev/stage/prod namespaces)
> 
<img width="2672" alt="Screenshot 2023-09-13 at 1 05 11 PM" src="https://github.com/kubefirst/kubefirst/assets/3058939/713c17ad-9c29-4d71-8b61-a6a95427fbf7">

**Comment by alechp** [comment]
Updated build script to include two extra flags:
```
--gitops-template-url https://github.com/kubefirst/gitops-template
--gitops-template-branch main
```

Before metaphor even loads, I'm getting an error on `metaphor-development-[hash]-[hash]-set-environment-version-[hash]`
> <img width="949" alt="Screenshot 2023-09-18 at 6 57 47 PM" src="https://github.com/kubefirst/kubefirst/assets/3058939/e230ad8a-9fac-4ebd-aacb-c928926188dc">

Pertinent error from logs:
```
time="2023-09-19T01:19:50.226Z" level=warning msg="failed to patch task set, falling back to legacy/insecure pod patch, see https://argoproj.github.io/argo-workflows/workflow-rbac/" error="workflowtaskresults.argoproj.io is forbidden: User \"system:serviceaccount:argo:argo-server\" cannot create resource \"workflowtaskresults\" in API group \"argoproj.io\" in the namespace \"argo\""
```

This seems to be what kicks off the initial errors that we saw above; they still exist in current version. Namely:
```
metaphor-development-32f8779-65f8z-set-environment-version-3899486693: setting wrapper Chart.yaml to version: 0.0.1-rc.32f8779
metaphor-development-32f8779-65f8z-set-environment-version-3899486693: sed: can't read registry/development/components/development/metaphor/Chart.yaml: No such file or directory
```
> <img width="2672" alt="Screenshot 2023-09-18 at 7 05 59 PM" src="https://github.com/kubefirst/kubefirst/assets/3058939/afc56dd2-3bc5-4bbf-b784-ff007d76feb8">

---

Full logs for that failed pod:
```
time="2023-09-19T01:19:47.789Z" level=info msg="Starting Workflow Executor" version=v3.4.1
time="2023-09-19T01:19:47.796Z" level=info msg="Using executor retry strategy" Duration=1s Factor=1.6 Jitter=0.5 Steps=5
time="2023-09-19T01:19:47.796Z" level=info msg="Executor initialized" deadline="0001-01-01 00:00:00 +0000 UTC" includeScriptOutput=false namespace=argo podName=metaphor-development-32f8779-65f8z-set-environment-version-3899486693 template="{\"name\":\"set-environment-version\",\"inputs\":{\"parameters\":[{\"name\":\"chartVersion\",\"value\":\"0.0.1-rc.32f8779\"},{\"name\":\"environment\",\"value\":\"development\"},{\"name\":\"fullChartPath\",\"value\":\"registry/development/components/development/metaphor/Chart.yaml\"}],\"artifacts\":[{\"name\":\"repo-source\",\"path\":\"/src\",\"s3\":{\"key\":\"argo-workflows/artifacts/2023/09/19/073bca0e-d574-465a-995d-3e53cec87ebd/metaphor-development-32f8779-65f8z/metaphor-development-32f8779-65f8z-checkout-with-gitops-ssh-2115738426/repo-source.tgz\"}}]},\"outputs\":{\"artifacts\":[{\"name\":\"repo-source\",\"path\":\"/src\"}]},\"metadata\":{},\"script\":{\"name\":\"\",\"image\":\"kubefirst/chubbo:0.2\",\"command\":[\"bash\"],\"workingDir\":\"/src/gitops\",\"resources\":{},\"source\":\"set -e\\necho \\\"setting wrapper Chart.yaml to version: 0.0.1-rc.32f8779\\\"\\nsed -i \\\"s/  version:.*/  version: 0.0.1-rc.32f8779/g\\\" \\\"registry/development/components/development/metaphor/Chart.yaml\\\"\\necho \\\"updated development wrapper chart version to 0.0.1-rc.32f8779\\\"\\n\"},\"archiveLocation\":{\"archiveLogs\":false,\"s3\":{\"endpoint\":\"s3.amazonaws.com\",\"bucket\":\"k1-artifacts-capswancloud-lxwgx5\",\"region\":\"us-east-1\",\"insecure\":false,\"accessKeySecret\":{\"key\":\"accesskey\"},\"secretKeySecret\":{\"key\":\"secretkey\"},\"useSDKCreds\":true,\"encryptionOptions\":{},\"key\":\"argo-workflows/artifacts/2023/09/19/073bca0e-d574-465a-995d-3e53cec87ebd/metaphor-development-32f8779-65f8z/metaphor-development-32f8779-65f8z-set-environment-version-3899486693\"}}}" version="&Version{Version:v3.4.1,BuildDate:2022-10-01T15:03:42Z,GitCommit:0546fef0b096d84c9e3362d2b241614e743ebe97,GitTag:v3.4.1,GitTreeState:clean,GoVersion:go1.18.6,Compiler:gc,Platform:linux/amd64,}"
time="2023-09-19T01:19:47.796Z" level=info msg="Starting deadline monitor"
time="2023-09-19T01:19:49.796Z" level=info msg="Main container completed" error="<nil>"
time="2023-09-19T01:19:49.796Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2023-09-19T01:19:49.796Z" level=info msg="No output parameters"
time="2023-09-19T01:19:49.796Z" level=info msg="Saving output artifacts"
time="2023-09-19T01:19:49.797Z" level=info msg="Staging artifact: repo-source"
time="2023-09-19T01:19:49.797Z" level=info msg="Staging /src from mirrored volume mount /mainctrfs/src"
time="2023-09-19T01:19:49.797Z" level=info msg="Taring /mainctrfs/src"
time="2023-09-19T01:19:49.913Z" level=info msg="archived 293 files/dirs in /mainctrfs/src"
time="2023-09-19T01:19:49.914Z" level=info msg="Successfully staged /src from mirrored volume mount /mainctrfs/src"
time="2023-09-19T01:19:49.914Z" level=info msg="S3 Save path: /tmp/argo/outputs/artifacts/repo-source.tgz, key: argo-workflows/artifacts/2023/09/19/073bca0e-d574-465a-995d-3e53cec87ebd/metaphor-development-32f8779-65f8z/metaphor-development-32f8779-65f8z-set-environment-version-3899486693/repo-source.tgz"
time="2023-09-19T01:19:49.914Z" level=info msg="Creating minio client using AWS SDK credentials"
time="2023-09-19T01:19:50.037Z" level=info msg="Saving file to s3" bucket=k1-artifacts-capswancloud-lxwgx5 endpoint=s3.amazonaws.com key=argo-workflows/artifacts/2023/09/19/073bca0e-d574-465a-995d-3e53cec87ebd/metaphor-development-32f8779-65f8z/metaphor-development-32f8779-65f8z-set-environment-version-3899486693/repo-source.tgz path=/tmp/argo/outputs/artifacts/repo-source.tgz
time="2023-09-19T01:19:50.218Z" level=info msg="Save artifact" artifactName=repo-source duration=304.271429ms error="<nil>" key=argo-workflows/artifacts/2023/09/19/073bca0e-d574-465a-995d-3e53cec87ebd/metaphor-development-32f8779-65f8z/metaphor-development-32f8779-65f8z-set-environment-version-3899486693/repo-source.tgz
time="2023-09-19T01:19:50.218Z" level=info msg="not deleting local artifact" localArtPath=/tmp/argo/outputs/artifacts/repo-source.tgz
time="2023-09-19T01:19:50.218Z" level=info msg="Successfully saved file: /tmp/argo/outputs/artifacts/repo-source.tgz"
time="2023-09-19T01:19:50.226Z" level=info msg="Create workflowtaskresults 403"
time="2023-09-19T01:19:50.226Z" level=warning msg="failed to patch task set, falling back to legacy/insecure pod patch, see https://argoproj.github.io/argo-workflows/workflow-rbac/" error="workflowtaskresults.argoproj.io is forbidden: User \"system:serviceaccount:argo:argo-server\" cannot create resource \"workflowtaskresults\" in API group \"argoproj.io\" in the namespace \"argo\""
time="2023-09-19T01:19:50.252Z" level=info msg="Patch pods 200"
time="2023-09-19T01:19:50.256Z" level=info msg="stopping progress monitor (context done)" error="context canceled"
time="2023-09-19T01:19:50.256Z" level=info msg="Deadline monitor stopped"
time="2023-09-19T01:19:50.257Z" level=info msg="Alloc=8355 TotalAlloc=24180 Sys=22994 NumGC=6 Goroutines=9"
```

**Comment by fharper** [comment]
There's an active discussion about this on the Slack community at https://kubefirst.slack.com/archives/C03U34WJ7FW/p1694539096211389

**Comment by alechp** [comment]
Status update from slack: @Claywd and @johndietz working on this

<img width="739" alt="Screenshot 2023-09-20 at 12 18 24 PM" src="https://github.com/kubefirst/kubefirst/assets/3058939/bb167983-b277-4402-85b7-df4bf05d6039">

**Comment by alechp** [comment]
Status update; blocked pending v2.3.0:
<img width="957" alt="Screenshot 2023-10-02 at 11 29 57 AM" src="https://github.com/kubefirst/kubefirst/assets/3058939/4ea156bf-f7bb-4b08-a484-dfe03a33fb14">

Will test again after https://github.com/kubefirst/kubefirst/pull/1832 is merged

**Comment by alechp** [comment]
Confirmed Metaphor is working now (tested with kubefirst v2.3.5)

CC: @jarededwards  @fharper @cameronraysmith 

<img width="1392" alt="Screenshot 2023-11-03 at 9 42 28 PM" src="https://github.com/kubefirst/kubefirst/assets/3058939/4ef9026f-614e-42ab-ae68-1b0939b5f81c">
