### ISSUE TITLE
About 2.2.18 release

### ISSUE THREAD

**Issue by chenrui333** [kubefirst/kubefirst#1805]
👋 looks like the latest release build was not completed (ie [this action run](https://github.com/kubefirst/kubefirst/actions/runs/6125935781) did not get completed), raise this issue for some awareness. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/141817

**Comment by fharper** [comment]
We cancelled the release, sorry about that!

What is the best process in that case @chenrui333? Close the PR or let it open until we release?

**Comment by chenrui333** [comment]
yeah, that would be great. Thanks for that info! 👍

**Comment by fharper** [comment]
I assume you said yes to close the PR, which I'll do, thanks
