### ISSUE TITLE
Don't let users install applications from the GitOps catalog that won't work on k3d

### ISSUE THREAD

**Issue by fharper** [kubefirst/kubefirst#1810]
### What is your feature idea?

Some applications from the GitOps catalog can't be installed on k3d (ex.: DataDog), and now that the catalog is also available on k3d, we probably want to prevent the users from installing those locally.

### Why is it needed?

It will prevent installing applications that won't work, so the users won't try to fix something that shouldn't, and we won't get support request for those.

I suggest we add a new field in the [index.yaml](https://github.com/kubefirst/gitops-catalog/blob/main/index.yaml), like `k3d` (@donnalux can find a better name for it) which should be set to `false` if not working on k3d, and `true` if it is. We could also default to `true` if the new field is not set.

### Is this missing feature preventing you from using kubefirst?

- [ ] Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fharper** [comment]
@donnalux agreed with the idea.

On the console side, it would just mean to not load the application with that property.

**Comment by tomekz** [comment]
Hey I would like to work on this issue

**Comment by fharper** [comment]
That is awesome @tomekz. Let me message you on Slack so we can discuss this :)

**Comment by fharper** [comment]
As shared with you on the Slack community, we decided to go another way which is a bit more complicated, but will let us cover more case scenarios.
