### ISSUE TITLE
cli install end of run: needs to launch browser to console and should end the cli pid

### ISSUE THREAD

**Issue by johndietz** [kubefirst/kubefirst#1825]
### What is your feature idea?

rc18 ends the cli installation with this screen
<img width="1715" alt="CleanShot 2023-09-20 at 14 24 47@2x" src="https://github.com/kubefirst/kubefirst/assets/3649336/084ac9df-06bc-4ff2-85f4-10a63dd3eb0a">

- you shouldn't have to press ctrl + c to quit, it should just end
- it should launch your browser to console and doesn't

### Why is it needed?

parity with existing user experience

### Is this missing feature preventing you from using kubefirst?

- [ ] Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CristhianF7** [comment]
Fixed by https://github.com/kubefirst/kubefirst/pull/1832
