### ISSUE TITLE
oidc reverse proxy required for mgmt instance of console app

### ISSUE THREAD

**Issue by johndietz** [kubefirst/kubefirst#1830]
### What is your feature idea?

any signed in user can access, but we must require auth against vault.

### Why is it needed?

internet facing app capable of provisioning infrastructure and incurring cloud costs by bad actors

### Is this missing feature preventing you from using kubefirst?

- [X] Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CristhianF7** [comment]
This is fixed. We have implemented native authentication in front of Console https://github.com/kubefirst/console/pull/315
