### ISSUE TITLE
CLI does not check if Docker is installed anymore

### ISSUE THREAD

**Issue by fharper** [kubefirst/kubefirst#1831]
### Which version of kubefirst are you using?

v2.3 (f6a7fcc6ddff22198f7b253266097cef4bcd8819)

### Which cloud provider?

Civo

### Which installation type?

CLI

### Which distributed Git provider?

None specific

### What is the issue?

If Docker isn't running, the new CLI will fail

<img width="965" alt="CleanShot 2023-09-25 at 14 47 17@2x" src="https://github.com/kubefirst/kubefirst/assets/1170989/de5f74c6-6d57-45c8-b100-ae60ea11a73f">

The error isn't related, but I can reproduce with having Docker close, and it worked when I started it. Since the new CLI always create a k3d cluster to use the API, we need to have the same pre-flight check than with the previous CLI version

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CristhianF7** [comment]
Fixed by https://github.com/kubefirst/kubefirst/pull/1832
