### ISSUE TITLE
README Docs Links Broken on Windows

### ISSUE THREAD

**Issue by Taiwrash** [kubefirst/kubefirst#1847]
### Which version of kubefirst are you using?

v2.2.17

### Which cloud provider?

AWS, Google Cloud, k3d (local)

### Which DNS?

None specific

### Which installation type?

None specific

### Which distributed Git provider?

GitHub

### What is the issue?

Using the link the in the README to navigate to the docs page broken using my windows device but work well on mac.

See the error screenshot below.
![Screenshot (3)](https://github.com/kubefirst/kubefirst/assets/49725691/6bc8de8e-3b21-4147-b8b6-5aa089b17324)
![Screenshot (4)](https://github.com/kubefirst/kubefirst/assets/49725691/86b2fbc8-7c2f-4e87-9e3d-9c77439bf2a2)
![Screenshot (5)](https://github.com/kubefirst/kubefirst/assets/49725691/bd9c6c8b-1b52-4f44-a9da-9099c5502b1f)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fharper** [comment]
I cannot replicate this issue on Windows with Microsoft Edge. In any cases, you're right, this shouldn't point to the `index.html` file anyway.
