### ISSUE TITLE
Update: Designing of the Footer Section

### ISSUE THREAD

**Issue by DeepRahangdale** [kubefirst/kubefirst#1861]
### What is your feature idea?

Would add all the buttons and links available in the Header Section to the Footer Section!!

### Why is it needed?

To Improve the interface of the site and the user experience.

### Is this missing feature preventing you from using kubefirst?

- [X] Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fharper** [comment]
Thanks for the suggestion @DeepRahangdale, but we won't move forward with that :)
