### ISSUE TITLE
failed to build since 2.3.0 release

### ISSUE THREAD

**Issue by chenrui333** [kubefirst/kubefirst#1869]
It looks like the build is broken since this CLI refactoring PR, https://github.com/kubefirst/kubefirst/pull/1832, ie the ldflags does not work anymore to override the version flag

https://github.com/Homebrew/homebrew-core/pull/152245

**Comment by k8swrangler** [comment]
<img width="677" alt="Screenshot 2023-10-30 at 8 42 35 PM" src="https://github.com/kubefirst/kubefirst/assets/6446939/dfb1bc6c-1f6c-4de0-9e2a-eb86aaba8b8e">

Issue appears to be resolved. Flags pulled directly from the formula. Can we please try running again?

**Comment by k8swrangler** [comment]
@chenrui333 Can we get that pr opened back up and the test bot trying our build again?

**Comment by chenrui333** [comment]
closing via https://github.com/Homebrew/homebrew-core/pull/153052 Thanks @k8swrangler!
