### ISSUE TITLE
GitOps catalog available for workload clusters

### ISSUE THREAD

**Issue by fharper** [kubefirst/kubefirst#1878]
### What is your feature idea?

GitOps catalog should also be available for workload cluster. It was planned that it wouldn't be the case for 2.3.0, still creating the issue for tracking purposes.

### Why is it needed?

Doing so will let users install the catalog applications in workload clusters also.

### Is this missing feature preventing you from using kubefirst?

- [ ] Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by johndietz** [comment]
the ability to target a workload cluster (physical or virtual) should be available only to pro tier users, including pro tier users with no physical clusters (0-cost pro users).

**Comment by donnalux** [comment]
**UX Design:**

https://www.figma.com/file/we6QSscpQH6MkXilCBO9aT/Kubefirst-Console?type=design&node-id=6404-105025&mode=design&t=s9z8gcSWItHg6xof-4

**Comment by johndietz** [comment]
this was implemented with 2.4
