### ISSUE TITLE
Open kubefirst console button only works if you click the text

### ISSUE THREAD

**Issue by fharper** [kubefirst/kubefirst#1900]
### Which version of kubefirst are you using?

2.3

### Which cloud provider?

Civo

### Which DNS?

None specific

### Which installation type?

UI (Console app)

### Which distributed Git provider?

None specific

### Which Operating System?

None specific

### What is the issue?

The "Open kubefirst console" button only works if you click the text on the button, the other part of the button don't works.

https://github.com/kubefirst/kubefirst/assets/1170989/041263c4-85a0-4daf-a11c-4d0ad1678a34

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by D-B-Hawk** [comment]
[PR for fix](https://github.com/kubefirst/console/pull/365)
