### ISSUE TITLE
Civo Marketplace Installer: Setup cluster nodes according to provided gitops-template

### ISSUE THREAD

**Issue by marc0olo** [kubefirst/kubefirst#1905]
### What is your feature idea?

Currently the user has to provide the instance count and their size via UI, even if the user provides a custom gitops-template in "Advanced Mode", see:
![image](https://github.com/kubefirst/kubefirst/assets/8124114/48af988d-d7db-41e9-ba79-9e3416eef9f1)

I would like kubefirst to pick up the terraform configuration in the gitops-template instead.

### Why is it needed?

This is especially needed if I want to set up different instance sizes and counts on each instance size.

### Is this missing feature preventing you from using kubefirst?

- [ ] Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marc0olo** [comment]
I actually need to double check this on next provisioning. it might have been correct already (just displayed kind of missleading in the Civo UI).

I changed the setup now after privisioning and the Civo Dashboard shows me following outputs:

## Kubernetes Dashboard
![image](https://github.com/kubefirst/kubefirst/assets/8124114/5140428d-9713-4de1-b8ea-6e376480e876)

## Cluster Details
![image](https://github.com/kubefirst/kubefirst/assets/8124114/3f0880d7-8986-4af1-a591-10b64ec17671)

**Comment by marc0olo** [comment]
closing this issue as the installer uses the config defined in my gitops template.

anyway, for users of the installer it would be grad to display the information in the UI correctly and remove the inputs that are overruled by the provided template :-)

**Comment by fharper** [comment]
Glad you fixed the issue @marc0olo!

You're right, the interface should display was is provided in the gitops-template. I'll give it a try later to see if I can reproduce.

**Comment by fharper** [comment]
@marc0olo do you want to create the issue about the UI not reflecting the `gitops-template` resources if modified? What the UI is showing is hardoced to the default values, and as I wrote, it should reflect that template content. If not, no worries, I can create it, just wanted to give you the opportunity to do so if you prefer and want.

Just let me know :)
