### ISSUE TITLE
kubefirst cli does not return on my mac

### ISSUE THREAD

**Issue by frank-bee** [kubefirst/kubefirst#1911]
### Which version of kubefirst are you using?

v2.3.5

### Which cloud provider?

AWS

### Which DNS?

Cloud ones (default)

### Which installation type?

CLI

### Which distributed Git provider?

GitHub

### Which Operating System?

macOS

### What is the issue?

If I run any command with kubefirst , e.g. `kubefirst --help`, the command call seems to not return / finish. Basically the cursor does not appear again even after the command has finished. 
I have to us <ctrl> +c to return.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fharper** [comment]
Thanks for reporting, and so sorry about that @frank-bee. It has been fixed, but not released yet https://github.com/kubefirst/kubefirst/issues/1883 . We will release soon. For now, you can CTRL+C as you did, and it will have no effect on the command, just terminated it as it should.

**Comment by fharper** [comment]
If you ping me on our [Slack community](http://kubefirst.io/swag) (I'm Fred), or send me an email at fred@kubefirst.io, I would like to send you some swag as a small gesture to thank you for reporting this problem, and to apologize for the issue!

**Comment by frank-bee** [comment]
that was a quick reply... thanks @fharper 
To slack com. I anyway wanted to connect ... one sec
