### ISSUE TITLE
AwaitHostNTimes needs to use https client

### ISSUE THREAD

**Issue by converge** [kubefirst/kubefirst#193]
AwaitHostNTimes `(internal/gitlab)` uses `http.Get()` that accepts HTTP or HTTPS when requesting HTTP. We should only accept valid HTTPS responses adding `Go http default client: http.DefaultClient` like we do on `getArgoCDToken` function.

**Comment by 6za** [comment]
As acceptance criteria for this: `to ensure we only set as valid HTTPS on the final step of install, once we have the real certificate not the self-signed one.`

So, it should only pass the test, and return true, if the certificate match on HTTPS calls. 

Used on the last check of installer and other places.

**Comment by 6za** [comment]
For clarification: 

This code is used here: https://github.com/kubefirst/kubefirst/blob/main/cmd/createGitlab.go#L312

```golang
		// Wait argocd cert to work, or force restart
		if !globalFlags.DryRun {
			argocdPodClient := clientset.CoreV1().Pods("argocd")
			for i := 1; i < 15; i++ {
				argoCDHostReady := gitlab.AwaitHostNTimes("argocd", globalFlags.DryRun, 20)
				if argoCDHostReady {
					informUser("ArgoCD DNS is ready", globalFlags.SilentMode)
					break
				} else {
					k8s.DeletePodByLabel(argocdPodClient, "app.kubernetes.io/name=argocd-server")
				}
			}
		}
```

This loop is meant to solve a known issue that sometimes takes some reboots to load the right certificate. 

It `AwaitHostNTimes` should only be a success(return true) if it has the `letsencrypt` certificate or any other trusted certificate.  If it has a self-signed one the broken lock, it should return false. So, the loop work as desired. 

Example: 
![image](https://user-images.githubusercontent.com/53096417/188448382-a97598d0-c859-498b-a9c8-30cc03cecbae.png)


I believe to achieve that we discussed before to create a custom http client in go to proper control its flags, as it seems it is setting globally to accept insecureCerts..

**Comment by converge** [comment]
most recent PR commit was this one https://github.com/kubefirst/kubefirst/pull/357/commits/95107efe8c93019a600f5f63b8be2257e4df9b2a

was it tested with that?

**Comment by 6za** [comment]
Installer seems to works as expected, this may not be needed anymore.
