### ISSUE TITLE
Cluster details page not opening when clicking on table row

### ISSUE THREAD

**Issue by donnalux** [kubefirst/kubefirst#1959]
### Which version of kubefirst are you using?

Not known

### Which cloud provider?

None specific

### Which DNS?

None specific

### Which installation type?

None specific

### Which distributed Git provider?

None specific

### Did you use a fork of `gitops-template`?

No

### Which Operating System?

None specific

### What is the issue?

On the Cluster mgmt page - List view tab, when user clicks on a table row the Cluster details panel does not open. 
It should have same behaviour as graph view.

**UX Design**:

https://www.figma.com/file/we6QSscpQH6MkXilCBO9aT/Kubefirst-Console?type=design&node-id=4574-69304&mode=design&t=ut6uaXtawix3jTtr-4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by D-B-Hawk** [comment]
Rectified in this PR:
https://github.com/kubefirst/console/commit/c304827c5f9fad970f4842773db77d003b731317
