### ISSUE TITLE
404 Page spacing is incorrect

### ISSUE THREAD

**Issue by donnalux** [kubefirst/kubefirst#1960]
### Which version of kubefirst are you using?

2.4.0-RC1

### Which cloud provider?

DigitalOcean

### Which DNS?

None specific

### Which installation type?

None specific

### Which distributed Git provider?

GitHub

### Did you use a fork of `gitops-template`?

No

### Which Operating System?

Windows

### What is the issue?

The 404 page does not have correct spacing.
![image](https://github.com/kubefirst/kubefirst/assets/102221761/a141075f-ddb7-4cdf-ba02-fa19496ddf76)

**Design:**
https://www.figma.com/file/we6QSscpQH6MkXilCBO9aT/Kubefirst-Console?type=design&node-id=4475-47421&mode=design&t=ut6uaXtawix3jTtr-4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by D-B-Hawk** [comment]
[PR for fix](https://github.com/kubefirst/console/pull/444)
