### ISSUE TITLE
Visual issues on Cluster details panel

### ISSUE THREAD

**Issue by donnalux** [kubefirst/kubefirst#1961]
### Which version of kubefirst are you using?

2.4.0-RC1

### Which cloud provider?

DigitalOcean

### Which DNS?

None specific

### Which installation type?

None specific

### Which distributed Git provider?

GitHub

### Did you use a fork of `gitops-template`?

No

### Which Operating System?

None specific

### What is the issue?

Visual issues present on the Cluster details panel:

- Cluster name is repeated
<img width="549" alt="image" src="https://github.com/kubefirst/kubefirst/assets/102221761/fa4c9536-706f-4b55-90d4-e897390c0bad">

- Links should display an underline on mouse hover (like on services page)
<img width="309" alt="image" src="https://github.com/kubefirst/kubefirst/assets/102221761/8d7a6013-f983-49ce-9412-4cea509f1ebd">

- Label should read "Git provider"
<img width="277" alt="image" src="https://github.com/kubefirst/kubefirst/assets/102221761/35b2ee4b-90c8-492b-aa5c-198797137c3f">

- Close button text not legible on hover
<img width="236" alt="image" src="https://github.com/kubefirst/kubefirst/assets/102221761/4448f810-37d3-457d-9371-e854e9b11285">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by D-B-Hawk** [comment]
Dealt with in this PR: https://github.com/kubefirst/console/pull/422

**Comment by donnalux** [comment]
@D-B-Hawk I see issues with secondary button on hover

<img width="225" alt="image" src="https://github.com/kubefirst/kubefirst/assets/102221761/da7e8ce0-148b-4aa3-8f22-9cb18246c996">

Design component:
https://www.figma.com/file/we6QSscpQH6MkXilCBO9aT/Kubefirst-Console?type=design&node-id=281-6121&mode=design&t=Xrmfh9KkfxYdeaB4-4
