### ISSUE TITLE
Required error messaging on subsequent field being displayed 

### ISSUE THREAD

**Issue by donnalux** [kubefirst/kubefirst#1962]
### Which version of kubefirst are you using?

2.4.0-RC1

### Which cloud provider?

DigitalOcean

### Which DNS?

None specific

### Which installation type?

None specific

### Which distributed Git provider?

GitHub

### Did you use a fork of `gitops-template`?

No

### Which Operating System?

None specific

### What is the issue?

On the cluster details panel, when user creates a new environment and the dropdown closes the cluster name field is in error state.

<img width="506" alt="image" src="https://github.com/kubefirst/kubefirst/assets/102221761/967816f9-596a-4554-af6d-db093743c15f">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by D-B-Hawk** [comment]
deal with in this PR: https://github.com/kubefirst/console/pull/424
