### ISSUE TITLE
Cannot use subdomains with the CLI

### ISSUE THREAD

**Issue by fharper** [kubefirst/kubefirst#1973]
### What is your feature idea?

There is a no flag to use subdomains when creating a cluster directly from the CLI, like one can do using the UI installer

### Why is it needed?

Need it for people to use subdomains with the CLI, but also for features parity between the CLI and UI.

### Is this missing feature preventing you from using kubefirst?

- [ ] Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CristhianF7** [comment]
Fixed in https://github.com/kubefirst/kubefirst/pull/1976
