### ISSUE TITLE
Learn more text appearing under log window during launch

### ISSUE THREAD

**Issue by donnalux** [kubefirst/kubefirst#1974]
### Which version of kubefirst are you using?

Not known

### Which cloud provider?

None specific

### Which DNS?

None specific

### Which installation type?

UI (Console app)

### Which distributed Git provider?

None specific

### Did you use a fork of `gitops-template`?

No

### Which Operating System?

None specific

### What is the issue?

Learn more about text appearing under log window. Shouldn't be there.
 
![image](https://github.com/kubefirst/kubefirst/assets/102221761/66607943-aa0d-4e40-bac4-bebba3af86e6)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by donnalux** [comment]
Reported by @jarededwards

**Comment by D-B-Hawk** [comment]
dealt with in this PR: https://github.com/kubefirst/console/pull/428
