### ISSUE TITLE
concise view doesn't continue to correctly report status after a retry event

### ISSUE THREAD

**Issue by johndietz** [kubefirst/kubefirst#1975]
### Which version of kubefirst are you using?

v2.3.7

### Which cloud provider?

DigitalOcean

### Which DNS?

Cloud ones (default)

### Which installation type?

UI (Console app)

### Which distributed Git provider?

GitHub

### Did you use a fork of `gitops-template`?

No

### Which Operating System?

macOS

### What is the issue?

i ran a mgmt provision that failed because of cloud quota, couldn’t create bucket in digitalocean because we ran out of space. the ui nicely offered me a retry, and the retry worked and provisioned the cluster. the problem is that the concise view never started back up. the detailed view continued, all the way to cluster complete, but the user was never offered the information that we were done in the concise view, and never was given the kbot password as a result.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by D-B-Hawk** [comment]
based off discussion with team we have rectified the issue as of now. Will revisit this issue if it pops up again
