### ISSUE TITLE
Cannot click next when coming back to previous step

### ISSUE THREAD

**Issue by fharper** [kubefirst/kubefirst#1983]
### Which version of kubefirst are you using?

2.3.7

### Which cloud provider?

None specific

### Which DNS?

None specific

### Which installation type?

Marketplace, UI (Console app)

### Which distributed Git provider?

None specific

### Did you use a fork of `gitops-template`?

No

### Which Operating System?

None specific

### What is the issue?

I don't know if it's like that on all steps, but when I filled step 2, go to 3, but go back to 2 for whatever reason, even if everything was filled correctly, and still is, I cannot click next to go move forward, I have to retype something in textboxes or like I did in this recording, select the GH org again so it become available. It should be available since all information is correct.

https://github.com/kubefirst/kubefirst/assets/1170989/2c47695c-7c78-474e-869a-978afb4180e9

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by D-B-Hawk** [comment]
confirmed in this PR that field validation on navigation back and forth is working as expected. [PR](https://github.com/kubefirst/console/pull/443)
