### ISSUE TITLE
Add dismissible tags to environment select dropdown

### ISSUE THREAD

**Issue by jarededwards** [kubefirst/kubefirst#1998]
**UX Design:**

Dismissible tag is a new component.

https://www.figma.com/file/we6QSscpQH6MkXilCBO9aT/Kubefirst-Console?type=design&node-id=3425-44299&mode=design&t=5G6uq0Y1SLY55ZN7-4

**Comment by D-B-Hawk** [comment]
[PR for new component](https://github.com/kubefirst/console/pull/436)
