### ISSUE TITLE
CLI verbose logs should also display cluster 1 interesting pods logs

### ISSUE THREAD

**Issue by fharper** [kubefirst/kubefirst#2032]
### What is your feature idea?

Since the CLI revamp in 2.3, the CLI verbose logs file contain only the logs from cluster 0 creation (except for k3d, which doesn't have cluster 0, and create the local experience right away), not the cluster the user wants to create on the public cloud. Users not need to check on cluster 1 (the public cloud cluster) pods logs to get more information about the process, or failures. kubefirst should get those logs themselves and transmit them in the verbose logs file for the CLI experience.	

### Why is it needed?

We will document this new process, but we can already see that it's confusing for folks, and it's adding initial steps one may not want to take at first just to create the cluster. Many folks also don't read the docs :)

This is also valid for the UI verbose logs tab.

### Is this missing feature preventing you from using kubefirst?

- [ ] Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CristhianF7** [comment]
Approach was changed and we are going to write the API logs in the same CLI log file.
