### ISSUE TITLE
console gitlab links when gitlab org already in use incorrectly point to github urls

### ISSUE THREAD

**Issue by johndietz** [kubefirst/kubefirst#2039]
### Which version of kubefirst are you using?

v2.3.7

### Which cloud provider?

Civo

### Which DNS?

Cloud ones (default)

### Which installation type?

UI (Console app)

### Which distributed Git provider?

GitLab

### Did you use a fork of `gitops-template`?

No

### Which Operating System?

macOS

### What is the issue?

console correctly identifies that gitlab org is in use, but the links point at github instead of gitlab.

![CleanShot 2024-01-16 at 09 25 01](https://github.com/kubefirst/kubefirst/assets/3649336/5bfd0bf9-5e2c-47ba-9e0c-ccc36e37b1ce)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by D-B-Hawk** [comment]
[PR for fix](https://github.com/kubefirst/console/pull/445)
