### ISSUE TITLE
Ngrok requires an authentication token, which brakes Kubefirst deployed via K3d.

### ISSUE THREAD

**Issue by agalue** [kubefirst/kubefirst#2058]
### Which version of kubefirst are you using?

2.3.7

### Which cloud provider?

k3d (local)

### Which DNS?

None specific

### Which installation type?

CLI

### Which distributed Git provider?

GitLab

### Did you use a fork of `gitops-template`?

No

### Which Operating System?

macOS

### What is the issue?

You cannot deploy `ngrok` without passing an authentication token. Because of this, deploying Kubefirst with K3d won't work, as that breaks Atlantis and the Argo Workflows on Metaphor.

### How do we reproduce it?

You can reproduce the problem easily by following the documentation with plain Docker:

https://ngrok.com/docs/using-ngrok-with/docker/

If you don’t pass the token, `ngrok` won’t start.

In Kubefirst, the `ngrok` manifests are taken from the following repository:

https://github.com/kubefirst/manifests

If you look at the following deployment YAML file, you’ll see that the token is not passed; therefore, `ngrok` won’t start:

https://github.com/kubefirst/manifests/blob/main/atlantis/ngrok/deployment.yaml

You can reproduce that without Kubefirst on a simple K8s cluster.

### Workaround

Deploy Kubefirst:
```
kubefirst k3d create --git-provider gitlab --gitlab-group agalue --cluster-name demo
```
> *NOTE*: I’m using Gitlab, although that also applies to GitHub. Note that the name I choose for the cluster is “demo”.

We should copy those templates into the `gitops` repository and then update `registry/demo/components/atlantis/ngrok.yaml` to use it:
```bash
cd /tmp/
git clone git@github.com:kubefirst/manifests.git
git clone git@gitlab.com:agalue/gitops.git
rsync -avr manifests/atlantis/ngrok/ gitops/registry/demo/components/atlantis/ngrok/
cd gitops/registry/demo/components/atlantis
```
Then, edit `ngrok.yaml` and do the following:

* Update the `repoURL` to point to your GIT provider (Gitlab in my case): `git@gitlab.com:agalue/gitops.git`
* Update the `path` based on what we did via `rsync` from above (i.e., `registry/demo/components/atlantis/ngrok`; note the name of the cluster, `demo` in my case).

Then, log into Vault, open `secret/atlantis-ngrok,` add a new version, and then add your `ngrok` authentication token as `NGROK_AUTHTOKEN`. The secret called `k3d-ngrok` inside the `atlantis` namespace will be updated as soon as you do that.

Update the `ngrok` deployment mentioned at the beginning to pass the token from the `k3d-ngrok` secret:
```yaml
          env:
          - name: NGROK_AUTHTOKEN
            valueFrom:
              secretKeyRef:
                name: k3d-ngrok
                key: NGROK_AUTHTOKEN
```
Commit all the changes on your `gitops` repository. You can wait for Argo or find `atlantis-components` and force a refresh. You might need to delete the job `ngrok-startup` to make it work. After that, `atlantis-components` should go green.

Then, you should see Argo Workflow progressing if you check the Pipelines on Gitlab (or the Actions in GitHub) for `metaphor`. If ArgoCD doesn’t auto-resolve, once the Pipeline/Action is done, refresh the Metaphor application on each environment.

### Suggested Solution

For Kubefirst, the same way it checks for the presence of `GITHUB_TOKEN` or `GITLAB_TOKEN` when using K3d, we should also check for `NGROK_AUTHTOKEN` (or perhaps `NGROK_TOKEN` to have name consistency); something the user should provide. With that in mind, we could update the code to ensure the token is injected correctly into the secret in Vault and move the `ngrok` manifests to the `k3d` template.

There is nothing wrong with keeping https://github.com/kubefirst/manifests/tree/main/atlantis/ngrok “as-is,” but we should ensure we’re injecting the token via env-var to make it work (as mentioned above). Then, we could do the magic on the Kubefirst CLI tool without altering the templates for K3d.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fharper** [comment]
Thanks for reporting this issue @agalue . It was working before, so we need to investigate. Maybe ngrok changed how their free tier is working token-wise.

**Comment by agalue** [comment]
Indeed, it worked before; I have used it several times. Now that Ngrok has changed its usage rules or terms of the agreement (which I believe happened), an authentication token is mandatory. Once again, there is nothing wrong with Kubefirst, but as it uses it for K3d, we need to ensure Ngrok has what it needs.

**Comment by johndietz** [comment]
@agalue thanks so much for the thorough assessment and detail on this issue. anyone reading along who needs a workaround, the one in this description works quite well as described.

i got this issue's fix merged yesterday so it'll go out in the next kubefirst release. the approach that we took was to expect our users to export an `NGROK_AUTHTOKEN` environment variable in their shell before running `kubefirst k3d create`. if they do, we'll include atlantis, and wire the authtoken into the vault secret as describe above. if the env var isn't exported, we'll remove atlantis from the registry of apps, and the k3d platform will simply not have that layer of IAC automation. we didn't want to force our users to create an ngrok account as a prerequesite step so we're basically making atlantis optional driven by env var presenence.

**Comment by chris-braidwell** [comment]
Another workaround:
- Get auth and API tokens from ngrok
- Open Vault: https://vault.kubefirst.dev/
- Visit the `atlantis-ngrok` secret page
- Add `NGROK_API_KEY` and `NGROK_AUTHTOKEN`
- Delete the atlantis/ngrok container to restart it

If the right solution is we need to export ngrok env vars before the create, that isn't in the docs now as far as I can tell.

**Comment by fharper** [comment]
This has been release in v.2.3.9: more info on the new token at https://docs.kubefirst.io/k3d/quick-start/install#local-atlantis-executions-optional
