### ISSUE TITLE
GitOps Catalog installed application with Ingress Controllers should display access URL

### ISSUE THREAD

**Issue by fharper** [kubefirst/kubefirst#2078]
### What is your feature idea?

GitOps Catalog installed application with Ingress Controllers should display access URL like we do for kubefirst installed application.

### Why is it needed?

This would be super useful, so the users wouldn't have to check the YAML file in their `gitops` repository to find this information. It will also harmonize the UI as we do it for kubefirst installed applications.

### Is this missing feature preventing you from using kubefirst?

- [ ] Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by donnalux** [comment]
This is already in the designs.
