### ISSUE TITLE
Fix repos: URL

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#210]
![image](https://user-images.githubusercontent.com/53096417/183909499-5a38ff6c-f1ad-4c2d-a358-22b7bf4752f7.png)
![image](https://user-images.githubusercontent.com/53096417/183909592-0e08d5f1-0ea6-4678-8ce6-0c7cba86b219.png)

**Comment by pagottoo** [comment]
will be merged on pr #204
