### ISSUE TITLE
`--ci` mode in CLI does not exit

### ISSUE THREAD

**Issue by abangser** [kubefirst/kubefirst#2112]
### Which version of kubefirst are you using?

v2.3.8

### Which cloud provider?

k3d (local)

### Which DNS?

None specific

### Which installation type?

CLI

### Which distributed Git provider?

GitHub

### Did you use a fork of `gitops-template`?

No

### Which Operating System?

macOS

### What is the issue?

When I use the `--ci` flag to stop the handover screen from coming up the command still hangs. This leads to more confusion as I am not sure if I can `ctrl+c` exit it or not until I look in the logs and see the last success message.

I believe this is an issue because of [this](https://github.com/kubefirst/kubefirst/blob/main/cmd/k3d/create.go#L1404-L1406) if statement:
```
if !ciFlag {
  reports.LocalHandoffScreenV2(viper.GetString("components.argocd.password"), clusterNameFlag, gitDestDescriptor, cGitOwner, config, false)
}
```

I believe you replace the if statement with just a call to that method but with the last parameter being `ciFlag` then the method in your API will manage this successfully with [this](https://github.com/kubefirst/kubefirst-api/blob/main/pkg/reports/local.go#L25-L28) if statement:
```
if silentMode {
  log.Printf("[#99] Silent mode enabled, LocalHandoffScreen skipped, please check ~/.kubefirst file for your cluster and service credentials.")
  return
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fharper** [comment]
Sorry about that, and thanks for reporting Abby. @CristhianF7 will give it a closer look.
