### ISSUE TITLE
Adding a new App through github produces no deployment

### ISSUE THREAD

**Issue by simontechdev** [kubefirst/kubefirst#2154]
### Which version of kubefirst are you using?

v2.4.3

### Which cloud provider?

DigitalOcean

### Which DNS?

Cloudflare

### Which installation type?

UI (Console app)

### Which distributed Git provider?

GitHub

### Did you use a fork of `gitops-template`?

No

### Which Operating System?

Linux

### What is the issue?

Adding a new app through GitOps, does not deploy an app from my helm chart.
No errors, everything appears healthy and the workflow works, with a perfectly working image — but nothing deploys, no service, no ingress and no DNS setting.
The original Metaphor works fine, and updates when pull requests are merged...
But adding a new application, produces no deployment and no errors.

![image](https://github.com/kubefirst/kubefirst/assets/2991240/521fa776-a58a-47f0-ac10-02cedfe7af13)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by simontechdev** [comment]
It looks a lot like this issue here
https://github.com/argoproj/argo-cd/issues/11638

**Comment by simontechdev** [comment]
It appears to be an app of apps issue with ArgoCD namespaces

**Comment by fharper** [comment]
Following-up with you on Slack. I will report the conclusion of our discussion in this issue for transparency and making the information available for all.

**Comment by fharper** [comment]
We concluded that it was not a platform issue.
