### ISSUE TITLE
Problem installing kubefirst using brew on WSL-2 Debian 12

### ISSUE THREAD

**Issue by mwoodpatrick** [kubefirst/kubefirst#2182]
### Which version of kubefirst are you using?

kubefirst-cli golang utility version: v2.4.8

### Which cloud provider?

k3d (local)

### Which DNS?

None specific

### Which installation type?

CLI

### Which distributed Git provider?

GitHub

### Did you use a fork of `gitops-template`?

No

### Which Operating System?

Linux

### What is the issue?

I have kubefirst installed using apt.

When I tried installing kubefirst using brew I got:

```
brew install kubefirst/tools/kubefirst
==> Auto-updating Homebrew...
Adjust how often this is run with HOMEBREW_AUTO_UPDATE_SECS or disable with
HOMEBREW_NO_AUTO_UPDATE. Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
==> Fetching dependencies for kubefirst/tools/kubefirst: aws-iam-authenticator
==> Fetching aws-iam-authenticator
==> Downloading https://ghcr.io/v2/homebrew/core/aws-iam-authenticator/manifests/0.6.14
Already downloaded: /home/mwoodpatrick/.cache/Homebrew/downloads/db4228885dabd2c81788408899392950847aa306e5dd7e49ef63346b4c2dad83--aws-iam-authenticator-0.6.14.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/aws-iam-authenticator/blobs/sha256:449f840bb69f28c2e1775ed90cea32aaf1c3
Already downloaded: /home/mwoodpatrick/.cache/Homebrew/downloads/f81485f11ff26505e7c7312e0d5d200ae21a6cd5d97fe3b514d10e8145036e0c--aws-iam-authenticator--0.6.14.x86_64_linux.bottle.tar.gz
==> Fetching kubefirst/tools/kubefirst
==> Downloading https://github.com/kubefirst/kubefirst/releases/download/v2.4.8/kubefirst_2.4.8_linux_amd64.tar.gz
Already downloaded: /home/mwoodpatrick/.cache/Homebrew/downloads/4acc16f1ceb5aa009e88c8106f55845e7ea726e6236d7922c71b095bf1403955--kubefirst_2.4.8_linux_amd64.tar.gz
==> Installing kubefirst from kubefirst/tools
Error: The following formula cannot be installed from bottle and must be
built from source.
  kubefirst
Install Clang or run `brew install gcc`.
```

I already have gcc installed:

```
brew install gcc
==> Auto-updating Homebrew...
Adjust how often this is run with HOMEBREW_AUTO_UPDATE_SECS or disable with
HOMEBREW_NO_AUTO_UPDATE. Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
Warning: gcc 14.1.0 is already installed and up-to-date.
To reinstall 14.1.0, run:
  brew reinstall gcc
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by codespearhead** [comment]
Try this: https://github.com/orgs/Homebrew/discussions/3030

**Comment by fharper** [comment]
I just installed Debian 12 on my Windows machine with WSL2, and I had no issue installing kubefirst. Homebrew suggested I install gcc in the end, but it didn't prevent me from installing kubefirst without gcc installed yet. With that said, it's a new installation, so I had nothing else that could cause Homebrew to have trouble.

It seems to be a Homebrew issue as @codespearhead mentioned. Did you have all the requirements mentioned at https://docs.brew.sh/Homebrew-on-Linux#requirements .

Also, based on this [issue](https://github.com/kubefirst/kubefirst/issues/2173) that was created by you before this one, it seems like you were using the kubefirst CLI on a Debian installation with WSL2, no? What happened between then and now?

**Comment by mwoodpatrick** [comment]
On updating my dependencies I was to install kubefirst on WSL-2 Debian GNU/Linux 12 (bookworm)
