### ISSUE TITLE
Add gitops & metaphor repository names as flags for create

### ISSUE THREAD

**Issue by alechp** [kubefirst/kubefirst#2193]
### What is your feature idea?

Problem:
> Gitops & metaphor repository names are hard-coded

Screenshot:
<img width="1365" alt="Screenshot 2024-06-09 at 3 39 23 PM" src="https://github.com/kubefirst/kubefirst/assets/3058939/8580a3a3-7793-4232-b571-381d8e66577d">

Solution:
- Add `--gitopsRepoName` flag
- Add `--metaphorRepoName` flag
- Keep "gitops" & "metaphor" as sane defaults 

Impacted files:
> There might be more, just what I found off initial search
- https://github.com/kubefirst/kubefirst/blob/a47ff7fa7d222555c9cd31ef066b4910368cc796/cmd/google/create.go#L66
- https://github.com/kubefirst/kubefirst/blob/a47ff7fa7d222555c9cd31ef066b4910368cc796/cmd/digitalocean/create.go#L67
- https://github.com/kubefirst/kubefirst/blob/a47ff7fa7d222555c9cd31ef066b4910368cc796/cmd/civo/create.go#L61
- https://github.com/kubefirst/kubefirst/blob/a47ff7fa7d222555c9cd31ef066b4910368cc796/cmd/k3s/create.go#L67
- https://github.com/kubefirst/kubefirst/blob/a47ff7fa7d222555c9cd31ef066b4910368cc796/cmd/akamai/create.go#L61
- https://github.com/kubefirst/kubefirst/blob/a47ff7fa7d222555c9cd31ef066b4910368cc796/cmd/vultr/create.go#L68
- https://github.com/kubefirst/kubefirst/blob/a47ff7fa7d222555c9cd31ef066b4910368cc796/cmd/aws/create.go#L90

### Why is it needed?

Why:
- maintaining multiple gitops repos for different clouds/regions
- maintaining associated metaphor repos for different clouds/regions
- mitigating risk of deletion when working with deletes (eg. spinning up a gitops directory on my local github to test something and then stressing that cleanup commands could nuke something on organization's github if I'm not careful)

### Is this missing feature preventing you from using kubefirst?

- [ ] Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alechp** [comment]
Started fork: https://github.com/alechp/kubefirst/tree/feat/repository-name-flags-for-digitalocean

---

Still failing here:
<img width="2628" alt="Screenshot 2024-06-09 at 5 42 50 PM" src="https://github.com/kubefirst/kubefirst/assets/3058939/692f271e-8b61-4f85-bbdb-35df0fa54933">

Happy to keep exploring. Pointers to save time would be nice

Inside `gitShim/init.go` I see `Repositories[]` being referenced & looped through to check whether the repositories exist:
<img width="1651" alt="Screenshot 2024-06-09 at 5 45 59 PM" src="https://github.com/kubefirst/kubefirst/assets/3058939/e9d1435e-6990-436a-8063-f935d93d915c">

Updated the newRepositories here:
<img width="1678" alt="Screenshot 2024-06-09 at 5 47 08 PM" src="https://github.com/kubefirst/kubefirst/assets/3058939/2ea55e10-7a85-4c6c-8f74-86b2b82e7a4a">

Noticed that the success message has a hard-coded gitops/metaphor. Which makes sense, but don't think that would impact create
<img width="1693" alt="Screenshot 2024-06-09 at 5 49 46 PM" src="https://github.com/kubefirst/kubefirst/assets/3058939/e76dad91-4c74-4b73-b0c9-749700fec91d">

I am not setting the flag with Viper in `flags.go`, but from what I can tell that's not necessary...? Perhaps I'm wrong
<img width="2672" alt="Screenshot 2024-06-09 at 5 51 27 PM" src="https://github.com/kubefirst/kubefirst/assets/3058939/3b986464-2d44-4f13-bd3d-168599eebda4">

I didn't define it in `apiTypes.ClusterDefinition` which might be the issue (not sure how this impacts gitShim, but maybe the check that throws is being done elsewhere):
<img width="1682" alt="Screenshot 2024-06-09 at 5 54 13 PM" src="https://github.com/kubefirst/kubefirst/assets/3058939/3e6b26c6-0a86-44e7-a4e4-3f18445c6ad6">

**Comment by fharper** [comment]
Thanks for this feature suggestion @alechp. Could you split those in two issues please as they will need different work in different places. Mainly, the `gitops` one will require a lot more work since it's hardcoded in multiples places.

**Comment by alechp** [comment]
Hey @fharper went ahead and split it into 3 issues (three requirements to enable deploying more than one gitops cluster per github organization):

- https://github.com/kubefirst/kubefirst/issues/2210
- https://github.com/kubefirst/kubefirst/issues/2211
- https://github.com/kubefirst/kubefirst/issues/2212

**Comment by fharper** [comment]
Thanks a lot, and sorry for the additional work 😅

Will close this one now.
