### ISSUE TITLE
kubefirst oss users should be allowed to install the oss platform without kubefirst pro

### ISSUE THREAD

**Issue by johndietz** [kubefirst/kubefirst#2202]
a stronger line needs to be drawn between the kubefirst oss platform and the kubefirst pro ui that we add to the platform at the end. users should be free to install the platform without the kubefirst pro product.

**Comment by johndietz** [comment]
add cli switch and advance ui checkbox to not install kubefirst pro (but default is to install)

**Comment by donnalux** [comment]
- Default is to install Pro - Free Plan.
- When user opts out - step 4 of launch
- Do not mention on site

**Comment by donnalux** [comment]
**UX Design:** 

https://www.figma.com/design/cLWCS4OWKnEnkV7uDOSNLp/Kubefirst-Console?node-id=1697-41365&t=DYf16ngmYD8YEoa1-4
