### ISSUE TITLE
Broken link in "kubefirst beta google destroy"

### ISSUE THREAD

**Issue by mrsimonemms** [kubefirst/kubefirst#2205]
### Which version of kubefirst are you using?

2.4.10

### Which cloud provider?

Google Cloud

### Which DNS?

None specific

### Which installation type?

CLI

### Which distributed Git provider?

None specific

### Did you use a fork of `gitops-template`?

No

### Which Operating System?

Linux

### What is the issue?

When running the `kubefirst beta google destroy` command, it displays the link "https://docs.kubefirst.io/google/deprovision". This returns a default nginx 404 (see also #2206).

The correct link should be https://docs.kubefirst.io/gcp/overview.

![image](https://github.com/kubefirst/kubefirst/assets/275848/385b7772-0d0f-477f-afc0-5516f6328db9)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jairoFernandez** [comment]
apparently we are using this funtion to resolve the Deprovision message:

https://github.com/kubefirst/kubefirst/blob/55e58cf642db4e48b11bdede6ba0f0a0d6077b4e/internal/common/common.go#L183

We need to discuss with Fred if is more easy to change the documentation from `https://docs.kubefirst.io/gcp/**` to `https://docs.kubefirst.io/google/**`

**Comment by jairoFernandez** [comment]
I'll close this issue, we solve temporally doing a redirect from /google/** to /gcp/**, in this PR https://github.com/kubefirst/docs/pull/715, thanks a lot @mrsimonemms for your catch!!
