### ISSUE TITLE
Add check to ensure that GitHub orgs can run Actions

### ISSUE THREAD

**Issue by mrsimonemms** [kubefirst/kubefirst#2216]
### What is your feature idea?

> Free GitHub orgs _should_ have 2,000 minutes and are able to create self-hosted runners so there's some root cause I'm missing here. I only know that using a public repo works and a private repo doesn't.

Related to https://github.com/kubefirst/docs/issues/720, if a GitHub org is a free account then it not able to trigger GitHub Actions. One effect of this is that only one KF cluster is able to be deployed (the rest stick in "provisioning").

There are two potential workarounds for this:
1. check that the organisation (not applicable for users) is able to run GitHub Actions on the `gitops` repo - if not, switch to using a "public" repo
2. provide an installer flag that allows you to switch between "public" and "private" repos

### Why is it needed?

Using a private repo on a free GitHub org breaks Kubefirst

### Is this missing feature preventing you from using kubefirst?

- [ ] Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fharper** [comment]
@mrsimonemms can you point where in the GitHub docs or webpage it's mention that a free GitHub organization cannot run GitHub Actions in private repositories? For future reference as one user may had this issue. I can't find the information...

**Comment by mrsimonemms** [comment]
Sorry @fharper, I thought I'd closed this - it's actually not an issue with GitHub Actions, but with how Kubefirst is setup. I've replaced this with @2232
