### ISSUE TITLE
Add EditorConfig support to Console

### ISSUE THREAD

**Issue by mrsimonemms** [kubefirst/kubefirst#2239]
This exists to standardise IDE configuration automatically and reduce compatibility issues across operating systems etc. See [parent issue](https://github.com/kubefirst/kubefirst/issues/2235) for more details

**Comment by CristhianF7** [comment]
Thanks @mrsimonemms. I think this is good for our golang repositories but Console has their own configuration with linter and prettier and this may cause a lot of issues.

**Comment by mrsimonemms** [comment]
@CristhianF7 Prettier and EditorConfig solve related, but distinct problems. Prettier makes sure the JavaScript is formatted to a known format, EditorConfig covers all files. It also covers things like line-endings, which Prettier/ESLint tend not to cover in my experience.

I've used Prettier/ESLint and EditorConfig together for about 10 years and never had a problem so I think this would be useful to include.

**Comment by CristhianF7** [comment]
Thanks for confirming @mrsimonemms

**Comment by mrsimonemms** [comment]
No probs. There's a PR for this which would like a review when you have time https://github.com/kubefirst/console/pull/481
