### ISSUE TITLE
Having trouble creating new K3D local cluster on Intel Mac (v14.6)

### ISSUE THREAD

**Issue by Kcorb95** [kubefirst/kubefirst#2255]
### Which version of kubefirst are you using?

v2.4.13

### Which cloud provider?

k3d (local)

### Which DNS?

None specific

### Which installation type?

CLI

### Which distributed Git provider?

GitHub

### Did you use a fork of `gitops-template`?

No

### Which Operating System?

macOS

### What is the issue?

Hey team! Having some issues getting k3d up and running on my intel mac (v14.6).

First was getting an error on Installing and configuring Argo CD about being unable to reach argocd.kubefirst.dev . I added it to my hosts file and was able to move on to Configuring Vault, but that's now giving me an error as well:
```
Error: unable to reach vault over https - this is likely due to the mkcert certificate store missing. please install it via `/Users/kevin/.k1/kubefirst/tools/mkcert -install`
```

However when I run that, I can see that they are already installed:
```
The local CA is already installed in the system trust store! 👍
The local CA is already installed in the Firefox trust store! 👍
```

After troubleshooting with support in Slack, we're hitting a wall with a fresh clean install in trying to create the k3d clusters. 

```
 ERRO[0010] Node k3d-kubefirst-server-0: Failed executing preStartAction 'WriteFileAction': [WriteFileAction] Writing 345 bytes to /tmp/localRe
ERRO[0010] Node k3d-kubefirst-server-0: Failed executing preStartAction 'WriteFileAction': [WriteFileAction] Writing 208 bytes to /etc/rancher/
ERRO[0010] Node k3d-kubefirst-server-0: Failed executing preStartAction 'WriteFileAction': [WriteFileAction] Writing 451 bytes to /bin/k3d-entr
ERRO[0010] Node k3d-kubefirst-server-0: Failed executing preStartAction 'WriteFileAction': [WriteFileAction] Writing 1325 bytes to /bin/k3d-ent
ERRO[0011] Failed Cluster Start: Failed to start server k3d-kubefirst-server-0: Node k3d-kubefirst-server-0 failed to get ready: error waiting 
ERRO[0011] Failed to create cluster >>> Rolling Back    
WARN[0011] Failed to delete volume 'k3d-kubefirst-images' of cluster 'kubefirst': failed to find volume 'k3d-kubefirst-images': Error: No such 
FATA[0011] Cluster creation FAILED, all changes have been rolled back! 
 exit status 1
```

Additional context in Slack: https://kubefirst.slack.com/archives/C03U34WJ7FW/p1722624581373809

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fharper** [comment]
@Kcorb95: it seems that you were able to fix your issue by adding the k3d local domains we use in `/etc/hosts/` so I'm closing this as resolves.

With that said, I would like to document that in case someone else had this issue, but I need more information. Since we never encountered this, any idea on why your setup require that?

For the docs, here are the domains that needs to be added:

```
argo.kubefirst.dev
argocd.kubefirst.dev
vault.kubefirst.dev
console.kubefirst.dev
chartmuseum.kubefirst.dev
atlantis.kubefirst.dev
minio.kubefirst.dev
metaphor-development.kubefirst.dev
metaphor-staging.kubefirst.dev
metaphor-production.kubefirst.dev
```
