### ISSUE TITLE
Gitlab install - Try to replace HTTPS based repo definition to SSH ones

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#256]
# Overview

Today github install uses SSH key to registry repos on argo, but gitlab uses HTTPS+Token. 

![image](https://user-images.githubusercontent.com/53096417/185476472-b868497a-002f-4cd2-bdae-c7aa578f9b1d.png)

# Goal

The goal of this ticket is to create a way Gitlab and Github can use SSH based repo definitions to prevent template tricks to address this.

**Comment by echoboomer** [comment]
This was fixed in the migration to Gitlab SaaS.
