### ISSUE TITLE
support for recertification in authentication for high-trust accounts like admin on gitlab and vault

### ISSUE THREAD

**Issue by johndietz** [kubefirst/kubefirst#259]
spawned from the kubefirst community slack thread
https://kubefirst.slack.com/archives/C01KVTDT0UC/p1660934416651119

we should at minimum strive to provide clarity to our community about the steps we have taken to secure our platform tools and security posture. for example vault and atlantis each have guidance that we have followed for securing their implementations, but that's not at all transparent to an end user.

a security section needs to be added to our docs as part of the documentation overhaul.

**Comment by fharper** [comment]
@johndietz: since we lost the history, and cannot see the content of the Slack discussion. Is there more details you want to add to this issue?

For the last part about the documentation, I created [this issue](https://github.com/kubefirst/docs/issues/87): feel free to add more details there also if needed.

**Comment by johndietz** [comment]
@fharper yes this one was derived from a conversation about our security posture and the steps we've taken to secure gitlab and vault, but applies generally to all of our platform components. the desire for this issue is to have some documentation that we can provide to our end users about the security measures that have already been taken on the platform that deviate from a "default installation". this is a docs issue though and can be closed as a duplicate of https://github.com/kubefirst/docs/issues/87. i'm okay closing this issue if you are as well.

**Comment by fharper** [comment]
oh OK, the title let me think we wanted to do something code-wise, closing this one, thanks for the details.
