### ISSUE TITLE
discuss app helm content location

### ISSUE THREAD

**Issue by jarededwards** [kubefirst/kubefirst#26]
lets have a discussion around where this content should live, i feel like `components/apps` could be a place for all helm chart content but up for debate
https://github.com/kubefirst/nebulous/tree/main/gitops/components/development/metaphor

**Comment by JaredEdwards** [comment]
```
registry
├── apps
│   └── metaphor
├── argo.yaml
├── argocd.yaml
├── atlantis.yaml
├── development.yaml
└── ops
    ├── argo
    ├── argocd
    └── atlantis
 ```
