### ISSUE TITLE
is it possible to integrate with an existing gitlab setup

### ISSUE THREAD

**Issue by johndietz** [kubefirst/kubefirst#260]
started from community slack thread
https://kubefirst.slack.com/archives/C01KVTDT0UC/p1660934159993299
---
a preexisting gitlab server ecosystem is not that different from the github story that we're working through in that it's a separate git provider that can be assumed to be up and running, and if you have keys you can connect repos to it, and configure argocd to get its gitops data from it.

i think we want to get this story into the roadmap. folks that have a complex self-hosted git ecosystem but want a bunch of awesome kubernetes stuff to work in minutes would likely be very inclined to want to stay on their preexisting operational git setup since they've already gone through the effort of getting it established, figuring out the issues, locking it down, documenting it, etc.

**Comment by echoboomer** [comment]
Given the recent pivot to support Gitlab SaaS exclusively, this is no longer relevant.
