### ISSUE TITLE
1.9.x - Create Automation to test Gitlab Flow

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#266]
# Overview

Create a an automation that executes the following commands in sequence:
> Any exit 1 is an signal of error.
```bash
# init
go run . init \
  --profile default \
  --cloud aws \
  --region us-east-1 \
  --aws-nodes-spot \
  --cluster-name cluster_name \
  --s3-suffix cicd01 \
  --admin-email email@host.io \
  --hosted-zone-name host.com

# create cluster
go run . cluster create

# backup certs
go run . backupSSL

# destroy cluster
go run . destroy 
go run . clean --destroy-buckets --destroy-confirm
go run . action remove-github # if github
```

# Notes

After destruction, ensure that: 
- VPC is removed (by tag)
- EC2/Load Balancer is removed (by tag)
- S3 Buckets are removed 
- KMS Alias is removed
- EKS Cluster is removed
- Volumes are removed for the EC2 Instances 
- *Routes are removed from Route53*-- # destroy doesn't delete routes

**Comment by 6za** [comment]
Although, destroy don't remove the routes, we may want to automate at  CI/Cd to remove it. To help speed the next run of the test. To make resolution of names faster.

**Comment by converge** [comment]
it might be good to have solve it separated https://github.com/kubefirst/kubefirst/issues/267

**Comment by converge** [comment]
initial test if there is resource

use:
—s3-suffix
—aws-nodes-sport

between create → destroy
backup ~/.k1

in case of destroy error:
 1 - apply terraform destroy (tfstate) -> based on backup
 2 - 2. API call to kill left overs resources (delete all tag based) -> based on backup

**Comment by 6za** [comment]
`—aws-nodes-spot` - right?

**Comment by 6za** [comment]
Summarizing my notes from the discussion:(this is not the solution is notes for a future improvement)
- It may exist a step 0, that knows every assets from the family of resources we care, check `notes` of the ticket description. This step has a binary on which run list operations againts the API of resources like buckets/kms/ec2/vpcs...   this will produce a file, probably a yaml of what exist today. This file is stored for a later step. 
> output: state_of_cloud.yaml 
- step 1: executes init
- step 2: executes create
- step 3: Validate if all the required elements expected were created as desired. At this step the binary of step zero could be run again, to check state state_of_cloud_post_create.yaml
> `state_of_cloud_post_create.yaml` subtracted `state_of_cloud.yaml` produces the list of all new elements.  Let's call it: delta_of_state_of_cloud.yaml 
- step 4: execute destroy(that should undo all that create did)
- step 6: execute clean(that should undo all that init did)
- step 7: Validate if all that as created(like what is listed at `delta_of_state_of_cloud.yaml`) was destroyed. 
- step 8: What ever is not deleted, that was created by this execution should be removed from the cloud. To allow a cleaner execution of CI/CD. 

Again, this is not a the Acceptance Criteria, this a possible evolution of this effort.
