### ISSUE TITLE
Nice to have - Make region of bucket on `state` - push to be the one in viper

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#281]
# Overview 

User already provide its region on  `init`, we should ask that again. 

![image](https://user-images.githubusercontent.com/53096417/186718319-0f172e45-4888-45cf-861b-2a5e3497e08b.png)

It does make sense to be optional on pull, but we could default to `virginia` in its absence as general amazon APIs does.

**Comment by echoboomer** [comment]
With the new aws command logic, none of this gets used anymore.
