### ISSUE TITLE
Error Handling - Try to address use of panic in the code and replace for returning errors.

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#284]
# Overview

Try to search opportunities to replace this:
```golang
if err != nil {
		log.Panicf("Error putting S3 versioning: %s", err)
}
```
By something like(bubbling up, to allow the command to exit with `exit code 1`):
```golang
log.Printf("Error putting S3 versioning: %s", err)
return err
```

https://github.com/kubefirst/kubefirst/blob/2feb82fea49bed0b229591cf87147f5c7c52ea32/internal/aws/aws.go

**Comment by 6za** [comment]
Reference: #282

**Comment by echoboomer** [comment]
Closing as this has mostly been sorted in the move to runtime.
