### ISSUE TITLE
CLI - init cmd: Progress bar not completing

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#289]
# Overview
![image](https://user-images.githubusercontent.com/53096417/186960450-9f01f23a-1f6e-4ed8-aee0-dc587c2521ee.png)

Last progress bar is missing to finish increment.

**Comment by converge** [comment]
Feels like it was fixed at some point:

![Screenshot 2022-08-31 at 20 53 05](https://user-images.githubusercontent.com/188671/187804606-f4b130fa-2330-40a0-8dcb-b88c84136e66.png)

Im closing the ticket, feel free to re-open it if we missed something.
