### ISSUE TITLE
Template - Metaphor-frontend has nor README.md

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#290]
# Overview 

Template repo [metaphor frontend](https://github.com/kubefirst/metaphor-frontend-template) has no readme.md like metaphor.

**Comment by 6za** [comment]
Metaphor Template: https://github.com/kubefirst/metaphor-template

**Comment by converge** [comment]
done at https://github.com/kubefirst/metaphor-frontend-template/pull/9
