### ISSUE TITLE
error while creating cluster

### ISSUE THREAD

**Issue by Shivaraj600** [kubefirst/kubefirst#296]
Hi team Adding few details regarding my setup
-> match all AWS Prerequesites
A.An AWS account with billing enabled
B.An established publicly routable hosted zone with dns 
C.Id with Admin access AdministratorAccess

->Using AWS cloudshell and logged in to AWS cli with admin access id
-> And kubefirst init was successful (kubefirst init --admin-email [xxxxx@gmail.com](mailto:xxxxx@gmail.com) --cloud aws --hosted-zone-name xxxx --region us-east-1 --profile default )
-but when i fire command kubefirst cluster create it creating cluster after that throwing bellow error

Process Parameters ... done! [1 in 1.001s]

Creating K8S Cluster
Prepare Temporary Repo ... 25.0% [#######.....................] [1 in 12m56.998282s]
panic: error: terraform init failed exit status 1
goroutine 1 [running]:
log.Panic({0xc000633440?, 0x2a?, 0xc000633420?})
/usr/local/go/src/log/log.go:388 +0x65
github.com/kubefirst/kubefirst/internal/terraform.ApplyBaseTerraform(0x0, {0xc0001355f0, 0x2f})
/github/workspace/internal/terraform/terraform.go:41 +0x585
github.com/kubefirst/kubefirst/cmd.glob..func6(0x2e04de0?, {0x2e528d0, 0x0, 0x0})
/github/workspace/cmd/create.go:78 +0x37b
github.com/spf13/cobra.(*Command).execute(0x2e04de0, {0x2e528d0, 0x0, 0x0})
/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x2e05060)
/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/kubefirst/kubefirst/cmd.Execute()
/github/workspace/cmd/root.go:26 +0x25
main.main()
/github/workspace/main.go:65 +0x41d

**Comment by Shivaraj600** [comment]
Hi team Adding few details regarding my setup
->Using AWS cloudshell and logged in to AWS cli with admin access id
-> And kubefirst init was successful (kubefirst init --admin-email xxxxx@gmail.com --cloud aws --hosted-zone-name xxxx --region us-east-1 --profile default )
-but when i fire command kubefirst cluster create it creating cluster after that throwing bellow error

Process Parameters            ... done! [1 in 1.001s]
- Creating K8S Cluster
Prepare Temporary Repo        ... 25.0% [#######.....................] [1 in 12m56.998282s]
panic: error: terraform init failed exit status 1

goroutine 1 [running]:
log.Panic({0xc000633440?, 0x2a?, 0xc000633420?})
        /usr/local/go/src/log/log.go:388 +0x65
github.com/kubefirst/kubefirst/internal/terraform.ApplyBaseTerraform(0x0, {0xc0001355f0, 0x2f})
        /github/workspace/internal/terraform/terraform.go:41 +0x585
github.com/kubefirst/kubefirst/cmd.glob..func6(0x2e04de0?, {0x2e528d0, 0x0, 0x0})
        /github/workspace/cmd/create.go:78 +0x37b
github.com/spf13/cobra.(*Command).execute(0x2e04de0, {0x2e528d0, 0x0, 0x0})
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x2e05060)
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/kubefirst/kubefirst/cmd.Execute()
        /github/workspace/cmd/root.go:26 +0x25
main.main()
        /github/workspace/main.go:65 +0x41d
[cloudshell-user@ip-10-0-88-83 ~]$

**Comment by 6za** [comment]
Hi!

Thanks for using kubefirst and sharing your issue. 

Would you mind to check the installer logs logs?
they are in the folder you executed  at `/logs`, I guess the file you want to take a look would be the last one generated or the one from the time of the run you are reporting the issue.

On our logs, you see what step on terraform the issue happen.  As this log may have some credentials, if you share part of, please redact your credentials before sharing. 


In general terms, this step will execute the creation of several resources on AWS on behalf of the credentials you provided to the init step. 

As it seems your `init` didn't failed, so you may have created S3 buckets on your account. So, the credential seems to be good as you described. 

With the logs we can research further which asset was not able to be created and troubleshoot further. 


Regards,

**Comment by 6za** [comment]
If this was just temporary issue, like break of communication between your machine and aws(or timeout) and the folders under `~/.k1` was not touched. If you run `kubefirst cluster create` again on the same place, installer will try to continue this installation.

We store checkpoints to allow this to work without repeating steps already executed.

**Comment by 6za** [comment]
Reading again this issue we realized this detail:  The installation was done using `AWS CloudShell`. 

`kubefirst` was not tested on it for the release `1.8.6`. we usually use local developer terminals to run the installer. 

I am running installation using `AWS cloudshell` terminal to try to simulate this issue.

**Comment by 6za** [comment]
Running the installation I got this error: 

```
LOG: 2022/08/30 16:34:47.171979 /github/workspace/pkg/shell.go:23: Commad Execution STDERR: %s Unable to connect to the server: getting credentials: exec: executable aws-iam-authenticator not found

It looks like you are trying to use a client-go credential plugin that is not installed.

To learn more about this feature, consult the documentation available at:
      https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins

LOG: 2022/08/30 16:34:47.172011 /github/workspace/internal/ssl/ssl.go:141: failed to create ns: %s, assuming that exists...exit status 1
LOG: 2022/08/30 16:34:47.172509 /github/workspace/internal/aws/aws.go:475: Listing the objects in the bucket:
LOG: 2022/08/30 16:34:47.209772 /github/workspace/internal/aws/aws.go:486: /certs/argo-secret.yaml (824640796304 bytes, class 0xc000692508) 
LOG: 2022/08/30 16:34:47.266758 /github/workspace/internal/softserve/softserve.go:21: creating soft-serve
LOG: 2022/08/30 16:34:47.402948 /github/workspace/pkg/shell.go:19: Error executing command: %v exit status 1
LOG: 2022/08/30 16:34:47.402971 /github/workspace/pkg/shell.go:21: Commad Execution: %s /home/cloudshell-user/.k1/tools/kubectl
LOG: 2022/08/30 16:34:47.402976 /github/workspace/pkg/shell.go:22: Commad Execution STDOUT: %s 
LOG: 2022/08/30 16:34:47.402985 /github/workspace/pkg/shell.go:23: Commad Execution STDERR: %s Unable to connect to the server: getting credentials: exec: executable aws-iam-authenticator not found

It looks like you are trying to use a client-go credential plugin that is not installed.

To learn more about this feature, consult the documentation available at:
      https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins

LOG: 2022/08/30 16:34:47.402992 /github/workspace/internal/softserve/softserve.go:29: Result:

        Unable to connect to the server: getting credentials: exec: executable aws-iam-authenticator not found

It looks like you are trying to use a client-go credential plugin that is not installed.

To learn more about this feature, consult the documentation available at:
      https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins
```

All the terraform action were completed to create the cluster, cluster was created, but this terminal lack one of the tools we use to authenticate against AWS EKS. 

All the dependencies we use are [available here](https://github.com/kubefirst/kubefirst/blob/main/build/Dockerfile)

In order the installer to work we need to be able to:
- kubectl against EKS cluster
- port-forward to that cluster to allow early setup
- helm install tools on the EKS cluster

**Comment by 6za** [comment]
Thanks again for reporting this issue, I tagged this on our community wishlist. 

We will try to test installer on AWS CloudShell on future releases. At the moment, it is not mode we currently support on 1.8.6, but check out all the other ways you can run the installer: https://github.com/kubefirst/kubefirst/blob/main/build/README.md


If are able to run it on AWS CloudShell with success and want to share your steps or tweaks on our code base, just feel welcomed to send us a PR. The page above is meant to store alternative ways to run the installer, and there would be a nice  home for a guide to run on AWS CloudShell. 

Thanks,

**Comment by Shivaraj600** [comment]
HI Thank you for your response.
I have tried in Amazon EC2 instance and installed all dependency manually and its working fine

Is there any way to automate it ? like installing all dependency

**Comment by 6za** [comment]
Sorry for late response, we have some docker docker containers to help on a blank machine, if the machine has docker you can run something like: https://github.com/kubefirst/kubefirst/blob/main/build/README.md#running-cli-in-docker-container

We still don't have a bash installer, similar to the `brew` one that is used for mac users. 
It is something we can improve. 


We will keep this ticket open, so we track and pursue such automation. 

Thanks for the feedback and the updates,

**Comment by fharper** [comment]
I'm closing this issue since you wrote everything is now working @Shivaraj600, but feel free to reopen or let us know on our Slack community if there is anything else https://kubefirst.io/slack.
