### ISSUE TITLE
Install and destroy output too long

### ISSUE THREAD

**Issue by marinhojess** [kubefirst/kubefirst#301]
Install and destroy output is too long due to progress line replication. 
This causes the progress view to be very cluttered, and can cause a limit overflow in the GitLab CI/CD view console.

![image](https://user-images.githubusercontent.com/19623668/187458309-2241426b-9405-4819-87b4-263669993649.png)

**Comment by 6za** [comment]
I think this issue is connected: #300

**Comment by converge** [comment]
done at https://github.com/kubefirst/kubefirst/pull/302
