### ISSUE TITLE
Create a Cluster "census" tool

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#308]
## Overview

Based on [this comment](https://github.com/kubefirst/kubefirst/issues/266#issuecomment-1233130373)

- Define a file format to store all the elements created by an installation, to help track of new infra elements.  
- Use cloud apis or tfstate files to collect this information. 
> cloud apis, may be better longer term. 
- Create a binary to execute this file generation(golang application)
- Create a binary to compare 2 of this file(golang application)
> Diff could be: identical sets, what was added, what was removed. 

Reference: #266

**Comment by 6za** [comment]
@kxdroid

**Comment by marinhojess** [comment]
- #346
