### ISSUE TITLE
Clean is removing SSL Certs

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#309]
# Overview 

`kubefirst clean --destroy-buckets --destroy-confirm` is removing all buckets that is meant to do, fora given installation. 

But one of this buckets is the SSL certs buckets, and that make us loose the certs for re-runs cycles. We should stop remove `by default` the ssl certs buckets. 

Choices:
- A: Add a flag to confirm you want to remove SSL too
OR 
- B: Without flag just stop to remove the ssl bucket. 

Code that is probably impacted: https://github.com/kubefirst/kubefirst/blob/135cd660b133c5c7b0c02a301b00a8d8fdd8d1f8/internal/aws/aws.go#L278

**Comment by converge** [comment]
fyi; https://github.com/kubefirst/kubefirst/issues/288

**Comment by 6za** [comment]
I closed 288, as this one has more details. Nice catch, I knew I had that before.

**Comment by converge** [comment]
done at https://github.com/kubefirst/kubefirst/commit/98bce33bd5f967edf60255bc733e39786292bf72

**Comment by converge** [comment]
The issue happens in a specific case only:
```
1. new installation
2. there is no backup bucket created yet
3. at the end of the installation, we must call "backupSSL"
4. it will create a new backup (if it wasn't created before), and our aws/createBucket function is also storing the bucket name in the viper file
5. call "destroy"
6. call "clean" with the destroy-buckets flags
7. viper file contains the backup bucket name (because of step 4)
8. clean will destroy the backup bucket
```

To mitigate this kind of bug, I believe it's a good idea to isolate what the function does. For example, `createBucket`, should only create a bucket, in case we need to store some information in the viper file, it could be a second step since not all new buckets needs to be in the viper file.
