### ISSUE TITLE
Create a noTTY mode of installer to be easily embedded on CI/CD flows

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#310]
# Overview 

Silent mode can be very anxious prone for people watching a CI/Cd that takes 30 mins to run, so a alternative to silence mode is to have a `non-tty` mode, by tweaking the bars tools to work, without rendering its actions. 

Code provided on this pr: https://github.com/kubefirst/kubefirst/pull/304

**Comment by converge** [comment]
done at https://github.com/kubefirst/kubefirst/pull/302
