### ISSUE TITLE
Create CI/CD for docs updates

### ISSUE THREAD

**Issue by marinhojess** [kubefirst/kubefirst#333]
To ensure that the Kubefirst documentation update process is done quickly and efficiently, it's necessary to create a CI/CD to push the changes to the S3 bucket.

The updates must be made in the pre-prod and prod environments.

**Comment by Adidev-KGP** [comment]
Hi! Can I work on this issue @marinhojess? I have experience in creating CI/CD pipelines using GitLab runner. 
Actually I am interested in kubefirst and want to contribute to it and I feel this can be a nice starting point for me.

**Comment by marinhojess** [comment]
Hey @Adidev-KGP,

First of all, thank you for using kubefirst! 

I have an open pull request for this issue https://github.com/kubefirst/kubefirst/pull/342, please feel free to review it and suggest changes.

We have other very interesting issues that I think would be really cool if you could help us. 
This issue is mapping a need that we will have to include in our CI to ensure that the resources were correctly created. https://github.com/kubefirst/kubefirst/issues/308

Do you think it's something you'd like to contribute?

I'm looking forward to hearing from you!

**Comment by Adidev-KGP** [comment]
Yeah, I'll definitely like to contribute to issue #308, please assign it to me.
