### ISSUE TITLE
1.9.x - Terraform update vault for secret SSH_PRIVATE_KEY

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#337]
# Overview

https://github.com/kubefirst/gitops-template/pull/99#discussion_r965940376

**Comment by pagottoo** [comment]
closed by: https://github.com/kubefirst/gitops-template/pull/100

**Comment by 6za** [comment]
Secret is not passing to vault side.

**Comment by 6za** [comment]
Tested on #340.
