### ISSUE TITLE
handoff screen memory leak

### ISSUE THREAD

**Issue by converge** [kubefirst/kubefirst#349]
In this https://github.com/kubefirst/kubefirst/pull/340, we introduce the handoff screen (browser UI/API). The code is commented in such PR, and applied in this https://github.com/kubefirst/kubefirst/pull/348

There are two points we would like to improve:

1. the Go routines are kept open, and main Go routine will kill it in the end. We want to gracefully handle go routines using a join point (channel or waitgroup).
2. The HTTP/API is kept open because of a second function that is not related to the Go routines (reports.HandoffScreen), when the user exits the console UI screen, the API and UI(browser) will also be killed. If the user tries to load the UI(browser) url, it will fail, and he won't know the reason.

Proposal:
- tell the user after exiting the handoff screen that the UI(browser) is still running, and it can be killed by executing "ctrl+c"
- add a channel to listen to os.Signal on the "ctrl+c" keyboard command to kill the main thread and exit gracefully
- tell the user that he can load the UI(browser) again by using `kubefirst command-name`

**Comment by 6za** [comment]
Just an update: #340 was merged without the code in question enabled. The code is at #348 to allow tests of the new feature.

**Comment by converge** [comment]
this is necessary since the go routines should not rely on another function that will hold the go routine forks. if someone touches/changes the handoff screen, it will create a bug for the go routines that hosts the API.

go routines rely on a fork join model, every time there is a fork, it might have a reconciliation/join point.

**Comment by converge** [comment]
I can't agree, but let's move it to a later point to discuss since 1.9 release is high priority now.

**Comment by fharper** [comment]
Next release won't have the handoff screen with the CLI rewrite done by @CristhianF7 so closing this issue as invalid.
