### ISSUE TITLE
[Docs]: GitLab general updates

### ISSUE THREAD

**Issue by converge** [kubefirst/kubefirst#368]
type: update
status: pending
location: `kubefirst/gitlab.md`

### Acceptance criteria:
AC1: needs new docs on gitlab OIDC configuration
AC2: needs new automated capability and docs on gitlab backups
AC3: need new docs on configuring gitlab to be able to send emails

**Comment by fharper** [comment]
The ones that were still relevant were moved into individual issues as I was moving notes from `mkdocs.yml` from @johndietz into issues.
