### ISSUE TITLE
How to install Kubefirst using GitHub

### ISSUE THREAD

**Issue by converge** [kubefirst/kubefirst#369]
type: new page
status: pending
location: pending

### Acceptance criteria:
AC1: there is a new page that describes how to install Kubefirst using GitHub
AC2: the user have all the details to be able to run a new installation

**Comment by 6za** [comment]
I think this is related to: https://github.com/kubefirst/kubefirst/issues/389

**Comment by converge** [comment]
#389 sounds like internal/developer documentation, we want to update the docs for the end user.

for example:
```
./kubefirst init --profile default --cloud aws --region $REGION \
    --admin-email $EMAIL --hosted-zone-name $HOSTED_ZONE --aws-nodes-spot \
    --cluster-name $CLUSTER_NAME --s3-suffix $S3_SUFFIX --github-user $GITHUB_USER \
    --github-org $GITHUB_ORGANIZATION --metaphor-branch $METAPHOR_BRANCH ----gitops-branch $GITOPS_BRANCH
```
end user wont need to specify branches, env values, etc

**Comment by converge** [comment]
missing update screen shots at after-install page

**Comment by converge** [comment]
https://github.com/kubefirst/kubefirst/pull/391
