### ISSUE TITLE
[Docs]: ArgoCD updates

### ISSUE THREAD

**Issue by converge** [kubefirst/kubefirst#371]
type: update
status: pending
location: `kubefirst/argocd.md`

### Acceptance criteria:
AC1: app of apps patterns
AC2: it describes how Kubefirst make use of ArgoCD sync waves on cluster provisioning
AC3: it describes how Kubefirst setup and use OIDC integration and service accounts for ArgoCD

**Comment by fharper** [comment]
Split in different issues for easier traceability and planning:
- https://github.com/kubefirst/kubefirst/issues/984
- https://github.com/kubefirst/kubefirst/issues/987
- https://github.com/kubefirst/kubefirst/issues/986
