### ISSUE TITLE
[Docs]: GitOps general update

### ISSUE THREAD

**Issue by converge** [kubefirst/kubefirst#372]
type: update
status: pending
location: `kubefirst/gitops.md`

# issues: 
        - need new image for the top
        - need new video for gitops rollbacks
        - need new section on how to add an application to the kubefirst platform
        - need branded image for architecture diagram
        - need better image that has singular registry
        - paths in docs need adjustment for open source platform (no east-2, etc)
        - drop the bottom section (secure registration layer)

**Comment by fharper** [comment]
The ones that were still relevant were moved into individual issues
