### ISSUE TITLE
[Docs]: Terraform general updates

### ISSUE THREAD

**Issue by converge** [kubefirst/kubefirst#374]
type: update
status: pending
location: `kubefirst/terraform.md`

# issues
### Terraform & Atlantis: 'kubefirst/terraform.md'
     
- video is enormous here
- info on webhooks
- info on security measures
- info on audit log
- info on state object versioning
- atlantis in realtime with gitlab
- atlantis.yaml
- entrypoint walkthroughs
- - Page: base
- - Page: users
- - Page: github
- - Page: gitlab
- - Page: vault

**Comment by fharper** [comment]
The ones that were still relevant were moved into individual issues as I was moving notes from `mkdocs.yml` from @johndietz into issues.
