### ISSUE TITLE
[Docs]: Vault general updates

### ISSUE THREAD

**Issue by converge** [kubefirst/kubefirst#375]
type: update
status: pending
location: `kubefirst/vault.md`

### Acceptance criteria:

AC1: it describes how Kubefirst make us of Vault ACL policies
AC2: it describes how the root Vault token works, and how Kubefirst make use of it
AC3: it describe disaster recovery scenarios with dynamodb point in time recovery
AC4: it describes thorough docs on external-secrets describing architecture to remove Vault realtime dependency

**Comment by fharper** [comment]
This was also a suggestion written by @johndietz in [mkdocs.yml](https://github.com/kubefirst/kubefirst/blob/e02ea71c886a2225c355db1a813a0b6276611c60/mkdocs.yml#L86)

**Comment by fharper** [comment]
The ones that were still relevant will be moved into individual issues as I was moving notes from `mkdocs.yml` from @johndietz into issues.
