### ISSUE TITLE
[Docs]: details about the direction we're heading for each boulder described on the roadmap

### ISSUE THREAD

**Issue by converge** [kubefirst/kubefirst#383]
type: new page
status: pending
location: pending

**Comment by converge** [comment]
hey @johndietz , I would like your inputs on this one, to follow your initial idea on that topic.

**Comment by fharper** [comment]
@converge : currently the roadmap page on the docs is empty, is this issue still relevant?

**Comment by fharper** [comment]
We will revisit on next release, but for 1.11 we are fine with https://docs.kubefirst.io/roadmap/index.html
