### ISSUE TITLE
Error to create cluster

### ISSUE THREAD

**Issue by marinhojess** [kubefirst/kubefirst#388]
Error creating cluster with Gitlab flavor:

`LOG: 2022/09/13 08:58:07.537726 /home/jessicamarinho/kubefirst/internal/flagset/common.go:58: Enviroment Variable(dry-run) not set
LOG: 2022/09/13 08:58:07.537764 /home/jessicamarinho/kubefirst/internal/flagset/common.go:58: Enviroment Variable(use-telemetry) not set
LOG: 2022/09/13 08:58:07.537769 /home/jessicamarinho/kubefirst/internal/flagset/common.go:58: Enviroment Variable(silent) not set
LOG: 2022/09/13 08:58:07.538016 /home/jessicamarinho/kubefirst/internal/metaphor/metaphor.go:22: cloning and detokenizing the metaphor-template repository
LOG: 2022/09/13 08:58:07.538072 /home/jessicamarinho/kubefirst/internal/gitClient/git.go:219: Trying to clone tag():1.8.6 
LOG: 2022/09/13 08:58:08.268490 /home/jessicamarinho/kubefirst/internal/gitClient/git.go:254: error removing old branch: metaphor, remove /home/jessicamarinho/.k1/metaphor/.git/refs/heads: directory not empty
`

**Comment by 6za** [comment]
Just to make it easier to read. 
```
LOG: 2022/09/13 08:58:07.537726 /home/jessicamarinho/kubefirst/internal/flagset/common.go:58: Enviroment Variable(dry-run) not set LOG: 2022/09/13 08:58:07.537764 /home/jessicamarinho/kubefirst/internal/flagset/common.go:58: Enviroment Variable(use-telemetry) not set LOG: 2022/09/13 08:58:07.537769 /home/jessicamarinho/kubefirst/internal/flagset/common.go:58: Enviroment Variable(silent) not set LOG: 2022/09/13 08:58:07.538016 /home/jessicamarinho/kubefirst/internal/metaphor/metaphor.go:22: cloning and detokenizing the metaphor-template repository LOG: 2022/09/13 08:58:07.538072 /home/jessicamarinho/kubefirst/internal/gitClient/git.go:219: Trying to clone tag():1.8.6 LOG: 2022/09/13 08:58:08.268490 /home/jessicamarinho/kubefirst/internal/gitClient/git.go:254: error removing old branch: metaphor, remove /home/jessicamarinho/.k1/metaphor/.git/refs/heads: directory not empty
```

IT seems to be related to recent changes, to support branch installs: #358 

We need to test it against tag builds.

**Comment by 6za** [comment]
@marinhojess  is this issue still an issue?

**Comment by converge** [comment]
Im on it

**Comment by converge** [comment]
at current dev. state, this flag is required since metaphor apps at default tag version 1.8.6 doesn't have the latest updates for GH integration.
```
--metaphor-branch main
```

what was happening is that without the explicit `metaphor branch-name`, it tries to load 1.8.6 tagged branch on metaphors.
