### ISSUE TITLE
Error to create cluster with assume role

### ISSUE THREAD

**Issue by marinhojess** [kubefirst/kubefirst#406]
When using assume role with the Kubefirst installer running on Argo Workflows, it fails when trying to create the cluster.

![image](https://user-images.githubusercontent.com/19623668/190499991-865b3b7b-3a56-4961-b00b-7ca17a2a9898.png)

**Comment by marinhojess** [comment]
We need to check if the AWS_PROFILE variable is conflicting with the ARN_ROLE authentication.

**Comment by marinhojess** [comment]
The init command doesn't allow to be executed without the aws profile being informed, this is probably creating the authentication conflict.

![image](https://user-images.githubusercontent.com/19623668/190512477-a8f52acd-909d-4f19-9530-dfa25b9a0615.png)

**Comment by 6za** [comment]
Based on the last tests, we are having some challenge to confirm `assumeRole` works as expected for `init` operation. Although, it seems to work as expected on the `awswhoami` command.

**Comment by marinhojess** [comment]
Added the following trusted relationship to the role that the CI wants to assume:

```
{
    "Sid": "Statement1",
    "Effect": "Allow",
    "Principal": {
        "AWS": "arn:aws:iam::xxx:role/kubefirst-worker-nodes-role-6zray_kubefirst_tech"
    },
    "Action": "sts:AssumeRole"
}
```
After this insertion, kubefirst init worked as expected.

**Comment by marinhojess** [comment]
By removing the `currentCommand.MarkFlagRequired("profile")` line in the cmd/init.go file it's possible to init kubefirst without informing the aws profile.

**Comment by marinhojess** [comment]
Even after suppressing the profile in kubefirst init, kubefirst create still exports the variable AWS_PROFILE, as shown in the following print:

![image](https://user-images.githubusercontent.com/19623668/191092825-f19cf4bd-924e-4a88-919e-4a179b275836.png)

**Comment by 6za** [comment]
@marinhojess is this still an issue?
