### ISSUE TITLE
terraformed users should have automatic membership to kubefirst project in gitlab

### ISSUE THREAD

**Issue by johndietz** [kubefirst/kubefirst#41]
the terraformed users in the gitops repo are automatically added to either the admin or developer group in gitlab.

that setup should be extended such that:
- admin group is added to the kubefirst group as owner
- developer group is aded to the kubefirst group as developer

**Comment by 6za** [comment]
Are we covering this? 

@jarededwards  or @pagottoo  are we covering this on the current release effort?
