### ISSUE TITLE
 aws-nuke - Nuke account itesm to backup

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#421]
# Overview 

This ticket is meant to a note what we want preserve on account nuking procedures to reduce waste resources on our account.

**Comment by 6za** [comment]
## Preserve certificates

Save the buckets with certs with something like: 

### Backup
```bash 
# Download Certs
docker run --rm -it -v $HOME/.aws:/root/.aws \
  -v $HOME/_s3_temp:/target \
  amazon/aws-cli s3 sync s3://k1-$DOMAIN /target


```

### Post Nuke

```bash 
docker run --rm -it -v $HOME/.aws:/root/.aws \
  -v $HOME/_s3_temp:/target \
  amazon/aws-cli  s3api create-bucket --bucket k1-$DOMAIN --region us-west-1 --create-bucket-configuration LocationConstraint=us-west-1

docker run --rm -it -v $HOME/.aws:/root/.aws \
  -v $HOME/_s3_temp:/target \
  amazon/aws-cli s3 sync /target s3://k1-$DOMAIN

```

**Comment by 6za** [comment]
Do we want to backup Route53 hostnames? 
> I think we pay for public names, not subdomains. So we may want preserve their records post-destroying the cluster.

**Comment by pagottoo** [comment]
> Do we want to backup Route53 hostnames?
> 
> > I think we pay for public names, not subdomains. So we may want preserve their records post-destroying the cluster.

We need to put Route53 on the exclusion filter of aws-nuke. (to avoid issues on DNS propagation)

**Comment by marinhojess** [comment]
If the target region is us-east-1, it's not necessary to inform the region in the post nuke commands. 

https://docs.aws.amazon.com/cli/latest/reference/s3api/create-bucket.html#options
