### ISSUE TITLE
ArgoCD - self-signed certificate conflicting with cert-manager certificate secret

### ISSUE THREAD

**Issue by pagottoo** [kubefirst/kubefirst#422]

**Comment by 6za** [comment]
# Overview 

Based on discussion


@jarededwards 
> https://github.com/kubefirst/gitops-template/blob/main/components/argocd-gitlab/application.yaml#L31
[application.yaml](https://github.com/kubefirst/gitops-template/blob/main/components/argocd-gitlab/application.yaml)

> yes, thats exactly what we’re referring to. the cert used to live in argocd-secret or something to that effect but since we’re using a different secret argocd automatically generates a self signed certificate in argocd-secret and for some reason argocd has a bug that it switches between the two certificates (the correct one from cert manager in argocd-server-tls and the incorrect self signed in argocd-secret )

> it was cycling between the two in a browser on page refresh, it was odd


@pagottoo 
> huuum, :thinking_face:
> got it
> we could disable tls on argocd-server, and manage tls isolated on ingress...
or we could update the argocd-secret with the cert, and mark these fields on argo to avoid conflicts like argo warns about out of sync


@jarededwards 
> yea im not sure what the best way is - when we deleted the incorrect tls.key and tls.crt  in the argocd-secret  the problem went away , so it might be just as good to remove the self signed cert so we can leave the application as is


@pagottoo 
> yes, looks like a good approach


Reference: https://argo-cd.readthedocs.io/en/stable/operator-manual/tls/#tls-certificates-used-by-argocd-server
