### ISSUE TITLE
Discussion/Update - Review the worker nodes definition

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#423]
# Overview 

Today we provision [3 compute groups](https://github.com/kubefirst/gitops-template/blob/main/terraform/base/eks/main.tf#L37). 

Although we seems to use only 1 or 2. 

The goal of this ticket is to define how much workers groups we want to have, and from that update terraform and applications node selector polices to follow the new definition.

**Comment by 6za** [comment]
From last discussion:
- we may want to have just one
OR
- Two one for management apps and other for applications like (metaphors)

**Comment by pagottoo** [comment]
I believe they (metaphor apps) could share the management nodes.

The only reason to justify another node pool is to show how the apps can be scheduled across the nodes... 
But this is more like a k8s tutorial than the kubefirst tutorial... IMHO
