### ISSUE TITLE
1.9.x - Gitlab Metaphor are missing icons of metaphor

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#430]
# Sample

<img width="392" alt="image" src="https://user-images.githubusercontent.com/53096417/191510613-b41c0891-1dcf-4013-80d3-300a41e9eacb.png">

- Metaphor has icon
- Metaphor-go: don't have it 
- Metaphor-frontend: don't have it

**Comment by johndietz** [comment]
in order to address this issue, there simply needs to be a logo.png added to the repository root in the respective template repos. see:
https://github.com/kubefirst/metaphor-template/blob/main/logo.png

**Comment by 6za** [comment]
logo added to repos.

**Comment by 6za** [comment]
<img width="325" alt="image" src="https://user-images.githubusercontent.com/53096417/191834227-01a45126-72b0-498e-a3bf-c7ad5d784be7.png">
