### ISSUE TITLE
State Pull - Issue

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#451]
# What?

The command `go run . state --bucket-name=bucket-name --region=us-east-1 --pull` is meant to allow a second developer to continue an installation or destroy an installations, recycling the files created from the 1st installer run event. 

It seems that the tool is not doing what is expected, based on reports. 

# How?

The goal of this ticket is to review the behavior of the tool and fix it to behave as expected. 

It should be tested and provide details on how to use it.

**Comment by converge** [comment]
the `state` command was designed to store the `.kubefirst` file only.

**Comment by 6za** [comment]
As discussed internally, I think there were a confusion on the requirements. 


> from  @jarededwards:
> Yea we discussed having a time stamp but decided that the S3 object versioning would be good enough so the file name wasn’t an issue and that piece wasn’t useful. I think we do need to store the ‘.k1’ directory in s3 as well or it’s much more difficult to take over a stack for a scenario like we just went through  (edited) 


> from @converge: 
> I can’t remember exactly why we removed the .k1 folder from the backup, do you 

> from @johndietz:
> hey good morning crew - yeah thought we ended up bailing on the timestamp requirement, but we did want to put both the .k1 folder and the .kubefirst file (with no need for timestamp) at the conclusion of the cluster create execution right in the s3 state bucket’s root. that probably got confusing when we were talking about “only .kubefirst” meaning with no timestamp on the filename. (edited)

**Comment by 6za** [comment]
So, the function was always intended to be used by a second developer to be able to continue or destroy an installation.
