### ISSUE TITLE
kubectl and go-client

### ISSUE THREAD

**Issue by converge** [kubefirst/kubefirst#452]
Our beloved `kubectl` command line calls works perfectly, but we would like to use `go-client` only to communicate with Kubernetes resources.

When our code calls host commands like `kubectl`, `kubectl` is using Go `go-client` library to do the required task, then our current code is:
```
1. using OS command line tool "kubectl"
2. "kubectl" is using go-client to do the task
3. we stream the OS output and return it to the go code via logs
```

after this ticket:
```
1. OS command line calls to "kubectl" are removed
2. Kubernetes communication is always done via go-client
```

note: this is a big story, and requires a lot of work.

### Acceptance criteria:
AC1: there is no command line calls to `kubectl`
AC2: `kubectl` doesn't need to be downloaded during `init`
AC3: kubectl doesn't need to be included in the end user Dockerfile

**Comment by 6za** [comment]
To avoid a PR with a huge refactory, as it would probably impact several parts of the installation. 

It would be nice, if this is done, it is divided on smaller PRs focus on a component update, and tested. If tests show no impact, then proceed to merge. 

Some artifacts may be tricky to be populated via structs such us CRD objects.
