### ISSUE TITLE
CI - Is current CI  flaky?

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#458]
# What?

IT seems current CI is too verbose to be clear where the issues are happening. 

And sometimes we have this message and job fails:
```bash 
Successfully built 6a347053b6b4
Successfully tagged kubefirst_kubefirst-unit-tests:latest
service.platform should be part of the service.build.platforms: "linux/amd64"
```

Sample: https://github.com/kubefirst/kubefirst/actions/runs/3129759209/jobs/5079236256

# What to do? 

- Let's try to make the job less verbose, to allow us to troubleshoot the build issues. 
- Maybe tweak the github action to add node type selectors to sove issue from the error above, if that is the cause of it. 

# What is creating?

Some merged PRs seems to be marked as fail, although the branch test worked. That is very odd.

**Comment by converge** [comment]
hey @marinhojess , I started something here https://github.com/kubefirst/kubefirst/pull/461

**Comment by converge** [comment]
https://github.com/kubefirst/kubefirst/pull/461
