### ISSUE TITLE
cmd version has no version

### ISSUE THREAD

**Issue by converge** [kubefirst/kubefirst#491]
observed behavior:

cmd version command is showing empty version when git clone repo.

expected behavior:

cmd version shows version information when git clone.

AC1: it does shows version when cmd version is called
AC2: ldflags still works when new release

**Comment by 6za** [comment]
there is a flag `experimental` to help work on development mode. 

Although, the LD Flags is the expected path:

```
go build -ldflags="-X github.com/kubefirst/kubefirst/configs.K1Version=1.8.6" .
```

**Comment by 6za** [comment]
If used `--experimental-mode` on init, that will make main the brach to be cloned, preventing issues with the lack of version.
