### ISSUE TITLE
error gracefully, and return more details when git clone fails

### ISSUE THREAD

**Issue by converge** [kubefirst/kubefirst#492]
observed behavior:

user reported that the message isn't clear when this error happens https://kubefirst.slack.com/archives/C03U34WJ7FW/p1664544076850029

expected behaviour:

inform the user that he needs to `git clean < destroy buckets >` before trying to `cluster create` again.

**Comment by echoboomer** [comment]
Cannot find original thread anymore and this is likely not an issue anymore.
