### ISSUE TITLE
segment.io integration

### ISSUE THREAD

**Issue by converge** [kubefirst/kubefirst#499]
As a Kubefirst user I want to collect metrics during the installation process so that I know better how Im experiencing the installation on a user stand point from start to finish.

**Acceptance criteria:**
AC1: it uses official Segment.io Golang library[1]
AC2: the implementation is feature parity[2] with Datadog
AC3: previous telemetry implementation still works for user running previous Kubefirst installer
AC4: the implementation is loosely coupled to allow unit tests
AC5: there are unit tests (at least some)
AC6: there are Segment.io documentation at docs.kubefirst.com describing how we use Segment.io
AC7: segment.io is default, and doesn't require a new flag
AC8: metrics are associated with user domain, and Kubefirst cli version
AC9: We need to be able to privately dashboard this information with varying time granularity (last hour, last 2 months, etc)

[1] https://github.com/segmentio/analytics-go
[2] events captured: init started, init completed, cluster create started, cluster create completed

### Details

Today (as of 1.9), we implement our telemetry MVP leveraging a custom metric microservice named telemetry that runs in our mgmt account so we can measure the frequency and success rate of init and create commands. This is implemented with 4 calls in kubefirst/kubefirst that look approximately like this:

https://github.com/kubefirst/kubefirst/blob/70f3d268040ac8af921b5416d53113f8138e9b06/cmd/createUtils.go#L51

*Note: We must KEEP the telemetry microservice operational until we're convinced nobody is using the older cli versions that leveraged this microservice. (probably a few months out)*

**Comment by 6za** [comment]
Do we care about protecting the `SEGMENT_WRITE_KEY` on segment?

**Comment by jarededwards** [comment]
Let’s add this to the service we proxy to for Datadog metrics currently to keep it protected for now

**Comment by converge** [comment]
I did research regarding the `SEGMENT_WRITE_KEY`, from Segment website[1]:

```
The write key is the unique identifier for a source that tells Segment which source data comes from, to which workspace the data belongs, and which destinations should receive the data.
```

They had a security incident with a customer, and in the incident description it was raised that the write key is considered public:

```
Two months of recent data about how Segment's own customers interact with different aspects of our product, including customer write keys for Segment (which are considered public)
```

Other projects also expose[3] the key.

[1] https://segment.com/docs/connections/find-writekey/
[2] https://segment.com/blog/bulletins-incident090519/
[3] https://github.com/search?p=1&q=segment_write_key&type=Code

**Comment by converge** [comment]
![Screenshot 2022-10-05 at 11 24 35](https://user-images.githubusercontent.com/188671/194085075-bd2b96c1-ed83-4a81-abbe-08cc381d61ed.png)

I believe we have two ways to implement it. Disabling AppRunner, and rely only on Segment.io, that will forward the metric to DataDog via Segment.io destination, will have one last app(app runner) for us to maintain.

**Comment by johndietz** [comment]
yeah i agree with the direction of the 2nd approach as our permanent approach. i do want to mention however that while we're removing the dependence on the telemetry app running in apprunner, old kubefirst clients in the wild will still use it until they upgrade the cli, so let's be sure to not disrupt anything about the `cli -> telemetry -> datadog` flow of data for the next few months - no deprovisioning operations in apprunner please.

**Comment by converge** [comment]
> yeah i agree with the direction of the 2nd approach as our permanent approach. i do want to mention however that while we're removing the dependence on the telemetry app running in apprunner, old kubefirst clients in the wild will still use it until they upgrade the cli, so let's be sure to not disrupt anything about the `cli -> telemetry -> datadog` flow of data for the next few months - no deprovisioning operations in apprunner please.

added a new AC in the ticket description to follow that.
`AC3: previous telemetry implementation still works for user running previous Kubefirst installer`
