### ISSUE TITLE
kubefirst on the localhost

### ISSUE THREAD

**Issue by johndietz** [kubefirst/kubefirst#501]
We're looking for a way to provide a kubefirst platform experience run entirely on the localhost. This is architecturally different from a cloud kubernetes environment in a number of different ways:
- the localhost has no native ingress available so the localhost story might need a local k8s [distro that supports that](https://k3d.io/v5.4.6/usage/exposing_services/)
- memory and cpu availability on a localhost will be significantly less available and we may need to make some choices about what pieces we deliver
- vault backend with dynamo and kms will need accommodations
- s3 storage for terraform state, argo artifacts, and chartmuseum helm charts will need accommodations
- ecr registry for containers will need accommodations

Today (1.9) many of our apps intercommunicate over the ingress' dns, and almost all of those should pivot to internal cluster references. This is a permanent change and not associated with this localhost feature, but doing so will help this localhost feature not depend on ingress so heavily.

The four most important things to be able to demonstrate from the localhost story are:
- metaphor gitops delivery with workflows
- atlantis automation of terraform
- vault secret store
- telemetry of a cluster create event

**Comment by 6za** [comment]
Exploring `localhost` experience using k3d:

```bash 
wget -q -O - https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | TAG=v5.4.6 bash
```

Initial thoughts: 
- This would be a "lite" experience of kubefirst. 
- It would have the basic to show keys elements of kubefirst, but will rely on some local adaptations to make it work. 
- [Persistence](https://dev.to/bbende/k3s-on-raspberry-pi-volumes-and-storage-1om5) we may try to replace s3 buckets PVC for local folders on host
- It would not be a production ready version, mostly an demo experience that is operational to help developers to create metaphor like applications with a set of devops experience
- It initial version will be based on a fork of the `github` version of kubefirst to save resources on the git repo. 
- For webhook, something like [ngrok](https://ngrok.com/) may works for exposing the cluster to web-events with ephemeral URLs.

**Comment by 6za** [comment]
The "lite" version.. "kubefirst-step" :) 
- Would include only 1 metaphor, the original one in nodejs. 
- We would have Vault as secret manager 
> Vault setup may need to be harmonized to be setup for local use, no KMS or DynamoDB
- We would have Vault as IDP
- ArgoCD + Argo workflows 
- External-secrets 
- We wouldn't need the lets encrypt tooling as most of routes would be internal
> cert-issuer, cert-manager, .. ingress-nginx?
- We would also have a github-runner with ngrok for webhooks? 
> More research on this.

**Comment by converge** [comment]
it would be nice if we could not change business logic to make it work, therefor we could also use this localhost version for faster local development.

https://localstack.cloud have some (if not all) the services we need to run it locally.

**Comment by 6za** [comment]
## What a developer should be able to do?

To `use` regular `kubefirst` cli to create a "local" cluster, with basics `kubefirst` tooling:

- Secrets for metaphor are stored on `vault` and injected by `external secrets`
- `repos` or `users` can be added using simple `terraform` PRs against gitops repo. 
- Metaphor is self-deployed in cluster using existing `cwft` and github actions events 
- A `console` application would be deployed to welcome users to the cluster and its tooling. 
> Ticket for it need to be open with details. This also should help to guide users to install the cloud version. 
- All applications in use would work with the cluster vault acting as the identity authority. 

Limitations: 
- Webhook events would need some bridged and proxied from the web, limited experience. 
- Hostnames and routes would be probably most self-signed local certs or HTTP.

**Comment by 6za** [comment]
As a sub-product of this journey we will fork/review all the artifacts at [gitops](https://github.com/kubefirst/gitops-template) in order to redirect some routes to leverage in cluster communication. 

A set of artifacts in registry will be tagged as `core` **addon**. That will be deployed on all flavors of kubefirst, and some others will be tagged as  `cloud`, that would be only used on `non-local` setups. 

We also may have `lite` or `firststeps`(or any other branding) to allow local setup only artifacts.

**Comment by 6za** [comment]
> it would be nice if we could not change business logic to make it work, therefor we could also use this localhost version for faster local development.
> 
> https://localstack.cloud have some (if not all) the services we need to run it locally.

We do intend to have, it as way to test some experiences in local mode. There will be a clear gap of some tooling in particular networking and mechanics of the installer to leverage more the docker availability to manage steps of the installation. 

As a flavor of the runner, we are starting with K3d as there is some already affinity in the team with it.  And also, it seems it seems to be a very minimal setup.

**Comment by 6za** [comment]
Details on https://docs.localstack.cloud/localstack/
https://news.ycombinator.com/item?id=24179455
https://blog.ruanbekker.com/blog/2020/02/12/lightweight-development-kubernetes-options-k3d/

_My gut feeling is that the key part of the experience is not to have a full "kubefirst" locally, but a subset to sample the key experience flow. To avoid derail the focus from tooling that can be focus the flavors selected and also to adapt to the environment limitations. As instead of relying of "fake s3" buckets, we can just use a simple local folder makes more sense for local user learning curve._ 

_And the local experience as an spring board for the cloud experience initally._

**Comment by 6za** [comment]
- https://k3d.io/v4.4.8/usage/guides/registries/
- https://registry.terraform.io/providers/3rein/k3d/latest/docs/resources/registry
- https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/raft_autopilot

**Comment by pagottoo** [comment]
I like the approach to using the native services, for example:

- replace s3 with minio;
- keep vault, but with another backend storage;
- ecr with harbor;

Or if it's possible to run these services inside the cluster (in containers, for example).

This approach will quickly unlock possibilities to run on-premises environments and even another cloud provider.
Another advantage to using agnostic solutions is to avoid cloud lock-in, e helps us to bring more CNCF solutions to our stack.

**Comment by 6za** [comment]
Initial stab started here: https://github.com/kubefirst/kubefirst/pull/535

**Comment by 6za** [comment]
The initial command line choice after this PR:

Regular AWS:
```bash 
kubefirst --admin-email user@domain.com --cloud aws --cloud aws --hosted-zone-name my.domain.com --profile default
````

Using K3d as a new cloud flavor:

```bash 
kubefirst --admin-email user@domain.com --cloud k3d
```

The create step would be the same: 
```bash 
kubefirst cluster create
```

**Comment by Opswatch** [comment]
Looking forward to local gitlab support with k3d :D

**Comment by Opswatch** [comment]
> I like the approach to using the native services, for example:
> 
>     * replace s3 with minio;
> 
>     * keep vault, but with another backend storage;
> 
>     * ecr with harbor;
> 
> 
> Or if it's possible to run these services inside the cluster (in containers, for example).
> 
> This approach will quickly unlock possibilities to run on-premises environments and even another cloud provider. Another advantage to using agnostic solutions is to avoid cloud lock-in, e helps us to bring more CNCF solutions to our stack.

Out of curiosity why harbour and not gitlab container registry? -https://docs.gitlab.com/ee/user/packages/container_registry/

**Comment by jarededwards** [comment]
hi @Opswatch! thanks for asking - none of the above were definitive choices and we're still actively developing our initial `kubefirst local` work. we ended up starting with github and using their container registry and will likely choose gitlabs native container registry as well when we add gitlab support. we're really excited about how the local experience is coming together, i've opened #598 for us to add into one of our upcoming releases - stay tuned!

**Comment by 6za** [comment]
This is issue was basically, the birth of local as concept, it was delivered some releases ago. In particular the first after kubecon, marking as done.
