### ISSUE TITLE
kubefirst issues template needed

### ISSUE THREAD

**Issue by johndietz** [kubefirst/kubefirst#503]
when users submit issues, they're presented with a blank template and we don't guide them on what we need them to tell us. we should fix that.

rough thoughts are that a user should have to tell us:
- what version of the cli
- github stack or gitlab stack
- the init command
- anything interesting about their runtime environment

it would be great if the `kubefirst info` command (or some new command) could tell us this information automatically so they can copy and paste it into the issue. then we could just have a section that says something like

## result from kubefirst info:
```
<paste result here>
```

**Comment by echoboomer** [comment]
https://github.com/kubefirst/kubefirst/tree/main/.github/ISSUE_TEMPLATE
