### ISSUE TITLE
console in cluster

### ISSUE THREAD

**Issue by johndietz** [kubefirst/kubefirst#507]
today (1.9.0) the console app is only presented to the installer, and becomes unavailable after install.

we would like to make the console application available in the cluster as well as a permanent fixture in their new management cluster. it would be good to implement a reverse auth proxy that leverages our new vault sso. this way we can advise the user to log into the console application after install, and they'll be pre-authenticated into all of the other apps we need to guide them toward.

details:
- the console chart needs to be helm published to a semi-permanent chart host, can be github if that completes the story faster
- the console app's reverse auth proxy should be bundled as a chart dependency. it should not be a standalone item in the registry
- any reverse auth proxy is adequate as long as the oidc secrets can be stored securely - i've used this one in the past with good success https://github.com/vouch/vouch-proxy
- the console app should be added to the gitops-template registry and delivered on any sync wave after vault is available and configured
- the console appliction should have an ingress hostname of `kubefirst.<AWS_HOSTED_ZONE_NAME>` - this is unorthodox as we almost always want to have the hostname match the application name for a frontend app. console will be an exception to that preference as it will receive the kubefirst brand in the hostname.
- the console application's bundled vouch proxy will need an application_id and secret_key from vault in the oidc path. it will need to get its secrets by leveraging external-secrets. this custom resource needs to be bundled with the application.

**Comment by pagottoo** [comment]
task done, released on https://github.com/kubefirst/kubefirst/releases/tag/1.9.9
