### ISSUE TITLE
new switch --bot-password needs correction

### ISSUE THREAD

**Issue by johndietz** [kubefirst/kubefirst#511]
the new --bot-password switch that was recently introduced doesn't have the intended influence on the initial admin user created on a github stack. it was introduced as part of the correction from #510 . the workaround is to use the root vault token to get the kubefirst-bot password at /users/kbot. that password does work with user kbot via sso as an admin throughout the platform.

**Comment by echoboomer** [comment]
This code has since been deprecated and is no longer used.
