### ISSUE TITLE
single point for constants

### ISSUE THREAD

**Issue by converge** [kubefirst/kubefirst#516]
some constants are initialised during ReadConfig(), a better place for constants are `pkg/constants`,

**Comment by bhavyastar** [comment]
Hey, @converge I would like to work on this issue. Could you please assign this to me?

**Comment by jarededwards** [comment]
hi @bhavyastar ! thanks for reaching out here, we're going to be grooming all of our issues on tuesday next week and will re-assign anything relevant then. We just did a major overhaul on how our installer works implementing Civo cloud and would like that to be the pattern we adopt moving forward for this issue specifically. if you dont mind, can i ping you next week after we have a new game plan for how we would like to handle the migration?

**Comment by bhavyastar** [comment]
Yup, thanks a lot. No problem. @jarededwards

**Comment by echoboomer** [comment]
Closing as this is no longer necessary for generalized platform constants.
