### ISSUE TITLE
GITLAB - Fix terraform.ApplyUsersTerraform(globalFlags.DryRun, directory)

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#519]
This function doesn't work for gitlab user setup. We need to add the parameters to make it work on gitlab. 

Atlantis is the key: https://github.com/kubefirst/gitops-template/blob/main/terraform/vault/secrets.tf#L35

**Comment by 6za** [comment]
Relates to this not be fixed: https://github.com/kubefirst/kubefirst/issues/514

**Comment by echoboomer** [comment]
Not relevant anymore.
