### ISSUE TITLE
Wire Validations to init

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#524]
# What?

To check if on init time if: 
- are ECR already present in aws installs
- are repos already present in github installs

# how?

For `are repos already present in github installs` we can recycle: 
https://github.com/kubefirst/kubefirst/blob/main/cmd/githubRemoveValidate.go

If this command erros, mean a repo exists. We can also improve command.

**Comment by converge** [comment]
As a Kubefirst developer I want to be informed if I already have Kubefirst resources in AWS ECR, and in my GitHub organization.

AC1: if I already have Kubefirst ECR repositories gitops-cluster_name, metaphor-frontend-cluster_name, metaphor-go-cluster_name or metaphor-cluster_name, I want to be informed to delete those resources before running `kubefirst init` again.
AC2: if my GitHub organization already have Kubefirst repositories (gitops, metaphor, metaphor-go, metaphor-frontend), I want to be informed to delete those resources before running `kubefirst init` again.
AC3: if my GitHub organization already have admin users associated with the organization, I want to be informed to delete those resources before running `kubefirst init` again.

**Comment by 6za** [comment]
We may want to have a command for "pre-flight" check, that could automate some of checks we use  on ci/cd to check allowing also users to use them. 

Like: 
- Repo
- ECR
- Query AWS resources by the install tag.. and log what was found..

**Comment by 6za** [comment]
@pagottoo / @marinhojess  We can query the some resources using `terraform` `data`, right?

**Comment by marinhojess** [comment]
Yes, we can use _external_data_sources_ on terraform to perform a script to check it by making a call directly to the cloud API.

**Comment by echoboomer** [comment]
This has since been implemented.
