### ISSUE TITLE
Error on Terraform  AWS provider 

### ISSUE THREAD

**Issue by casperakos** [kubefirst/kubefirst#558]
Hi team,

I'm getting this error when I'm trying to create the cluster using AWS sts:

error configuring Terraform AWS Provider: error validating provider credentials: error calling sts:GetCallerIdentity: operation error STS: GetCallerIdentity, failed to resolve service endpoint, an AWS region is required, but was not found

I see the #406 was about the same issue and that it has been resolved but I'm getting that error with the latest kubefirst release.

**Comment by 6za** [comment]
Thanks for reporting, We will investigate and execute some test and return to you.

**Comment by 6za** [comment]
What version of kubefirst are you using?  
`kubefirst info` may help with that.

**Comment by marinhojess** [comment]
Hi @casperakos, 

Could you please share with us the kubefirst init command line which you used?

Thank you!

**Comment by casperakos** [comment]
FYI, just tried with Gitlab and it works without any errors using the same account.

**Comment by marinhojess** [comment]
Thank you for the additional details, @casperakos!

We performed some installations based on the scenarios you gave us, but we were unable to reproduce this behavior. 

Investigating this, we came across this issue in the terraform provider, https://github.com/hashicorp/terraform-provider-aws/issues/26043, apparently this happens when the region name is miss spelled. Is it possible it had a typo in the region name?

Could you please test it again using our latest 1.9.9 version, and see if the issue still persists?

If the issue persists, could you send us the last lines of the log generated inside the logs directory? Please make sure to remove any sensitive data from logs.

**Comment by casperakos** [comment]
Hi @marinhojess ,

Here is the logs from a try with the latest 1.9.9 version:

`OUT:  [0m[1mInitializing provider plugins...[0m
OUT:  - Finding integrations/github versions matching "4.26.0"...
OUT:  - Finding latest version of hashicorp/aws...
OUT:  - Installing integrations/github v4.26.0...
OUT:  - Installed integrations/github v4.26.0 (signed by a HashiCorp partner, key ID [0m[1m38027F80D7FD5FB2[0m[0m)
OUT:  - Installing hashicorp/aws v4.34.0...
OUT:  - Installed hashicorp/aws v4.34.0 (signed by HashiCorp)
OUT:  
OUT:  Partner and community providers are signed by their developers.
OUT:  If you'd like to know more about provider signing, you can read about it here:
OUT:  https://www.terraform.io/docs/cli/plugins/signing.html
OUT:  
OUT:  Terraform has created a lock file [1m.terraform.lock.hcl[0m to record the provider
OUT:  selections it made above. Include this file in your version control repository
OUT:  so that Terraform can guarantee to make the same selections by default when
OUT:  you run "terraform init" in the future.[0m
OUT:  
OUT:  [0m[1m[32mTerraform has been successfully initialized![0m[32m[0m
OUT:  [0m[32m
OUT:  You may now begin working with Terraform. Try running "terraform plan" to see
OUT:  any changes that are required for your infrastructure. All Terraform commands
OUT:  should now work.
OUT:  
OUT:  If you ever set or change modules or backend configuration for Terraform,
OUT:  rerun this command to reinitialize your working directory. If you forget, other
OUT:  commands will detect it and remind you to do so if necessary.[0m
INFO: Running /Users/test/.k1/tools/terraform
 export TF_VAR_atlantis_repo_webhook_secret = ********************
 export TF_VAR_kubefirst_bot_ssh_public_key = *********************************************************************************
 export AWS_SDK_LOAD_CONFIG = *
 export AWS_PROFILE = ******************
 export GITHUB_TOKEN = ****************************************
 export GITHUB_OWNER = ***************
ERR:  [31m╷[0m[0m
ERR:  [31m│[0m [0m[1m[31mError: [0m[0m[1mInvalid provider configuration[0m
ERR:  [31m│[0m [0m
ERR:  [31m│[0m [0m[0mProvider "registry.terraform.io/hashicorp/aws" requires explicit
ERR:  [31m│[0m [0mconfiguration. Add a provider block to the root module and configure the
ERR:  [31m│[0m [0mprovider's required arguments as described in the provider documentation.
ERR:  [31m│[0m [0m
ERR:  [31m╵[0m[0m
ERR:  [31m╷[0m[0m
ERR:  [31m│[0m [0m[1m[31mError: [0m[0m[1merror configuring Terraform AWS Provider: error validating provider credentials: error calling sts:GetCallerIdentity: operation error STS: GetCallerIdentity, failed to resolve service endpoint, an AWS region is required, but was not found[0m
ERR:  [31m│[0m [0m
ERR:  [31m│[0m [0m[0m  with provider["registry.terraform.io/hashicorp/aws"],
ERR:  [31m│[0m [0m  on <empty> line 0:
ERR:  [31m│[0m [0m  (source code not available)
ERR:  [31m│[0m [0m
ERR:  [31m╵[0m[0m
error: /Users/test/.k1/tools/terraform failed exit status 1
error: terraform apply for github failed exit status 1
[000] Create duration is 23.028817527s`

**Comment by casperakos** [comment]
Interesting, I just tried to rename the AWS profile I was using to `default` and the now it succeeds. It seems that if you have different profiles in ~/.aws/credentials the `default` it only succeeds if you use the default as profile alias?

**Comment by marinhojess** [comment]
Hey @casperakos,

I performed tests based on the scenario you informed us, renaming the AWS profile to a name that was different from the default, but all tests were executed successfully.

Would you mind redoing the test with a profile name other than "default" and sending us the log of the init command?

Thank you!
