### ISSUE TITLE
Zerossl or Google's Acme Server should be supported providers

### ISSUE THREAD

**Issue by autotune** [kubefirst/kubefirst#58]
Just a suggestion, I always have issues with letsencrypt, and that seems to be the case here as well. It'd be great to have additional support for either https://zerossl.com, https://cloud.google.com/blog/products/identity-security/automate-public-certificate-lifecycle-management-via--acme-client-api, or both. Additional options are are a Good Thing imho! To clarify, the installation is stuck on "https://gitlab.example.com/help is not yet ready" and the reason is because the certificate is failing to be issued.

**Comment by johndietz** [comment]
this is no longer needed with 1.8 moving gitlab to kubernetes, it'll now take advantage of cert-manager and the letsencrypt certificate provider. closing issue.
