### ISSUE TITLE
docs: requirements to run k1 local

### ISSUE THREAD

**Issue by pagottoo** [kubefirst/kubefirst#637]
add on docs the requirements (hardware and limitations) when running k1 locally

**Comment by converge** [comment]
following this user comment[1], add this validation:

- check if there is at least 10GB of disk size available before start the installation

This step can be done at the (init / PreRunE) for the local command.

[1] https://github.com/kubefirst/kubefirst/issues/626#issuecomment-1295127556

**Comment by converge** [comment]
sometimes I don't have Docker running in my machine, and I can start the installation. The installation fails at the moment of the creation fo the K3d cluster.

Add this validation:

- check if Docker daemon is up and running before start the instllation

**Comment by marinhojess** [comment]
It would be nice to have a check before cluster creation to ensure there is no repository with the same name pre-existing on github.

**Comment by marinhojess** [comment]
Check if there's an environment variable called GITHUB_AUTH_TOKEN.

**Comment by fharper** [comment]
the OP docs updates suggestions were done.
