### ISSUE TITLE
add instructions how to create new commands

### ISSUE THREAD

**Issue by converge** [kubefirst/kubefirst#643]
There is internal documentation on how to create new commands, and handle flags, env. values and config file, that we would like to make it public.

Should we move it into kubefirst documentation (docs.kubefirst.io) or ... ?

**Comment by fharper** [comment]
I like the idea, it would help contributors to add new features. It may be too much detail in the contributing guide maybe? In that case, I could see this as a blog article, and we could link to it from `CONTRIBUTING.md` WDYT?

**Comment by converge** [comment]
Sounds like a good idea!

**Comment by fharper** [comment]
From a past Slack discussion, we didn't want to move forward with that for now.
