### ISSUE TITLE
add fix for state store github repos issue

### ISSUE THREAD

**Issue by converge** [kubefirst/kubefirst#674]
At the end of the installation, atlantis plan is called to change the Terrraform S3 bucket address, from local, to the internal Kubernetes address. The change is applied successfully, but the plan tries to create the GitHub buckets again.

We want to avoid the GitHub repos. being created again on Atlantis plan.

**Comment by 6za** [comment]
@pagottoo is this something you are already updating related to atlantis variables?

**Comment by pagottoo** [comment]
testing...

**Comment by 6za** [comment]
- Based on chat with @pagottoo  this is related to #809. 

Waiting this to be completed, before checking:
- #809
