### ISSUE TITLE
local cosmetic changes

### ISSUE THREAD

**Issue by converge** [kubefirst/kubefirst#675]
- info screen doesnt show progress, it start showing the progress when the code command is called (create local)
- progress bar no progressing correctly
- waiting for authorization (95 seconds) counter is not counting correctly
- disk pressure ( k3d change disk pressure setting on k3d cluster creation ) / try it ( low prio )

**Comment by 6za** [comment]
Progress bar issue fixed for local already on main.

**Comment by 6za** [comment]
Disk pressure fix also already on main.

**Comment by converge** [comment]
waiting for authorization (95 seconds) counter is not counting correctly
 #704

**Comment by 6za** [comment]
This was already addressed during bug fixes for 1.11
