### ISSUE TITLE
metaphor-frontend needs adjustment for backend api configs

### ISSUE THREAD

**Issue by johndietz** [kubefirst/kubefirst#720]
metaphor frontend should communicate to the 2 backend services using internal routing - like:
development.metaphor-development.svc.cluster.local
instead of:
metaphor-development.<AWS_HOSTED_ZONE>

local metaphor can't reach its backends without overriding. while an override would fix it, we should probably be demonstrating the internal routing instead as the chart's default opinion since we're able to teach folks how interservice communication works.

**Comment by fharper** [comment]
@CristhianF7 is working on this.
