### ISSUE TITLE
spike: see what it will take to enable https access to local services throughout kubefirst local

### ISSUE THREAD

**Issue by johndietz** [kubefirst/kubefirst#746]
kubefirst local presently requires a lot of http communication with port forwards to non-https service endpoints. we would love to find a way to secure that communication over https.
it's likely that hashicorp vault can be leveraged as a certificate issuer for the k3d cluster so reaching tools like vault over ingress were done over https. 
bonus points if we can convince the user's browser to trust the tls certificates without any proactive user action, but we have to be careful to not overreach. if it's more appropriate to document how to let them trust the vault ca, we can do that too.
https://cert-manager.io/docs/configuration/vault/
there is no requirement for external access to https services, just the host browser

**Comment by johndietz** [comment]
see also https://github.com/FiloSottile/mkcert

**Comment by converge** [comment]
implemented
