### ISSUE TITLE
spike: what will it take to provide a local dns similar to the cloud dns experience

### ISSUE THREAD

**Issue by johndietz** [kubefirst/kubefirst#747]
with an ingress controller available to the k3d cluster, it'd be nice to have a way to more closely resemble kubefirst cloud ecosystems with a local dns implementation so we could have our services available at something to the effect of 
https://vault.kubefirst.local
https://argocd.kubefirst.local
etc.

explore localdev-me first (credit abdallah) https://codeengineered.com/blog/2022/localdev-me/

dns only needs to work on the host machine

**Comment by Opswatch** [comment]
I use https://github.com/guumaster/hostctl for our local environments works pretty good

**Comment by k1-dev1** [comment]
@Opswatch tks for the hint ! We're at final implementation phase of localdev.me , but we will also consider using hostctl, thanks a lot!

**Comment by converge** [comment]
@Opswatch tks for the hint ! We're at final implementation phase of localdev.me , but we will also consider using hostctl, thanks a lot!

**Comment by converge** [comment]
implemented and pending release
