### ISSUE TITLE
establish a frictionless user password management through vault

### ISSUE THREAD

**Issue by johndietz** [kubefirst/kubefirst#748]
users need to be able to reset their passwords frictionlessly

currently our terraform implementation is a little awkward for passwords. i think if we change our password to a simple null_resource that invokes a call to vault one time only, the state will stop being tracked by terraform state, which is ideal.

with that change in place, we'd still need to add the ability to change a password, which we could do with a kubefirst cli command provided the user was in the administrator role, or provided the password belonged to the user requesting the password change.

still need to flesh this story out more completely.

**Comment by jarededwards** [comment]
@6za this might be helpful for when you need to add vault acl policies
https://developer.hashicorp.com/vault/tutorials/policies/policy-templating

**Comment by 6za** [comment]
Return to this, after checking vault in `local mode`, we don't have most of the rules for testing this police changes. I will explore it for the cloud based installs. 

The general plans, as discussed internally is: 
- Find a police rule, similar to https://stackoverflow.com/questions/60762255/is-there-a-way-to-allow-a-user-to-change-its-own-password-on-hashicorps-vault that allow users to update their on passwords. Using police templates. 
- Create a police that allows admins to update all users passwords. 

Then the question is if we need a UI for it, or Vault would based on the police to allow use vault owns UI to update it.

**Comment by 6za** [comment]
Initial solution. 

Policy for developers/admins:
```hcl
path "auth/userpass/users/{{identity.entity.name}}" {
  capabilities = [ "update" ]
  allowed_parameters = {
    "password" = []
  }
}
```
> Users can change their password via vault CLI at the Vault UI. 

Impact: 
![image](https://user-images.githubusercontent.com/53096417/204790423-8c4b7704-13b5-4c5a-a4cc-db87fe1daac3.png)

**Comment by 6za** [comment]
Polices for dev: 
```hcl
# pwd change
path "sys/auth" {
  capabilities = ["read"]
}
path "auth/userpass/users/*" {
  capabilities = ["list"]
}


path "auth/userpass/users/{{identity.entity.name}}" {
  capabilities = ["read", "update","create"]
}

```
> Reference: https://github.com/kubefirst/gitops-template/blob/main/terraform/vault/policies.tf#L144

This allows Developers to update their own password via vault cool ui. 

Sample: 
![k1-watcher-crd-20221130-pwdchange](https://user-images.githubusercontent.com/53096417/204801723-602beff0-12f9-45a9-bb9c-4d85a889d1ce.gif)

**Comment by 6za** [comment]
The new password becomes the valid password. :)

**Comment by 6za** [comment]
The current admin policy already allow admins to replace all users passwords

**Comment by 6za** [comment]
I was not able to find a solution that offers the same "easy to use".. without showing the list of active users in the vault tool. 

There is another policy: 
```hcl
path "auth/userpass/users/{{identity.entity.name}}" {
  capabilities = [ "update" ]
  allowed_parameters = {
    "password" = []
  }
}
```

That allow only password to be changed, via ie: 
```bash 
vault write auth/userpass/users/done password=newpassword
```

As the vault UI has a cli based on your user, it also produce the same effect, although it is a bit "more advanced" for my taste. 

If we go on that path, we would need to create some UI app, or add something to console app, in logged mode to allow user using SSO to update their password by calling the [password update API](https://developer.hashicorp.com/vault/api-docs/auth/userpass#update-password-on-user).  I think to create a new UI it would be a bit overkill, so I rather to stick with vault as the tool all things users.

**Comment by 6za** [comment]
As discussed, the current solution is missing a mechanism to ignore password changes outside of terraform: 
```bash
Terraform will perform the following actions:

  # module.developer_one.gitlab_user.user[0] will be updated in-place
~ resource "gitlab_user" "user" {
        id               = "3"
      ~ name             = "Dev One" -> "Dev One person 1"
        # (11 unchanged attributes hidden)
    }

  # module.developer_one.vault_generic_endpoint.user will be updated in-place
~ resource "vault_generic_endpoint" "user" {
      ~ data_json            = (sensitive value)
        id                   = "auth/userpass/users/done"
        # (6 unchanged attributes hidden)
    }

  # module.kubefirst_bot.vault_generic_endpoint.user will be updated in-place
~ resource "vault_generic_endpoint" "user" {
      ~ data_json            = (sensitive value)
        id                   = "auth/userpass/users/kbot"
        # (6 unchanged attributes hidden)
    }

Plan: 0 to add, 3 to change, 0 to destroy.
 
```

For that, some terraform need to be tweaked.

**Comment by 6za** [comment]
Even without changing password, this is always detected as change: 
```
  # module.developer_one.vault_generic_endpoint.user will be updated in-place
~ resource "vault_generic_endpoint" "user" {
      ~ data_json            = (sensitive value)
        id                   = "auth/userpass/users/done"
        # (6 unchanged attributes hidden)
    }

  # module.kubefirst_bot.vault_generic_endpoint.user will be updated in-place
~ resource "vault_generic_endpoint" "user" {
      ~ data_json            = (sensitive value)
        id                   = "auth/userpass/users/kbot"
        # (6 unchanged attributes hidden)
    }

```

**Comment by 6za** [comment]
After the ignore state rules: 
```bash
  # module.developer_one.gitlab_user.user[0] will be updated in-place
~ resource "gitlab_user" "user" {
        id               = "3"
      ~ name             = "Dev One person 1" -> "Dev One not today"
        # (11 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

```

password is not touched anymore.

**Comment by 6za** [comment]
PR ready, waiting for approvals. 

For a future discussion we will cover how to make easier to admins to send the initial password or token to developers, post their creation.
