### ISSUE TITLE
introduce informer pattern to local

### ISSUE THREAD

**Issue by johndietz** [kubefirst/kubefirst#750]
the informer patterns that @6za has been working on might serve our users that have older laptops better than our existing  operation flow controls. we've received reports of some users waiting minutes for argocd to start as an example. informers would be a more reliable state confirmation than some of our current techniques.

**Comment by johndietz** [comment]
note: this may help with our internal ci operations as well

**Comment by 6za** [comment]
The informer pattern, it is now available as an operator here:
- [X] https://github.com/kubefirst/kubefirst-watcher-operator

and the behavior implemented here: 
- [X] https://github.com/kubefirst/kubefirst-watcher

Although, it is operational. I need to add some tooling to allow the image/helm deployment to be delivered via automated CI. 

- [ ] Automate build of docker image of https://github.com/kubefirst/kubefirst-watcher
- [ ] Automate helm updates of operator: https://github.com/kubefirst/kubefirst-watcher-operator
