### ISSUE TITLE
spike: determine the minimum specs of kubefirst local

### ISSUE THREAD

**Issue by johndietz** [kubefirst/kubefirst#753]
can use varying ec2 instance sizes with ubuntu to measure the stability of the kubefirst local experience.
document the results, and provide a good recommendation to users who have laptops that don't support kubefirst local.

**Comment by converge** [comment]
this information was introduced in the 1.11 release, and is available here https://docs.kubefirst.io/kubefirst/local/limitations.html#hardware-recommendation
