### ISSUE TITLE
Spot instance kubefirst opinion doesn't persist in Atlantis

### ISSUE THREAD

**Issue by johndietz** [kubefirst/kubefirst#755]
kubefirst offers the ability to run spot instances to save on infra costs. when we run kubefirst cluster create with the `--aws-nodes-spot` flag, it correctly establishes the cluster with spot nodes as the underlying ec2 type. however, if you run a plan against `gitops/terraform/base` after provisioning, when atlantis runs the plan, it tries to change the instance type back to `on demand` instances. this is likely due to a TF_VAR_ variable that is used in the cli, but isn't persisted in the atlantis secret.

**Comment by fharper** [comment]
We removed this flag when we refactored our code to introduce Civo support. We may add it back in the future, but not right now.

@johndietz will add a comment in the [gitops-template repository](https://github.com/kubefirst/gitops-template) where could can manually add this feature. Once done, he'll share the link to the specific line as a comment on this issue.
