### ISSUE TITLE
Improve template download logic

### ISSUE THREAD

**Issue by converge** [kubefirst/kubefirst#757]
In order to simplify the logic to download the correct template based on the release, as a Kubefirst user I want to have the following logic to select the current template version:

```  
    // "development" is the default value for kubefirst version
    // ldflag changes this variable configs.K1Version
	if configs.K1Version != "development" {
      // it means its a built/binary, and has a tag like 1.10.6
      // we can use this version(1.10.6) to download the templates
    }

    // if not a built/binary version ->
    // try to use gitops-branch flag, if not provided set gitops-branch to main as default
    // try to use metaphor-branch flag, if not provided set metaphor-branch to main as default
```

AC1: we unsure it works as expected for local development on (local, cloud github and cloud aws)
AC2: the logic works for local development using `go run` and using the binary/built version

**Comment by converge** [comment]
implemented

**Comment by 6za** [comment]
Fix in the code provided at: https://github.com/kubefirst/kubefirst/issues/818

**Comment by 6za** [comment]
This mode should run an respect the flag to of gitops-branch if is provided, the branch should be cloned, not the tag: 

```bash 
go build -ldflags="-X github.com/kubefirst/kubefirst/configs.K1Version=1.10.11" .
./kubefirst local --gitops-branch add-ingress-localhost
```

**Comment by 6za** [comment]
The exiting implementation was preventing, developers that use the `LDFLAGS` to test from branches, as it was assuming that only developers not using LDFLAGs would like to use the branch selection flags, but that should be available always even for built releases. 


````bash 
go build -ldflags="-X github.com/kubefirst/kubefirst/configs.K1Version=1.10.11" .
./kubefirst local --gitops-branch add-ingress-localhost
```
