### ISSUE TITLE
local - local install is logging github-token   (should we avoid that?)

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#763]
# Logs

```bash
LOG: 2022/11/17 19:49:41.673707 /app/cmd/destroyLocalGithub.go:54: {false false false false false false} &{l.. supopressed} 
```

This line is dumping a lot of personal information from the ones that run the install, including:
- user
- githubtoken

**Comment by converge** [comment]
hi @timoguin , tks for bring it back! We just marked this with higher priority, and should be fixed soon. I'll keep you posted!

**Comment by echoboomer** [comment]
This should no longer be an issue. Please report any similar issues if they arise again in the future.
