### ISSUE TITLE
improve destroy for local

### ISSUE THREAD

**Issue by converge** [kubefirst/kubefirst#794]
As a Kubefirst user, I want to have a stable local cluster destroy command.

AC1: the destroy command is able to delete the user gitops, metaphor, metaphor-go and metaphor-frontend
AC2: K3d cluster is deleted
AC3: if the installation fails, the destroy command should be able to delete/destroy the current installation resources

**Comment by 6za** [comment]
Connected to: https://github.com/kubefirst/kubefirst/issues/762
