### ISSUE TITLE
atlantis should load vars used during provision

### ISSUE THREAD

**Issue by pagottoo** [kubefirst/kubefirst#809]
Atlantis needs to load all the vars used during the bootstrap cluster to keep consistently in the futures plan/apply to avoid wrong changes.

**Comment by 6za** [comment]
@pagottoo  - is this still happening?

**Comment by pagottoo** [comment]
The missing variables on Atlantis secret were AMI and instance type.

PR: 
- https://github.com/kubefirst/gitops-template/pull/246
