### ISSUE TITLE
kubefirst eks needs upgrade

### ISSUE THREAD

**Issue by johndietz** [kubefirst/kubefirst#811]
users are met in eks module in aws with a notice that they're on the oldest supported version of kubernetes
<img width="1358" alt="image" src="https://user-images.githubusercontent.com/3649336/205174980-9ad1f35f-3e2a-45bd-96fa-9a1caf778c73.png">

biggest risk will likely be ci issues on the publishing pipeline, will need to confirm ci is fully operational as part of this story

**Comment by pagottoo** [comment]
PR: https://github.com/kubefirst/gitops-template/pull/211

**Comment by pagottoo** [comment]
Closing, done in: https://github.com/kubefirst/gitops-template/pull/211
