### ISSUE TITLE
AWS_PROFILE isn't set when executing `kubectl` and causes authentication errors

### ISSUE THREAD

**Issue by jarededwards** [kubefirst/kubefirst#838]
when the installer attempts to install argocd an authorization error is thrown if the AWS_PROFILE in the users shell does not match the profile flag provided to the kubefirst cli. With the user providing this value we need to make sure that the entire installation honors the value provided

**Comment by 6za** [comment]
- related #900

**Comment by 6za** [comment]
- Solved on #900
