### ISSUE TITLE
eks node needs iam policy tightening

### ISSUE THREAD

**Issue by jarededwards** [kubefirst/kubefirst#841]
this role should be removed, with the adoption of IRSA Chartmuseum and Vault were overlooked to get permissions via their service account
https://github.com/kubefirst/gitops-template/blob/main/terraform/base/eks/main.tf#L241-L268

**Comment by jarededwards** [comment]
adopted IRSA for remaining workloads in cluster

**Comment by 6za** [comment]
@jarededwards  is this solved with the new AIM roles? or do still have work to do?

Id this part of 1.11?

**Comment by 6za** [comment]
fixed at: https://github.com/kubefirst/gitops-template/commit/2c9a0e9e342da8af133453a2b257a93d2cd5bebc

https://github.com/kubefirst/gitops-template/pull/227
