### ISSUE TITLE
implement force destroy for GitLab cluster destroy

### ISSUE THREAD

**Issue by converge** [kubefirst/kubefirst#852]
**As a Kubefirst user, I want to rely on `kubefirst cluster destroy` command when I request to delete all the provisioned resources Kubefirst installed in my cluster.** 

**background**: As I Kubefirst user, I don't know the Kubefirst internal details, and don't want to research what is the correct flag to delete the Kubefirst provisioned resources. I would like to have a smooth experience using the cluster destroy command, and don't want to debug to know what I should do next, `cluster destroy` should do the job for me.

- AC1: this update is for GitLab only
- AC2: destroy command uses current terraform approach to destroy resources, if it fails, force destroy the resource
- AC3: no flags are necessary to destroy resources

_extras (if possible):_
- AC4: the implementation doesn't use shell OS calls
- AC5: the implementation doesn't use sleep times (to force wait)

related: https://github.com/kubefirst/kubefirst/issues/395

Please check: https://github.com/kubefirst/kubefirst/issues/887

**Comment by echoboomer** [comment]
This is no longer relevant given the latest command formatting.
