### ISSUE TITLE
Kubefirst Local - Github Auth Flow - Repeat Token Request

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#866]
# Overview

**Repeated prompting for GitHub device auth flow**

# Details 

When not used the variable `KUBEFIRST_GITHUB_AUTH_TOKEN` on your terminal for the installation. The installer by design don't store the users token, so every interactions with installer that needs a github token may request access to github. 
```bash 
export KUBEFIRST_GITHUB_AUTH_TOKEN='your github token'
```

It is not clear from the feedback, if there is multiple request of token on the same interaction, but I believe that is not the case. 

# Goal 

If possible, to explore a better User Experience to handle this credentials and flow to get a token, and document better the existence of workarounds. 
 

Source: https://github.com/kubefirst/kubefirst/discussions/848

**Comment by 6za** [comment]
@converge  / @jarededwards Is this a 1.11 deliverable?

**Comment by 6za** [comment]
There was a PR in work by @converge  exploring this, I am not aware if this was completed.  I don't see changes in the code related to this flow: 

- https://github.com/kubefirst/kubefirst/blob/main/internal/wrappers/github.go#L13

**Comment by converge** [comment]
created a new ticket with story details https://github.com/kubefirst/kubefirst/issues/1065

**Comment by 6za** [comment]
I think we should keep this ticket open at least to allow the workaround documentation to be covered on the current release.
