### ISSUE TITLE
--use-telemetry false not honnored - probably local

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#869]
# Overview 

It seems that because of bad binding of the flag `--use-telemetry` telemetry is not properly skipped on some flavor of installation. 

I believe the issue reported is focused on local, that is been re-factored for 1.11. 

# Goals

- [ ] Review on 1.11 if local install `--use-telemetry` is honored 
- [ ] Review on 1.11 if aws-github install `--use-telemetry` is honored 
- [ ] Review on 1.11 if aws-gitlab install `--use-telemetry` is honored 

# Notes

- Possible regression issue due to `local` refactor of flags handling incomplete on 1.10.8. 

Source: https://github.com/kubefirst/kubefirst/discussions/848

**Comment by converge** [comment]
tested a full install on `local`, it's working as expected. There is maybe a confusion how the flag should be used, the docs were updated to make it clear how to use `use-telemetry` flag.

https://github.com/kubefirst/kubefirst/pull/877

**Comment by timoguin** [comment]
> tested a full install on `local`, it's working as expected. There is maybe a confusion how the flag should be used, the docs were updated to make it clear how to use `use-telemetry` flag.
> 
> https://github.com/kubefirst/kubefirst/pull/877

Perfect. I'm pretty sure I was using `--use-telemetry false`. I'll check it out and confirm.

**Comment by fharper** [comment]
Good suggestion @timoguin, I created this issue for the team https://github.com/kubefirst/kubefirst/issues/1021
