### ISSUE TITLE
kubefirst clean --rm-logs is not deleting logs directory in CWD

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#871]
# Overview 

`--rm-logs` flag seems to be ignored

# Details 

- https://github.com/kubefirst/kubefirst/blob/1_11_release/cmd/clean.go#L64 it seems the flag is wired in, but I believe we need to confirm it desired effect and if it is really working as expected. 

Source: https://github.com/kubefirst/kubefirst/discussions/848

**Comment by converge** [comment]
done at https://github.com/kubefirst/kubefirst/pull/881
