### ISSUE TITLE
Create an issue form template

### ISSUE THREAD

**Issue by fharper** [kubefirst/kubefirst#875]
Create an issue form template to help users' problems reporting

**Comment by echoboomer** [comment]
Is this not it?

https://github.com/kubefirst/kubefirst/tree/main/.github/ISSUE_TEMPLATE

Do we still need this issue?

**Comment by fharper** [comment]
Yes, it's https://github.com/kubefirst/kubefirst/blob/main/.github/ISSUE_TEMPLATE/bugs.yml
