### ISSUE TITLE
implement force destroy for GitHub cluster destroy

### ISSUE THREAD

**Issue by converge** [kubefirst/kubefirst#887]
**As a Kubefirst user, I want to rely on `kubefirst cluster destroy` command when I request to delete all the provisioned resources Kubefirst installed in my cluster.** 

**background**: As I Kubefirst user, I don't know the Kubefirst internal details, and don't want to research what is the correct flag to delete the Kubefirst provisioned resources. I would like to have a smooth experience using the cluster destroy command, and don't want to debug to know what I should do next, `cluster destroy` should do the job for me.

- AC1: this update is for GitHub only
- AC2: destroy command uses current terraform approach to destroy resources, if it fails, force destroy the resource
- AC3: no flags are necessary to destroy resources

_extras (if possible):_
- AC4: the implementation doesn't use shell OS calls
- AC5: the implementation doesn't use sleep times (to force wait)

related: https://github.com/kubefirst/kubefirst/issues/395

Please check: https://github.com/kubefirst/kubefirst/issues/852

**Comment by converge** [comment]
done at https://github.com/kubefirst/kubefirst/pull/964/files

**Comment by converge** [comment]
destroy is still failing in this case:

![Screenshot 2023-01-11 at 10 56 49](https://user-images.githubusercontent.com/188671/211824696-1d490215-ff6b-49f7-b285-45c1e9889056.png)

**Comment by echoboomer** [comment]
Given the more recent roadmap, this is no longer required.
