### ISSUE TITLE
Metaphor - Publish/Build is not working for github

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#925]
# Overview 

- Post install metaphor unfolding not working

I tried to bump the version, it still not unfolding as expected, fails on publish step. Possible regression issue at the templates.

<img width="1700" alt="image" src="https://user-images.githubusercontent.com/53096417/207874269-121c02bf-21c0-42a3-a677-952a823f7bfc.png">

**Comment by 6za** [comment]
I just checked for gitlab it is also not unfolding: 
![image](https://user-images.githubusercontent.com/53096417/207948196-e2396358-0d12-4cfa-927d-2e8ddcd4e3a2.png)

**Comment by 6za** [comment]
I think this is related to this change: https://github.com/kubefirst/gitops-template/pull/234/files#diff-a356580ab8eb03aa18dabbe7408d37b5d58e1e3ff57f938ee3c571b608aad183

**Comment by 6za** [comment]
CC: @CristhianF7 / @jarededwards

**Comment by 6za** [comment]
After reverting on cloud on my gitops(at gitlab), builds work as expected: 
![image](https://user-images.githubusercontent.com/53096417/207956587-621b711e-c17d-4349-8d4d-87e6173c0764.png)

**Comment by jarededwards** [comment]
reverts the cloud variation
https://github.com/kubefirst/gitops-template/pull/237

**Comment by 6za** [comment]
Validating..

**Comment by 6za** [comment]
Post PR: https://github.com/kubefirst/gitops-template/pull/237 metaphor are back. Their CI works as expected.

**Comment by 6za** [comment]
<img width="948" alt="image" src="https://user-images.githubusercontent.com/53096417/208167682-f46e2dc5-f15d-4550-959c-a0dda24d2ed7.png">
