### ISSUE TITLE
technical debt: allow use of force-redirect based on --disable-tls

### ISSUE THREAD

**Issue by converge** [kubefirst/kubefirst#941]
When user pass the `--disable-tls` flag, force-redirect annontations and redirect should not be used by the YAML files/deployed to the cluster.

This[1] is going to be reverted when there is a way to select TLS and non-TLS during the installation.

[1] https://github.com/kubefirst/gitops-template/pull/238/files

**Comment by 6za** [comment]
This is not needed anymore since #956. All traffic is HTTPS, but we don't makcert install anymore for the user the certs on the Truststore.
