### ISSUE TITLE
[Docs]: add more details on the difference between Kubefirst local & Kubefirst Cloud

### ISSUE THREAD

**Issue by fharper** [kubefirst/kubefirst#946]
### What type of suggestions?

Unclear Documentation

### What page is concerned?

https://docs.kubefirst.io/kubefirst/local/install.html

### What is the issue?

Add more details on the difference between Kubefirst local & Kubefirst Cloud mentioned by @johndietz in #751

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fharper** [comment]
Suggestion for more content by @6za in #751: What can I do with the local kubefirst?

**Comment by 6za** [comment]
![image](https://user-images.githubusercontent.com/53096417/212066931-63e69577-bc0a-4d31-b572-277b8af43d1e.png)
