### ISSUE TITLE
[Docs]: improve the local FAQ

### ISSUE THREAD

**Issue by fharper** [kubefirst/kubefirst#947]
### What type of suggestions?

Missing Information

### What page is concerned?

https://docs.kubefirst.io/kubefirst/github/faq.html

### What is the issue?

Improve the local FAQ as not good enough yet as mentioned by @johndietz in #751

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fharper** [comment]
FAQ suggestion by @6za : Can I keep using local, after I exit the handoff screen?

**Comment by fharper** [comment]
FAQ suggestion by @6za in #751: It would be nice to have some mention that load balancer on cloud installs may hang and not be deleted, making destroy to fail. Guide user for workaround.

**Comment by fharper** [comment]
@johndietz you wrote in #751 that the troubleshooting was incomplete. Feel free to add ideas of what can be added here.

**Comment by converge** [comment]
for reference: https://github.com/kubefirst/kubefirst/pull/1066
