### ISSUE TITLE
[Docs]: details on users and administrators can change their passwords

### ISSUE THREAD

**Issue by fharper** [kubefirst/kubefirst#950]
### What type of suggestions?

Missing Information

### What is the issue?

Write details information on how users and administrators can change their passwords. Sugested by @6za on #751

Check https://github.com/kubefirst/kubefirst/issues/748#issuecomment-1332101262 for more details.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 6za** [comment]
Already updated on the branch: `docs_1_11_local` at the tips section of the vault page.

**Comment by 6za** [comment]
This is already merged to main.
